/* Generated by Yosys 0.32+74 (git sha1 b739213d9, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* dynports =  1  *)
(* src = "fwpic.v:116.1-228.10" *)
module fwpic(clock, reset, adr, int_o, irq);
  (* src = "fwpic.v:123.15-123.18" *)
  input [1:0] adr;
  wire [1:0] adr;
  (* src = "fwpic.v:119.9-119.14" *)
  input clock;
  wire clock;
  (* src = "fwpic.v:133.23-133.28" *)
  wire [8:1] edgen;
  (* src = "fwpic.v:124.16-124.21" *)
  output int_o;
  wire int_o;
  (* src = "fwpic.v:125.20-125.23" *)
  input [7:0] irq;
  wire [7:0] irq;
  (* src = "fwpic.v:133.30-133.34" *)
  wire [8:1] mask;
  (* src = "fwpic.v:133.18-133.21" *)
  wire [8:1] pol;
  (* src = "fwpic.v:179.10-179.15" *)
  wire ready;
  (* src = "fwpic.v:120.9-120.14" *)
  input reset;
  wire reset;
  assign edgen = 8'h00;
  assign int_o = 1'h0;
  assign mask = 8'hff;
  assign pol = 8'h00;
  assign ready = 1'h1;
endmodule
