/* Generated by Yosys 0.32+74 (git sha1 b739213d9, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "u_rec.v:4.1-163.10" *)
module u_rec(sys_rst_l, sys_clk, uart_dataH, rec_dataH, rec_readyH);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  (* src = "u_rec.v:30.12-30.25" *)
  wire [3:0] bitCell_cntrH;
  (* src = "u_rec.v:32.12-32.21" *)
  wire [7:0] par_dataH;
  (* src = "u_rec.v:29.8-29.16" *)
  wire rec_datH;
  (* src = "u_rec.v:29.18-29.30" *)
  wire rec_datSyncH;
  (* src = "u_rec.v:23.14-23.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "u_rec.v:24.10-24.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "u_rec.v:34.12-34.25" *)
  wire [3:0] recd_bitCntrH;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  (* src = "u_rec.v:19.9-19.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "u_rec.v:18.9-18.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "u_rec.v:21.9-21.19" *)
  input uart_dataH;
  wire uart_dataH;
  iv1v0x05 _071_ (
    .a(recd_bitCntrH[1]),
    .z(_034_)
  );
  iv1v0x05 _072_ (
    .a(state[4]),
    .z(_035_)
  );
  iv1v0x05 _073_ (
    .a(sys_rst_l),
    .z(_036_)
  );
  iv1v0x05 _074_ (
    .a(state[0]),
    .z(_037_)
  );
  nd2av0x05 _075_ (
    .a(rec_datH),
    .b(sys_rst_l),
    .z(_038_)
  );
  nr2v0x05 _076_ (
    .a(bitCell_cntrH[0]),
    .b(bitCell_cntrH[1]),
    .z(_039_)
  );
  nd3abv0x05 _077_ (
    .a(bitCell_cntrH[0]),
    .b(bitCell_cntrH[1]),
    .c(bitCell_cntrH[2]),
    .z(_040_)
  );
  nr2v0x05 _078_ (
    .a(bitCell_cntrH[3]),
    .b(_040_),
    .z(_041_)
  );
  nd2v0x05 _079_ (
    .a(state[2]),
    .b(_041_),
    .z(_042_)
  );
  nr2av0x1 _080_ (
    .a(bitCell_cntrH[1]),
    .b(bitCell_cntrH[0]),
    .z(_043_)
  );
  aoi31v0x05 _081_ (
    .a1(bitCell_cntrH[2]),
    .a2(bitCell_cntrH[3]),
    .a3(_043_),
    .b(_035_),
    .z(_044_)
  );
  oai21v0x05 _082_ (
    .a1(state[1]),
    .a2(_044_),
    .b(sys_rst_l),
    .z(_045_)
  );
  oai21v0x05 _083_ (
    .a1(_038_),
    .a2(_042_),
    .b(_045_),
    .z(_004_)
  );
  oai211v0x05 _084_ (
    .a1(bitCell_cntrH[3]),
    .a2(_040_),
    .b(state[2]),
    .c(sys_rst_l),
    .z(_046_)
  );
  oai21v0x05 _085_ (
    .a1(_037_),
    .a2(_038_),
    .b(_046_),
    .z(_003_)
  );
  aoi21v0x05 _086_ (
    .a1(state[2]),
    .a2(_041_),
    .b(state[0]),
    .z(_047_)
  );
  nd2av0x05 _087_ (
    .a(state[3]),
    .b(sys_rst_l),
    .z(_048_)
  );
  oai21a2bv0x05 _088_ (
    .a1(_047_),
    .a2(rec_datH),
    .b(_048_),
    .z(_002_)
  );
  nr2v0x05 _089_ (
    .a(recd_bitCntrH[1]),
    .b(recd_bitCntrH[0]),
    .z(_049_)
  );
  nr3abv0x05 _090_ (
    .a(recd_bitCntrH[3]),
    .b(_049_),
    .c(recd_bitCntrH[2]),
    .z(_050_)
  );
  nd4v0x05 _091_ (
    .a(bitCell_cntrH[2]),
    .b(bitCell_cntrH[3]),
    .c(sys_rst_l),
    .d(_043_),
    .z(_051_)
  );
  nr2v0x05 _092_ (
    .a(_035_),
    .b(_051_),
    .z(_052_)
  );
  nr2av0x1 _093_ (
    .a(_052_),
    .b(_050_),
    .z(_000_)
  );
  an2v0x05 _094_ (
    .a(_050_),
    .b(_052_),
    .z(_001_)
  );
  nd2av0x05 _095_ (
    .a(uart_dataH),
    .b(sys_rst_l),
    .z(_005_)
  );
  nr3v0x05 _096_ (
    .a(state[4]),
    .b(state[2]),
    .c(state[3]),
    .z(_053_)
  );
  nr4v1x05 _097_ (
    .a(state[4]),
    .b(state[2]),
    .c(state[0]),
    .d(state[3]),
    .z(_054_)
  );
  nd2av0x05 _098_ (
    .a(state[1]),
    .b(rec_datH),
    .z(_055_)
  );
  nr2av0x1 _099_ (
    .a(_053_),
    .b(_055_),
    .z(_056_)
  );
  aoi21bv0x05 _100_ (
    .a1(state[0]),
    .a2(_055_),
    .b(_053_),
    .z(_057_)
  );
  oai21v0x05 _101_ (
    .a1(recd_bitCntrH[0]),
    .a2(_054_),
    .b(sys_rst_l),
    .z(_058_)
  );
  aoi21v0x05 _102_ (
    .a1(recd_bitCntrH[0]),
    .a2(_057_),
    .b(_058_),
    .z(_006_)
  );
  an2v0x05 _103_ (
    .a(recd_bitCntrH[1]),
    .b(recd_bitCntrH[0]),
    .z(_059_)
  );
  nd2av0x05 _104_ (
    .a(_049_),
    .b(_054_),
    .z(_060_)
  );
  oai22v0x05 _105_ (
    .a1(_034_),
    .a2(_057_),
    .b1(_059_),
    .b2(_060_),
    .z(_061_)
  );
  an2v0x05 _106_ (
    .a(sys_rst_l),
    .b(_061_),
    .z(_007_)
  );
  nd3v0x05 _107_ (
    .a(recd_bitCntrH[2]),
    .b(recd_bitCntrH[1]),
    .c(recd_bitCntrH[0]),
    .z(_062_)
  );
  nd2v0x05 _108_ (
    .a(_054_),
    .b(_062_),
    .z(_063_)
  );
  aoi21v0x05 _109_ (
    .a1(_054_),
    .a2(_059_),
    .b(recd_bitCntrH[2]),
    .z(_064_)
  );
  aoi112v0x05 _110_ (
    .a(_036_),
    .b(_064_),
    .c1(_063_),
    .c2(_057_),
    .z(_008_)
  );
  nd3v0x05 _111_ (
    .a(recd_bitCntrH[3]),
    .b(_057_),
    .c(_063_),
    .z(_065_)
  );
  aoi21a2v0x05 _112_ (
    .a1(_054_),
    .a2(_062_),
    .b(recd_bitCntrH[3]),
    .z(_066_)
  );
  nr3abv0x05 _113_ (
    .a(sys_rst_l),
    .b(_065_),
    .c(_066_),
    .z(_009_)
  );
  mxi2v0x05 _114_ (
    .a0(par_dataH[0]),
    .a1(par_dataH[1]),
    .s(_054_),
    .z(_067_)
  );
  nr2v0x05 _115_ (
    .a(_036_),
    .b(_067_),
    .z(_010_)
  );
  mxi2v0x05 _116_ (
    .a0(par_dataH[1]),
    .a1(par_dataH[2]),
    .s(_054_),
    .z(_068_)
  );
  nr2v0x05 _117_ (
    .a(_036_),
    .b(_068_),
    .z(_011_)
  );
  mxi2v0x05 _118_ (
    .a0(par_dataH[2]),
    .a1(par_dataH[3]),
    .s(_054_),
    .z(_069_)
  );
  nr2v0x05 _119_ (
    .a(_036_),
    .b(_069_),
    .z(_012_)
  );
  mxi2v0x05 _120_ (
    .a0(par_dataH[3]),
    .a1(par_dataH[4]),
    .s(_054_),
    .z(_070_)
  );
  nr2v0x05 _121_ (
    .a(_036_),
    .b(_070_),
    .z(_013_)
  );
  mxi2v0x05 _122_ (
    .a0(par_dataH[4]),
    .a1(par_dataH[5]),
    .s(_054_),
    .z(_024_)
  );
  nr2v0x05 _123_ (
    .a(_036_),
    .b(_024_),
    .z(_014_)
  );
  mxi2v0x05 _124_ (
    .a0(par_dataH[5]),
    .a1(par_dataH[6]),
    .s(_054_),
    .z(_025_)
  );
  nr2v0x05 _125_ (
    .a(_036_),
    .b(_025_),
    .z(_015_)
  );
  mxi2v0x05 _126_ (
    .a0(par_dataH[6]),
    .a1(par_dataH[7]),
    .s(_054_),
    .z(_026_)
  );
  nr2v0x05 _127_ (
    .a(_036_),
    .b(_026_),
    .z(_016_)
  );
  mxi2v0x05 _128_ (
    .a0(par_dataH[7]),
    .a1(rec_datH),
    .s(_054_),
    .z(_027_)
  );
  nr2v0x05 _129_ (
    .a(_036_),
    .b(_027_),
    .z(_017_)
  );
  oan21bv0x05 _130_ (
    .a1(state[3]),
    .a2(_056_),
    .b(_036_),
    .z(_018_)
  );
  oai21v0x05 _131_ (
    .a1(bitCell_cntrH[3]),
    .a2(_040_),
    .b(_035_),
    .z(_028_)
  );
  nr3v0x05 _132_ (
    .a(state[0]),
    .b(state[1]),
    .c(_048_),
    .z(_029_)
  );
  oai21a2v0x05 _133_ (
    .a1(_044_),
    .a2(_028_),
    .b(_029_),
    .z(_030_)
  );
  nr2v0x05 _134_ (
    .a(bitCell_cntrH[0]),
    .b(_030_),
    .z(_019_)
  );
  an2v0x05 _135_ (
    .a(bitCell_cntrH[0]),
    .b(bitCell_cntrH[1]),
    .z(_031_)
  );
  nr3v0x05 _136_ (
    .a(_039_),
    .b(_030_),
    .c(_031_),
    .z(_020_)
  );
  xnr2v0x05 _137_ (
    .a(bitCell_cntrH[2]),
    .b(_031_),
    .z(_032_)
  );
  nr2v0x05 _138_ (
    .a(_030_),
    .b(_032_),
    .z(_021_)
  );
  xaoi21v0x05 _139_ (
    .a1(bitCell_cntrH[2]),
    .a2(_031_),
    .b(bitCell_cntrH[3]),
    .z(_033_)
  );
  nr2v0x05 _140_ (
    .a(_030_),
    .b(_033_),
    .z(_022_)
  );
  nd2av0x05 _141_ (
    .a(rec_datSyncH),
    .b(sys_rst_l),
    .z(_023_)
  );
  dfnt1v0x2 _142_ (
    .cp(sys_clk),
    .d(_002_),
    .z(state[0])
  );
  dfnt1v0x2 _143_ (
    .cp(sys_clk),
    .d(_000_),
    .z(state[1])
  );
  dfnt1v0x2 _144_ (
    .cp(sys_clk),
    .d(_003_),
    .z(state[2])
  );
  dfnt1v0x2 _145_ (
    .cp(sys_clk),
    .d(_001_),
    .z(state[3])
  );
  dfnt1v0x2 _146_ (
    .cp(sys_clk),
    .d(_004_),
    .z(state[4])
  );
  (* src = "u_rec.v:46.1-53.6" *)
  dfnt1v0x2 _147_ (
    .cp(sys_clk),
    .d(_005_),
    .z(rec_datSyncH)
  );
  (* src = "u_rec.v:70.1-73.42" *)
  dfnt1v0x2 _148_ (
    .cp(sys_clk),
    .d(_006_),
    .z(recd_bitCntrH[0])
  );
  (* src = "u_rec.v:70.1-73.42" *)
  dfnt1v0x2 _149_ (
    .cp(sys_clk),
    .d(_007_),
    .z(recd_bitCntrH[1])
  );
  (* src = "u_rec.v:70.1-73.42" *)
  dfnt1v0x2 _150_ (
    .cp(sys_clk),
    .d(_008_),
    .z(recd_bitCntrH[2])
  );
  (* src = "u_rec.v:70.1-73.42" *)
  dfnt1v0x2 _151_ (
    .cp(sys_clk),
    .d(_009_),
    .z(recd_bitCntrH[3])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _152_ (
    .cp(sys_clk),
    .d(_010_),
    .z(par_dataH[0])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _153_ (
    .cp(sys_clk),
    .d(_011_),
    .z(par_dataH[1])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _154_ (
    .cp(sys_clk),
    .d(_012_),
    .z(par_dataH[2])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _155_ (
    .cp(sys_clk),
    .d(_013_),
    .z(par_dataH[3])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _156_ (
    .cp(sys_clk),
    .d(_014_),
    .z(par_dataH[4])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _157_ (
    .cp(sys_clk),
    .d(_015_),
    .z(par_dataH[5])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _158_ (
    .cp(sys_clk),
    .d(_016_),
    .z(par_dataH[6])
  );
  (* src = "u_rec.v:62.1-67.6" *)
  dfnt1v0x2 _159_ (
    .cp(sys_clk),
    .d(_017_),
    .z(par_dataH[7])
  );
  (* src = "u_rec.v:156.1-158.35" *)
  dfnt1v0x2 _160_ (
    .cp(sys_clk),
    .d(_018_),
    .z(rec_readyH)
  );
  (* src = "u_rec.v:56.1-59.43" *)
  dfnt1v0x2 _161_ (
    .cp(sys_clk),
    .d(_019_),
    .z(bitCell_cntrH[0])
  );
  (* src = "u_rec.v:56.1-59.43" *)
  dfnt1v0x2 _162_ (
    .cp(sys_clk),
    .d(_020_),
    .z(bitCell_cntrH[1])
  );
  (* src = "u_rec.v:56.1-59.43" *)
  dfnt1v0x2 _163_ (
    .cp(sys_clk),
    .d(_021_),
    .z(bitCell_cntrH[2])
  );
  (* src = "u_rec.v:56.1-59.43" *)
  dfnt1v0x2 _164_ (
    .cp(sys_clk),
    .d(_022_),
    .z(bitCell_cntrH[3])
  );
  (* src = "u_rec.v:46.1-53.6" *)
  dfnt1v0x2 _165_ (
    .cp(sys_clk),
    .d(_023_),
    .z(rec_datH)
  );
  assign rec_dataH = par_dataH;
endmodule

(* src = "u_xmit.v:4.1-200.10" *)
module u_xmit(sys_clk, sys_rst_l, uart_xmitH, xmitH, xmit_dataH, xmit_doneH);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  (* src = "u_xmit.v:40.16-40.28" *)
  wire DataSend_ena;
  (* src = "u_xmit.v:29.12-29.25" *)
  wire [3:0] bitCell_cntrH;
  (* src = "u_xmit.v:32.12-32.21" *)
  wire [3:0] bitCountH;
  (* src = "u_xmit.v:43.16-43.24" *)
  wire [31:0] count_in;
  (* onehot = 32'd1 *)
  wire [3:0] state;
  (* src = "u_xmit.v:16.9-16.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "u_xmit.v:17.9-17.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "u_xmit.v:19.10-19.20" *)
  output uart_xmitH;
  wire uart_xmitH;
  (* src = "u_xmit.v:20.9-20.14" *)
  input xmitH;
  wire xmitH;
  (* src = "u_xmit.v:31.12-31.26" *)
  wire [7:0] xmit_ShiftRegH;
  (* src = "u_xmit.v:21.13-21.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "u_xmit.v:22.10-22.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  iv1v0x05 _103_ (
    .a(count_in[24]),
    .z(_087_)
  );
  iv1v0x05 _104_ (
    .a(count_in[23]),
    .z(_088_)
  );
  iv1v0x05 _105_ (
    .a(count_in[22]),
    .z(_089_)
  );
  iv1v0x05 _106_ (
    .a(count_in[18]),
    .z(_090_)
  );
  iv1v0x05 _107_ (
    .a(count_in[17]),
    .z(_091_)
  );
  iv1v0x05 _108_ (
    .a(count_in[16]),
    .z(_092_)
  );
  iv1v0x05 _109_ (
    .a(count_in[12]),
    .z(_093_)
  );
  iv1v0x05 _110_ (
    .a(count_in[11]),
    .z(_094_)
  );
  iv1v0x05 _111_ (
    .a(count_in[10]),
    .z(_095_)
  );
  iv1v0x05 _112_ (
    .a(DataSend_ena),
    .z(_096_)
  );
  iv1v0x05 _113_ (
    .a(sys_rst_l),
    .z(_097_)
  );
  oai21a2v0x05 _114_ (
    .a1(xmitH),
    .a2(state[0]),
    .b(sys_rst_l),
    .z(_002_)
  );
  aoi21v0x05 _115_ (
    .a1(xmitH),
    .a2(state[0]),
    .b(state[1]),
    .z(_098_)
  );
  nr2v0x05 _116_ (
    .a(_097_),
    .b(_098_),
    .z(_003_)
  );
  oan21bv0x05 _117_ (
    .a1(state[2]),
    .a2(state[0]),
    .b(state[3]),
    .z(uart_xmitH)
  );
  an2v0x05 _118_ (
    .a(sys_rst_l),
    .b(state[2]),
    .z(_000_)
  );
  an2v0x05 _119_ (
    .a(sys_rst_l),
    .b(state[3]),
    .z(_001_)
  );
  nd2v0x05 _120_ (
    .a(count_in[31]),
    .b(count_in[30]),
    .z(_099_)
  );
  an4v0x05 _121_ (
    .a(count_in[3]),
    .b(count_in[2]),
    .c(count_in[1]),
    .d(count_in[0]),
    .z(_100_)
  );
  an4v0x05 _122_ (
    .a(count_in[6]),
    .b(count_in[5]),
    .c(count_in[4]),
    .d(_100_),
    .z(_101_)
  );
  an2v0x05 _123_ (
    .a(count_in[7]),
    .b(_101_),
    .z(_102_)
  );
  nd4v0x05 _124_ (
    .a(count_in[9]),
    .b(count_in[8]),
    .c(count_in[7]),
    .d(_101_),
    .z(_038_)
  );
  nr2v0x05 _125_ (
    .a(_095_),
    .b(_038_),
    .z(_039_)
  );
  nr4v1x05 _126_ (
    .a(_093_),
    .b(_094_),
    .c(_095_),
    .d(_038_),
    .z(_040_)
  );
  nd3v0x05 _127_ (
    .a(count_in[14]),
    .b(count_in[13]),
    .c(_040_),
    .z(_041_)
  );
  nd4v0x05 _128_ (
    .a(count_in[15]),
    .b(count_in[14]),
    .c(count_in[13]),
    .d(_040_),
    .z(_042_)
  );
  nr4v1x05 _129_ (
    .a(_090_),
    .b(_091_),
    .c(_092_),
    .d(_042_),
    .z(_043_)
  );
  an2v0x05 _130_ (
    .a(count_in[19]),
    .b(_043_),
    .z(_044_)
  );
  nd4v0x05 _131_ (
    .a(count_in[21]),
    .b(count_in[20]),
    .c(count_in[19]),
    .d(_043_),
    .z(_045_)
  );
  nr4v1x05 _132_ (
    .a(_087_),
    .b(_088_),
    .c(_089_),
    .d(_045_),
    .z(_046_)
  );
  nd3v0x05 _133_ (
    .a(count_in[26]),
    .b(count_in[25]),
    .c(_046_),
    .z(_047_)
  );
  nd4v0x05 _134_ (
    .a(count_in[27]),
    .b(count_in[26]),
    .c(count_in[25]),
    .d(_046_),
    .z(_048_)
  );
  nr3abv0x05 _135_ (
    .a(count_in[29]),
    .b(count_in[28]),
    .c(_048_),
    .z(_049_)
  );
  nd2av0x05 _136_ (
    .a(_099_),
    .b(_049_),
    .z(_050_)
  );
  xor2v0x05 _137_ (
    .a(count_in[28]),
    .b(_048_),
    .z(_051_)
  );
  aoi21v0x05 _138_ (
    .a1(_050_),
    .a2(_051_),
    .b(_097_),
    .z(_004_)
  );
  aoi21a2v0x05 _139_ (
    .a1(count_in[28]),
    .a2(_048_),
    .b(count_in[29]),
    .z(_052_)
  );
  aoi112v0x05 _140_ (
    .a(_097_),
    .b(_052_),
    .c1(_049_),
    .c2(_099_),
    .z(_005_)
  );
  oai23av0x05 _141_ (
    .a3(count_in[31]),
    .b1(count_in[30]),
    .b2(_049_),
    .z(_053_)
  );
  nr2av0x1 _142_ (
    .a(sys_rst_l),
    .b(_053_),
    .z(_006_)
  );
  aoi21v0x05 _143_ (
    .a1(count_in[30]),
    .a2(_049_),
    .b(count_in[31]),
    .z(_054_)
  );
  nr2av0x1 _144_ (
    .a(sys_rst_l),
    .b(_054_),
    .z(_007_)
  );
  nd3abv0x05 _145_ (
    .a(DataSend_ena),
    .b(xmitH),
    .c(sys_rst_l),
    .z(_055_)
  );
  nr4v1x05 _146_ (
    .a(state[1]),
    .b(state[2]),
    .c(state[3]),
    .d(_055_),
    .z(_008_)
  );
  aoi21bv0x05 _147_ (
    .a1(_096_),
    .a2(_050_),
    .b(sys_rst_l),
    .z(_009_)
  );
  aoi21bv0x05 _148_ (
    .a1(count_in[0]),
    .a2(_050_),
    .b(sys_rst_l),
    .z(_010_)
  );
  xnr2v0x05 _149_ (
    .a(count_in[1]),
    .b(count_in[0]),
    .z(_056_)
  );
  aoi21bv0x05 _150_ (
    .a1(_050_),
    .a2(_056_),
    .b(sys_rst_l),
    .z(_011_)
  );
  xaoi21v0x05 _151_ (
    .a1(count_in[1]),
    .a2(count_in[0]),
    .b(count_in[2]),
    .z(_057_)
  );
  aoi21bv0x05 _152_ (
    .a1(_050_),
    .a2(_057_),
    .b(sys_rst_l),
    .z(_012_)
  );
  aoi31v0x05 _153_ (
    .a1(count_in[2]),
    .a2(count_in[1]),
    .a3(count_in[0]),
    .b(count_in[3]),
    .z(_058_)
  );
  or2v0x05 _154_ (
    .a(_100_),
    .b(_058_),
    .z(_059_)
  );
  aoi21bv0x05 _155_ (
    .a1(_050_),
    .a2(_059_),
    .b(sys_rst_l),
    .z(_013_)
  );
  xnr2v0x05 _156_ (
    .a(count_in[4]),
    .b(_100_),
    .z(_060_)
  );
  aoi21bv0x05 _157_ (
    .a1(_050_),
    .a2(_060_),
    .b(sys_rst_l),
    .z(_014_)
  );
  xaoi21v0x05 _158_ (
    .a1(count_in[4]),
    .a2(_100_),
    .b(count_in[5]),
    .z(_061_)
  );
  aoi21bv0x05 _159_ (
    .a1(_050_),
    .a2(_061_),
    .b(sys_rst_l),
    .z(_015_)
  );
  aoi31v0x05 _160_ (
    .a1(count_in[5]),
    .a2(count_in[4]),
    .a3(_100_),
    .b(count_in[6]),
    .z(_062_)
  );
  or2v0x05 _161_ (
    .a(_101_),
    .b(_062_),
    .z(_063_)
  );
  aoi21bv0x05 _162_ (
    .a1(_050_),
    .a2(_063_),
    .b(sys_rst_l),
    .z(_016_)
  );
  xnr2v0x05 _163_ (
    .a(count_in[7]),
    .b(_101_),
    .z(_064_)
  );
  aoi21bv0x05 _164_ (
    .a1(_050_),
    .a2(_064_),
    .b(sys_rst_l),
    .z(_017_)
  );
  xnr2v0x05 _165_ (
    .a(count_in[8]),
    .b(_102_),
    .z(_065_)
  );
  aoi21bv0x05 _166_ (
    .a1(_050_),
    .a2(_065_),
    .b(sys_rst_l),
    .z(_018_)
  );
  xaoi21v0x05 _167_ (
    .a1(count_in[8]),
    .a2(_102_),
    .b(count_in[9]),
    .z(_066_)
  );
  aoi21bv0x05 _168_ (
    .a1(_050_),
    .a2(_066_),
    .b(sys_rst_l),
    .z(_019_)
  );
  xnr2v0x05 _169_ (
    .a(_095_),
    .b(_038_),
    .z(_067_)
  );
  aoi21bv0x05 _170_ (
    .a1(_050_),
    .a2(_067_),
    .b(sys_rst_l),
    .z(_020_)
  );
  xnr2v0x05 _171_ (
    .a(count_in[11]),
    .b(_039_),
    .z(_068_)
  );
  aoi21bv0x05 _172_ (
    .a1(_050_),
    .a2(_068_),
    .b(sys_rst_l),
    .z(_021_)
  );
  xaoi21v0x05 _173_ (
    .a1(count_in[11]),
    .a2(_039_),
    .b(count_in[12]),
    .z(_069_)
  );
  aoi21bv0x05 _174_ (
    .a1(_050_),
    .a2(_069_),
    .b(sys_rst_l),
    .z(_022_)
  );
  xnr2v0x05 _175_ (
    .a(count_in[13]),
    .b(_040_),
    .z(_070_)
  );
  aoi21bv0x05 _176_ (
    .a1(_050_),
    .a2(_070_),
    .b(sys_rst_l),
    .z(_023_)
  );
  xaoi21v0x05 _177_ (
    .a1(count_in[13]),
    .a2(_040_),
    .b(count_in[14]),
    .z(_071_)
  );
  aoi21bv0x05 _178_ (
    .a1(_050_),
    .a2(_071_),
    .b(sys_rst_l),
    .z(_024_)
  );
  xor2v0x05 _179_ (
    .a(count_in[15]),
    .b(_041_),
    .z(_072_)
  );
  aoi21bv0x05 _180_ (
    .a1(_050_),
    .a2(_072_),
    .b(sys_rst_l),
    .z(_025_)
  );
  xnr2v0x05 _181_ (
    .a(_092_),
    .b(_042_),
    .z(_073_)
  );
  aoi21bv0x05 _182_ (
    .a1(_050_),
    .a2(_073_),
    .b(sys_rst_l),
    .z(_026_)
  );
  xooi21v0x05 _183_ (
    .a1(_092_),
    .a2(_042_),
    .b(_091_),
    .z(_074_)
  );
  aoi21bv0x05 _184_ (
    .a1(_050_),
    .a2(_074_),
    .b(sys_rst_l),
    .z(_027_)
  );
  oai31v0x05 _185_ (
    .a1(_091_),
    .a2(_092_),
    .a3(_042_),
    .b(_090_),
    .z(_075_)
  );
  nd2av0x05 _186_ (
    .a(_043_),
    .b(_075_),
    .z(_076_)
  );
  aoi21bv0x05 _187_ (
    .a1(_050_),
    .a2(_076_),
    .b(sys_rst_l),
    .z(_028_)
  );
  xnr2v0x05 _188_ (
    .a(count_in[19]),
    .b(_043_),
    .z(_077_)
  );
  aoi21bv0x05 _189_ (
    .a1(_050_),
    .a2(_077_),
    .b(sys_rst_l),
    .z(_029_)
  );
  xnr2v0x05 _190_ (
    .a(count_in[20]),
    .b(_044_),
    .z(_078_)
  );
  aoi21bv0x05 _191_ (
    .a1(_050_),
    .a2(_078_),
    .b(sys_rst_l),
    .z(_030_)
  );
  xaoi21v0x05 _192_ (
    .a1(count_in[20]),
    .a2(_044_),
    .b(count_in[21]),
    .z(_079_)
  );
  aoi21bv0x05 _193_ (
    .a1(_050_),
    .a2(_079_),
    .b(sys_rst_l),
    .z(_031_)
  );
  xnr2v0x05 _194_ (
    .a(_089_),
    .b(_045_),
    .z(_080_)
  );
  aoi21bv0x05 _195_ (
    .a1(_050_),
    .a2(_080_),
    .b(sys_rst_l),
    .z(_032_)
  );
  xooi21v0x05 _196_ (
    .a1(_089_),
    .a2(_045_),
    .b(_088_),
    .z(_081_)
  );
  aoi21bv0x05 _197_ (
    .a1(_050_),
    .a2(_081_),
    .b(sys_rst_l),
    .z(_033_)
  );
  oai31v0x05 _198_ (
    .a1(_088_),
    .a2(_089_),
    .a3(_045_),
    .b(_087_),
    .z(_082_)
  );
  nd2av0x05 _199_ (
    .a(_046_),
    .b(_082_),
    .z(_083_)
  );
  aoi21bv0x05 _200_ (
    .a1(_050_),
    .a2(_083_),
    .b(sys_rst_l),
    .z(_034_)
  );
  xnr2v0x05 _201_ (
    .a(count_in[25]),
    .b(_046_),
    .z(_084_)
  );
  aoi21bv0x05 _202_ (
    .a1(_050_),
    .a2(_084_),
    .b(sys_rst_l),
    .z(_035_)
  );
  xaoi21v0x05 _203_ (
    .a1(count_in[25]),
    .a2(_046_),
    .b(count_in[26]),
    .z(_085_)
  );
  aoi21bv0x05 _204_ (
    .a1(_050_),
    .a2(_085_),
    .b(sys_rst_l),
    .z(_036_)
  );
  xor2v0x05 _205_ (
    .a(count_in[27]),
    .b(_047_),
    .z(_086_)
  );
  aoi21bv0x05 _206_ (
    .a1(_050_),
    .a2(_086_),
    .b(sys_rst_l),
    .z(_037_)
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _207_ (
    .cp(sys_clk),
    .d(_004_),
    .z(count_in[28])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _208_ (
    .cp(sys_clk),
    .d(_005_),
    .z(count_in[29])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _209_ (
    .cp(sys_clk),
    .d(_006_),
    .z(count_in[30])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _210_ (
    .cp(sys_clk),
    .d(_007_),
    .z(count_in[31])
  );
  dfnt1v0x2 _211_ (
    .cp(sys_clk),
    .d(_002_),
    .z(state[0])
  );
  dfnt1v0x2 _212_ (
    .cp(sys_clk),
    .d(_003_),
    .z(state[1])
  );
  dfnt1v0x2 _213_ (
    .cp(sys_clk),
    .d(_000_),
    .z(state[2])
  );
  dfnt1v0x2 _214_ (
    .cp(sys_clk),
    .d(_001_),
    .z(state[3])
  );
  (* src = "u_xmit.v:192.1-197.31" *)
  dfnt1v0x2 _215_ (
    .cp(sys_clk),
    .d(_008_),
    .z(xmit_doneH)
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _216_ (
    .cp(sys_clk),
    .d(_009_),
    .z(DataSend_ena)
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _217_ (
    .cp(sys_clk),
    .d(_010_),
    .z(count_in[0])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _218_ (
    .cp(sys_clk),
    .d(_011_),
    .z(count_in[1])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _219_ (
    .cp(sys_clk),
    .d(_012_),
    .z(count_in[2])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _220_ (
    .cp(sys_clk),
    .d(_013_),
    .z(count_in[3])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _221_ (
    .cp(sys_clk),
    .d(_014_),
    .z(count_in[4])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _222_ (
    .cp(sys_clk),
    .d(_015_),
    .z(count_in[5])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _223_ (
    .cp(sys_clk),
    .d(_016_),
    .z(count_in[6])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _224_ (
    .cp(sys_clk),
    .d(_017_),
    .z(count_in[7])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _225_ (
    .cp(sys_clk),
    .d(_018_),
    .z(count_in[8])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _226_ (
    .cp(sys_clk),
    .d(_019_),
    .z(count_in[9])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _227_ (
    .cp(sys_clk),
    .d(_020_),
    .z(count_in[10])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _228_ (
    .cp(sys_clk),
    .d(_021_),
    .z(count_in[11])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _229_ (
    .cp(sys_clk),
    .d(_022_),
    .z(count_in[12])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _230_ (
    .cp(sys_clk),
    .d(_023_),
    .z(count_in[13])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _231_ (
    .cp(sys_clk),
    .d(_024_),
    .z(count_in[14])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _232_ (
    .cp(sys_clk),
    .d(_025_),
    .z(count_in[15])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _233_ (
    .cp(sys_clk),
    .d(_026_),
    .z(count_in[16])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _234_ (
    .cp(sys_clk),
    .d(_027_),
    .z(count_in[17])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _235_ (
    .cp(sys_clk),
    .d(_028_),
    .z(count_in[18])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _236_ (
    .cp(sys_clk),
    .d(_029_),
    .z(count_in[19])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _237_ (
    .cp(sys_clk),
    .d(_030_),
    .z(count_in[20])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _238_ (
    .cp(sys_clk),
    .d(_031_),
    .z(count_in[21])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _239_ (
    .cp(sys_clk),
    .d(_032_),
    .z(count_in[22])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _240_ (
    .cp(sys_clk),
    .d(_033_),
    .z(count_in[23])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _241_ (
    .cp(sys_clk),
    .d(_034_),
    .z(count_in[24])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _242_ (
    .cp(sys_clk),
    .d(_035_),
    .z(count_in[25])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _243_ (
    .cp(sys_clk),
    .d(_036_),
    .z(count_in[26])
  );
  (* src = "u_xmit.v:181.3-189.8" *)
  dfnt1v0x2 _244_ (
    .cp(sys_clk),
    .d(_037_),
    .z(count_in[27])
  );
  assign bitCell_cntrH = 4'h0;
  assign bitCountH = 4'h0;
  assign xmit_ShiftRegH = 8'h00;
endmodule

(* src = "uart.v:3.1-78.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "uart.v:29.14-29.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "uart.v:34.17-34.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "uart.v:33.17-33.31" *)
  wire [7:0] rec_dataH_temp;
  (* src = "uart.v:30.10-30.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "uart.v:19.9-19.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "uart.v:20.9-20.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "uart.v:28.9-28.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "uart.v:23.10-23.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "uart.v:24.9-24.14" *)
  input xmitH;
  wire xmitH;
  (* src = "uart.v:25.13-25.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "uart.v:26.10-26.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  an2v0x05 _16_ (
    .a(rec_dataH_rec[0]),
    .b(sys_rst_l),
    .z(_00_)
  );
  an2v0x05 _17_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[1]),
    .z(_01_)
  );
  an2v0x05 _18_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[2]),
    .z(_02_)
  );
  an2v0x05 _19_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[3]),
    .z(_03_)
  );
  an2v0x05 _20_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[4]),
    .z(_04_)
  );
  an2v0x05 _21_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[5]),
    .z(_05_)
  );
  an2v0x05 _22_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[6]),
    .z(_06_)
  );
  an2v0x05 _23_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[7]),
    .z(_07_)
  );
  an2v0x05 _24_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[0]),
    .z(_08_)
  );
  an2v0x05 _25_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[1]),
    .z(_09_)
  );
  an2v0x05 _26_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[2]),
    .z(_10_)
  );
  an2v0x05 _27_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[3]),
    .z(_11_)
  );
  an2v0x05 _28_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[4]),
    .z(_12_)
  );
  an2v0x05 _29_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[5]),
    .z(_13_)
  );
  an2v0x05 _30_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[6]),
    .z(_14_)
  );
  an2v0x05 _31_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[7]),
    .z(_15_)
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _32_ (
    .cp(rec_readyH),
    .d(_00_),
    .z(rec_dataH_temp[0])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _33_ (
    .cp(rec_readyH),
    .d(_01_),
    .z(rec_dataH_temp[1])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _34_ (
    .cp(rec_readyH),
    .d(_02_),
    .z(rec_dataH_temp[2])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _35_ (
    .cp(rec_readyH),
    .d(_03_),
    .z(rec_dataH_temp[3])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _36_ (
    .cp(rec_readyH),
    .d(_04_),
    .z(rec_dataH_temp[4])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _37_ (
    .cp(rec_readyH),
    .d(_05_),
    .z(rec_dataH_temp[5])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _38_ (
    .cp(rec_readyH),
    .d(_06_),
    .z(rec_dataH_temp[6])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _39_ (
    .cp(rec_readyH),
    .d(_07_),
    .z(rec_dataH_temp[7])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _40_ (
    .cp(sys_clk),
    .d(_08_),
    .z(rec_dataH[0])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _41_ (
    .cp(sys_clk),
    .d(_09_),
    .z(rec_dataH[1])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _42_ (
    .cp(sys_clk),
    .d(_10_),
    .z(rec_dataH[2])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _43_ (
    .cp(sys_clk),
    .d(_11_),
    .z(rec_dataH[3])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _44_ (
    .cp(sys_clk),
    .d(_12_),
    .z(rec_dataH[4])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _45_ (
    .cp(sys_clk),
    .d(_13_),
    .z(rec_dataH[5])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _46_ (
    .cp(sys_clk),
    .d(_14_),
    .z(rec_dataH[6])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _47_ (
    .cp(sys_clk),
    .d(_15_),
    .z(rec_dataH[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "uart.v:48.7-57.6" *)
  u_rec iRECEIVER (
    .rec_dataH(rec_dataH_rec),
    .rec_readyH(rec_readyH),
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_dataH(uart_REC_dataH)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "uart.v:39.9-46.5" *)
  u_xmit iXMIT (
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_xmitH(uart_XMIT_dataH),
    .xmitH(xmitH),
    .xmit_dataH(xmit_dataH),
    .xmit_doneH(xmit_doneH)
  );
endmodule
