/* Generated by Yosys 0.32+74 (git sha1 b739213d9, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "u_rec.v:4.1-165.10" *)
module u_rec(sys_rst_l, sys_clk, uart_dataH, rec_dataH, rec_readyH);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  (* src = "u_rec.v:31.12-31.25" *)
  wire [3:0] bitCell_cntrH;
  (* src = "u_rec.v:33.12-33.21" *)
  wire [7:0] par_dataH;
  (* src = "u_rec.v:30.8-30.16" *)
  wire rec_datH;
  (* src = "u_rec.v:30.18-30.30" *)
  wire rec_datSyncH;
  (* src = "u_rec.v:24.14-24.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "u_rec.v:25.10-25.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "u_rec.v:35.12-35.25" *)
  wire [3:0] recd_bitCntrH;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  (* src = "u_rec.v:20.9-20.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "u_rec.v:19.9-19.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "u_rec.v:22.9-22.19" *)
  input uart_dataH;
  wire uart_dataH;
  iv1v0x05 _071_ (
    .a(rec_datH),
    .z(_034_)
  );
  iv1v0x05 _072_ (
    .a(recd_bitCntrH[1]),
    .z(_035_)
  );
  iv1v0x05 _073_ (
    .a(state[0]),
    .z(_036_)
  );
  iv1v0x05 _074_ (
    .a(sys_rst_l),
    .z(_037_)
  );
  nr2v0x05 _075_ (
    .a(_037_),
    .b(state[3]),
    .z(_038_)
  );
  nr2v0x05 _076_ (
    .a(bitCell_cntrH[0]),
    .b(bitCell_cntrH[1]),
    .z(_039_)
  );
  nr3v0x05 _077_ (
    .a(bitCell_cntrH[0]),
    .b(bitCell_cntrH[1]),
    .c(bitCell_cntrH[3]),
    .z(_040_)
  );
  an2v0x05 _078_ (
    .a(bitCell_cntrH[2]),
    .b(_040_),
    .z(_041_)
  );
  nd2v0x05 _079_ (
    .a(state[2]),
    .b(_041_),
    .z(_042_)
  );
  aoi21v0x05 _080_ (
    .a1(state[2]),
    .a2(_041_),
    .b(state[0]),
    .z(_043_)
  );
  oai21v0x05 _081_ (
    .a1(_034_),
    .a2(_043_),
    .b(_038_),
    .z(_002_)
  );
  nd2v0x05 _082_ (
    .a(_034_),
    .b(sys_rst_l),
    .z(_044_)
  );
  nr2av0x1 _083_ (
    .a(bitCell_cntrH[1]),
    .b(bitCell_cntrH[0]),
    .z(_045_)
  );
  an2v0x05 _084_ (
    .a(bitCell_cntrH[3]),
    .b(bitCell_cntrH[2]),
    .z(_046_)
  );
  aoi21bv0x05 _085_ (
    .a1(_045_),
    .a2(_046_),
    .b(state[4]),
    .z(_047_)
  );
  oai21v0x05 _086_ (
    .a1(state[1]),
    .a2(_047_),
    .b(sys_rst_l),
    .z(_048_)
  );
  oai21v0x05 _087_ (
    .a1(_042_),
    .a2(_044_),
    .b(_048_),
    .z(_004_)
  );
  nd2v0x05 _088_ (
    .a(sys_rst_l),
    .b(state[2]),
    .z(_049_)
  );
  oai22v0x05 _089_ (
    .a1(_036_),
    .a2(_044_),
    .b1(_049_),
    .b2(_041_),
    .z(_003_)
  );
  nr2v0x05 _090_ (
    .a(recd_bitCntrH[1]),
    .b(recd_bitCntrH[0]),
    .z(_050_)
  );
  nr3abv0x05 _091_ (
    .a(recd_bitCntrH[3]),
    .b(_050_),
    .c(recd_bitCntrH[2]),
    .z(_051_)
  );
  nd4v0x05 _092_ (
    .a(sys_rst_l),
    .b(state[4]),
    .c(_045_),
    .d(_046_),
    .z(_052_)
  );
  nr2av0x1 _093_ (
    .a(_051_),
    .b(_052_),
    .z(_001_)
  );
  nr2v0x05 _094_ (
    .a(_051_),
    .b(_052_),
    .z(_000_)
  );
  nr3v0x05 _095_ (
    .a(state[2]),
    .b(state[3]),
    .c(state[4]),
    .z(_053_)
  );
  nr4v1x05 _096_ (
    .a(state[0]),
    .b(state[2]),
    .c(state[3]),
    .d(state[4]),
    .z(_054_)
  );
  nd2av0x05 _097_ (
    .a(state[1]),
    .b(rec_datH),
    .z(_055_)
  );
  nr2av0x1 _098_ (
    .a(_053_),
    .b(_055_),
    .z(_056_)
  );
  aoi21bv0x05 _099_ (
    .a1(state[0]),
    .a2(_055_),
    .b(_053_),
    .z(_057_)
  );
  oai21v0x05 _100_ (
    .a1(recd_bitCntrH[0]),
    .a2(_054_),
    .b(sys_rst_l),
    .z(_058_)
  );
  aoi21v0x05 _101_ (
    .a1(recd_bitCntrH[0]),
    .a2(_057_),
    .b(_058_),
    .z(_005_)
  );
  an2v0x05 _102_ (
    .a(recd_bitCntrH[1]),
    .b(recd_bitCntrH[0]),
    .z(_059_)
  );
  nd2av0x05 _103_ (
    .a(_050_),
    .b(_054_),
    .z(_060_)
  );
  oai22v0x05 _104_ (
    .a1(_035_),
    .a2(_057_),
    .b1(_059_),
    .b2(_060_),
    .z(_061_)
  );
  an2v0x05 _105_ (
    .a(sys_rst_l),
    .b(_061_),
    .z(_006_)
  );
  nd3v0x05 _106_ (
    .a(recd_bitCntrH[2]),
    .b(recd_bitCntrH[1]),
    .c(recd_bitCntrH[0]),
    .z(_062_)
  );
  nd2v0x05 _107_ (
    .a(_054_),
    .b(_062_),
    .z(_063_)
  );
  aoi21v0x05 _108_ (
    .a1(_054_),
    .a2(_059_),
    .b(recd_bitCntrH[2]),
    .z(_064_)
  );
  aoi112v0x05 _109_ (
    .a(_037_),
    .b(_064_),
    .c1(_063_),
    .c2(_057_),
    .z(_007_)
  );
  nd3v0x05 _110_ (
    .a(recd_bitCntrH[3]),
    .b(_057_),
    .c(_063_),
    .z(_065_)
  );
  aoi21a2v0x05 _111_ (
    .a1(_054_),
    .a2(_062_),
    .b(recd_bitCntrH[3]),
    .z(_066_)
  );
  nr3abv0x05 _112_ (
    .a(sys_rst_l),
    .b(_065_),
    .c(_066_),
    .z(_008_)
  );
  mxi2v0x05 _113_ (
    .a0(par_dataH[0]),
    .a1(par_dataH[1]),
    .s(_054_),
    .z(_067_)
  );
  nr2v0x05 _114_ (
    .a(_037_),
    .b(_067_),
    .z(_009_)
  );
  mxi2v0x05 _115_ (
    .a0(par_dataH[1]),
    .a1(par_dataH[2]),
    .s(_054_),
    .z(_068_)
  );
  nr2v0x05 _116_ (
    .a(_037_),
    .b(_068_),
    .z(_010_)
  );
  mxi2v0x05 _117_ (
    .a0(par_dataH[2]),
    .a1(par_dataH[3]),
    .s(_054_),
    .z(_069_)
  );
  nr2v0x05 _118_ (
    .a(_037_),
    .b(_069_),
    .z(_011_)
  );
  mxi2v0x05 _119_ (
    .a0(par_dataH[3]),
    .a1(par_dataH[4]),
    .s(_054_),
    .z(_070_)
  );
  nr2v0x05 _120_ (
    .a(_037_),
    .b(_070_),
    .z(_012_)
  );
  mxi2v0x05 _121_ (
    .a0(par_dataH[4]),
    .a1(par_dataH[5]),
    .s(_054_),
    .z(_024_)
  );
  nr2v0x05 _122_ (
    .a(_037_),
    .b(_024_),
    .z(_013_)
  );
  mxi2v0x05 _123_ (
    .a0(par_dataH[5]),
    .a1(par_dataH[6]),
    .s(_054_),
    .z(_025_)
  );
  nr2v0x05 _124_ (
    .a(_037_),
    .b(_025_),
    .z(_014_)
  );
  mxi2v0x05 _125_ (
    .a0(par_dataH[6]),
    .a1(par_dataH[7]),
    .s(_054_),
    .z(_026_)
  );
  nr2v0x05 _126_ (
    .a(_037_),
    .b(_026_),
    .z(_015_)
  );
  mxi2v0x05 _127_ (
    .a0(par_dataH[7]),
    .a1(rec_datH),
    .s(_054_),
    .z(_027_)
  );
  nr2v0x05 _128_ (
    .a(_037_),
    .b(_027_),
    .z(_016_)
  );
  oan21bv0x05 _129_ (
    .a1(state[3]),
    .a2(_056_),
    .b(_037_),
    .z(_017_)
  );
  aoi21v0x05 _130_ (
    .a1(bitCell_cntrH[2]),
    .a2(_040_),
    .b(state[4]),
    .z(_028_)
  );
  nr2v0x05 _131_ (
    .a(state[0]),
    .b(state[1]),
    .z(_029_)
  );
  oai211v0x05 _132_ (
    .a1(_047_),
    .a2(_028_),
    .b(_029_),
    .c(_038_),
    .z(_030_)
  );
  nr2v0x05 _133_ (
    .a(bitCell_cntrH[0]),
    .b(_030_),
    .z(_018_)
  );
  an2v0x05 _134_ (
    .a(bitCell_cntrH[0]),
    .b(bitCell_cntrH[1]),
    .z(_031_)
  );
  nr3v0x05 _135_ (
    .a(_039_),
    .b(_030_),
    .c(_031_),
    .z(_019_)
  );
  xnr2v0x05 _136_ (
    .a(bitCell_cntrH[2]),
    .b(_031_),
    .z(_032_)
  );
  nr2v0x05 _137_ (
    .a(_030_),
    .b(_032_),
    .z(_020_)
  );
  xaoi21v0x05 _138_ (
    .a1(bitCell_cntrH[2]),
    .a2(_031_),
    .b(bitCell_cntrH[3]),
    .z(_033_)
  );
  nr2v0x05 _139_ (
    .a(_030_),
    .b(_033_),
    .z(_021_)
  );
  nd2av0x05 _140_ (
    .a(rec_datSyncH),
    .b(sys_rst_l),
    .z(_022_)
  );
  nd2av0x05 _141_ (
    .a(uart_dataH),
    .b(sys_rst_l),
    .z(_023_)
  );
  dfnt1v0x2 _142_ (
    .cp(sys_clk),
    .d(_002_),
    .z(state[0])
  );
  dfnt1v0x2 _143_ (
    .cp(sys_clk),
    .d(_000_),
    .z(state[1])
  );
  dfnt1v0x2 _144_ (
    .cp(sys_clk),
    .d(_003_),
    .z(state[2])
  );
  dfnt1v0x2 _145_ (
    .cp(sys_clk),
    .d(_001_),
    .z(state[3])
  );
  dfnt1v0x2 _146_ (
    .cp(sys_clk),
    .d(_004_),
    .z(state[4])
  );
  (* src = "u_rec.v:71.1-74.42" *)
  dfnt1v0x2 _147_ (
    .cp(sys_clk),
    .d(_005_),
    .z(recd_bitCntrH[0])
  );
  (* src = "u_rec.v:71.1-74.42" *)
  dfnt1v0x2 _148_ (
    .cp(sys_clk),
    .d(_006_),
    .z(recd_bitCntrH[1])
  );
  (* src = "u_rec.v:71.1-74.42" *)
  dfnt1v0x2 _149_ (
    .cp(sys_clk),
    .d(_007_),
    .z(recd_bitCntrH[2])
  );
  (* src = "u_rec.v:71.1-74.42" *)
  dfnt1v0x2 _150_ (
    .cp(sys_clk),
    .d(_008_),
    .z(recd_bitCntrH[3])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _151_ (
    .cp(sys_clk),
    .d(_009_),
    .z(par_dataH[0])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _152_ (
    .cp(sys_clk),
    .d(_010_),
    .z(par_dataH[1])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _153_ (
    .cp(sys_clk),
    .d(_011_),
    .z(par_dataH[2])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _154_ (
    .cp(sys_clk),
    .d(_012_),
    .z(par_dataH[3])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _155_ (
    .cp(sys_clk),
    .d(_013_),
    .z(par_dataH[4])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _156_ (
    .cp(sys_clk),
    .d(_014_),
    .z(par_dataH[5])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _157_ (
    .cp(sys_clk),
    .d(_015_),
    .z(par_dataH[6])
  );
  (* src = "u_rec.v:63.1-68.6" *)
  dfnt1v0x2 _158_ (
    .cp(sys_clk),
    .d(_016_),
    .z(par_dataH[7])
  );
  (* src = "u_rec.v:158.1-160.35" *)
  dfnt1v0x2 _159_ (
    .cp(sys_clk),
    .d(_017_),
    .z(rec_readyH)
  );
  (* src = "u_rec.v:57.1-60.43" *)
  dfnt1v0x2 _160_ (
    .cp(sys_clk),
    .d(_018_),
    .z(bitCell_cntrH[0])
  );
  (* src = "u_rec.v:57.1-60.43" *)
  dfnt1v0x2 _161_ (
    .cp(sys_clk),
    .d(_019_),
    .z(bitCell_cntrH[1])
  );
  (* src = "u_rec.v:57.1-60.43" *)
  dfnt1v0x2 _162_ (
    .cp(sys_clk),
    .d(_020_),
    .z(bitCell_cntrH[2])
  );
  (* src = "u_rec.v:57.1-60.43" *)
  dfnt1v0x2 _163_ (
    .cp(sys_clk),
    .d(_021_),
    .z(bitCell_cntrH[3])
  );
  (* src = "u_rec.v:47.1-54.6" *)
  dfnt1v0x2 _164_ (
    .cp(sys_clk),
    .d(_022_),
    .z(rec_datH)
  );
  (* src = "u_rec.v:47.1-54.6" *)
  dfnt1v0x2 _165_ (
    .cp(sys_clk),
    .d(_023_),
    .z(rec_datSyncH)
  );
  assign rec_dataH = par_dataH;
endmodule

(* src = "u_xmit.v:4.1-177.10" *)
module u_xmit(sys_clk, sys_rst_l, uart_xmitH, xmitH, xmit_dataH, xmit_doneH);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "u_xmit.v:28.12-28.25" *)
  wire [3:0] bitCell_cntrH;
  (* src = "u_xmit.v:31.12-31.21" *)
  wire [3:0] bitCountH;
  (* onehot = 32'd1 *)
  wire [3:0] state;
  (* src = "u_xmit.v:15.9-15.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "u_xmit.v:16.9-16.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "u_xmit.v:18.10-18.20" *)
  output uart_xmitH;
  wire uart_xmitH;
  (* src = "u_xmit.v:19.9-19.14" *)
  input xmitH;
  wire xmitH;
  (* src = "u_xmit.v:30.12-30.26" *)
  wire [7:0] xmit_ShiftRegH;
  (* src = "u_xmit.v:20.13-20.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "u_xmit.v:21.10-21.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  aoi21v0x05 _07_ (
    .a1(xmitH),
    .a2(state[0]),
    .b(state[1]),
    .z(_05_)
  );
  nr2av0x1 _08_ (
    .a(sys_rst_l),
    .b(_05_),
    .z(_03_)
  );
  oai21a2v0x05 _09_ (
    .a1(xmitH),
    .a2(state[0]),
    .b(sys_rst_l),
    .z(_02_)
  );
  or2v0x05 _10_ (
    .a(state[0]),
    .b(state[2]),
    .z(uart_xmitH)
  );
  an2v0x05 _11_ (
    .a(sys_rst_l),
    .b(state[2]),
    .z(_00_)
  );
  an2v0x05 _12_ (
    .a(sys_rst_l),
    .b(state[3]),
    .z(_01_)
  );
  nd3abv0x05 _13_ (
    .a(xmitH),
    .b(state[3]),
    .c(sys_rst_l),
    .z(_06_)
  );
  nr3v0x05 _14_ (
    .a(state[1]),
    .b(state[2]),
    .c(_06_),
    .z(_04_)
  );
  dfnt1v0x2 _15_ (
    .cp(sys_clk),
    .d(_02_),
    .z(state[0])
  );
  dfnt1v0x2 _16_ (
    .cp(sys_clk),
    .d(_03_),
    .z(state[1])
  );
  dfnt1v0x2 _17_ (
    .cp(sys_clk),
    .d(_00_),
    .z(state[2])
  );
  dfnt1v0x2 _18_ (
    .cp(sys_clk),
    .d(_01_),
    .z(state[3])
  );
  (* src = "u_xmit.v:172.1-174.35" *)
  dfnt1v0x2 _19_ (
    .cp(sys_clk),
    .d(_04_),
    .z(xmit_doneH)
  );
  assign bitCell_cntrH = 4'h0;
  assign bitCountH = 4'h0;
  assign xmit_ShiftRegH = 8'h00;
endmodule

(* src = "uart.v:3.1-98.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "uart.v:30.17-30.21" *)
  wire cntr;
  (* src = "uart.v:25.14-25.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "uart.v:31.17-31.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "uart.v:29.17-29.31" *)
  wire [7:0] rec_dataH_temp;
  (* src = "uart.v:26.10-26.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "uart.v:17.9-17.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "uart.v:18.9-18.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "uart.v:24.9-24.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "uart.v:19.10-19.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "uart.v:20.9-20.14" *)
  input xmitH;
  wire xmitH;
  (* src = "uart.v:21.13-21.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "uart.v:22.10-22.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  an2v0x05 _16_ (
    .a(rec_dataH_rec[5]),
    .b(sys_rst_l),
    .z(_00_)
  );
  an2v0x05 _17_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[7]),
    .z(_01_)
  );
  an2v0x05 _18_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[0]),
    .z(_02_)
  );
  an2v0x05 _19_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[1]),
    .z(_03_)
  );
  an2v0x05 _20_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[2]),
    .z(_04_)
  );
  an2v0x05 _21_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[3]),
    .z(_05_)
  );
  an2v0x05 _22_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[4]),
    .z(_06_)
  );
  an2v0x05 _23_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[6]),
    .z(_07_)
  );
  an2v0x05 _24_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[0]),
    .z(_08_)
  );
  an2v0x05 _25_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[1]),
    .z(_09_)
  );
  an2v0x05 _26_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[2]),
    .z(_10_)
  );
  an2v0x05 _27_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[3]),
    .z(_11_)
  );
  an2v0x05 _28_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[4]),
    .z(_12_)
  );
  an2v0x05 _29_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[5]),
    .z(_13_)
  );
  an2v0x05 _30_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[6]),
    .z(_14_)
  );
  an2v0x05 _31_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[7]),
    .z(_15_)
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _32_ (
    .cp(rec_readyH),
    .d(_00_),
    .z(rec_dataH_temp[5])
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _33_ (
    .cp(rec_readyH),
    .d(_01_),
    .z(rec_dataH_temp[7])
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _34_ (
    .cp(rec_readyH),
    .d(_02_),
    .z(rec_dataH_temp[0])
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _35_ (
    .cp(rec_readyH),
    .d(_03_),
    .z(rec_dataH_temp[1])
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _36_ (
    .cp(rec_readyH),
    .d(_04_),
    .z(rec_dataH_temp[2])
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _37_ (
    .cp(rec_readyH),
    .d(_05_),
    .z(rec_dataH_temp[3])
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _38_ (
    .cp(rec_readyH),
    .d(_06_),
    .z(rec_dataH_temp[4])
  );
  (* src = "uart.v:68.1-78.6" *)
  dfnt1v0x2 _39_ (
    .cp(rec_readyH),
    .d(_07_),
    .z(rec_dataH_temp[6])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _40_ (
    .cp(sys_clk),
    .d(_08_),
    .z(rec_dataH[0])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _41_ (
    .cp(sys_clk),
    .d(_09_),
    .z(rec_dataH[1])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _42_ (
    .cp(sys_clk),
    .d(_10_),
    .z(rec_dataH[2])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _43_ (
    .cp(sys_clk),
    .d(_11_),
    .z(rec_dataH[3])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _44_ (
    .cp(sys_clk),
    .d(_12_),
    .z(rec_dataH[4])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _45_ (
    .cp(sys_clk),
    .d(_13_),
    .z(rec_dataH[5])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _46_ (
    .cp(sys_clk),
    .d(_14_),
    .z(rec_dataH[6])
  );
  (* src = "uart.v:58.1-65.6" *)
  dfnt1v0x2 _47_ (
    .cp(sys_clk),
    .d(_15_),
    .z(rec_dataH[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "uart.v:47.7-56.6" *)
  u_rec iRECEIVER (
    .rec_dataH(rec_dataH_rec),
    .rec_readyH(rec_readyH),
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_dataH(uart_REC_dataH)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "uart.v:35.9-42.5" *)
  u_xmit iXMIT (
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_xmitH(uart_XMIT_dataH),
    .xmitH(xmitH),
    .xmit_dataH(xmit_dataH),
    .xmit_doneH(xmit_doneH)
  );
  assign cntr = 1'h0;
endmodule
