/* Generated by Yosys 0.32+74 (git sha1 b739213d9, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "u_rec.v:4.1-179.10" *)
module u_rec(sys_rst_l, sys_clk, uart_dataH, rec_dataH, rec_readyH);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  (* src = "u_rec.v:120.16-120.45" *)
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* src = "u_rec.v:32.12-32.25" *)
  wire [3:0] bitCell_cntrH;
  (* src = "u_rec.v:46.9-46.12" *)
  reg ena = 1'h0;
  (* src = "u_rec.v:34.12-34.21" *)
  wire [7:0] par_dataH;
  (* src = "u_rec.v:31.8-31.16" *)
  wire rec_datH;
  (* src = "u_rec.v:31.18-31.30" *)
  wire rec_datSyncH;
  (* src = "u_rec.v:25.14-25.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "u_rec.v:44.9-44.25" *)
  reg rec_data_cntrH_1 = 1'h0;
  (* src = "u_rec.v:45.9-45.25" *)
  reg rec_data_cntrH_2 = 1'h0;
  (* src = "u_rec.v:26.10-26.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "u_rec.v:39.8-39.23" *)
  wire rec_readyH_temp;
  (* src = "u_rec.v:36.12-36.25" *)
  wire [3:0] recd_bitCntrH;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  (* src = "u_rec.v:21.9-21.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "u_rec.v:20.9-20.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "u_rec.v:23.9-23.19" *)
  input uart_dataH;
  wire uart_dataH;
  iv1v0x05 _073_ (
    .a(rec_datH),
    .z(_056_)
  );
  iv1v0x05 _074_ (
    .a(bitCell_cntrH[0]),
    .z(_057_)
  );
  iv1v0x05 _075_ (
    .a(state[4]),
    .z(_058_)
  );
  iv1v0x05 _076_ (
    .a(state[2]),
    .z(_059_)
  );
  nr3v0x05 _077_ (
    .a(bitCell_cntrH[1]),
    .b(bitCell_cntrH[0]),
    .c(bitCell_cntrH[3]),
    .z(_060_)
  );
  an2v0x05 _078_ (
    .a(bitCell_cntrH[2]),
    .b(_060_),
    .z(_061_)
  );
  nd2v0x05 _079_ (
    .a(bitCell_cntrH[2]),
    .b(_060_),
    .z(_062_)
  );
  an2v0x05 _080_ (
    .a(bitCell_cntrH[3]),
    .b(bitCell_cntrH[2]),
    .z(_063_)
  );
  nd3v0x05 _081_ (
    .a(bitCell_cntrH[1]),
    .b(_057_),
    .c(_063_),
    .z(_064_)
  );
  aoi31v0x05 _082_ (
    .a1(bitCell_cntrH[1]),
    .a2(_057_),
    .a3(_063_),
    .b(_058_),
    .z(_065_)
  );
  aoi31v0x05 _083_ (
    .a1(_056_),
    .a2(state[2]),
    .a3(_061_),
    .b(state[1]),
    .z(_066_)
  );
  aoi21a2bv0x05 _084_ (
    .a1(_066_),
    .a2(_065_),
    .b(sys_rst_l),
    .z(_004_)
  );
  aoi22v0x05 _085_ (
    .a1(_056_),
    .a2(state[0]),
    .b1(state[2]),
    .b2(_062_),
    .z(_067_)
  );
  nr2av0x1 _086_ (
    .a(sys_rst_l),
    .b(_067_),
    .z(_003_)
  );
  nd3v0x05 _087_ (
    .a(rec_datH),
    .b(state[2]),
    .c(_061_),
    .z(_005_)
  );
  nd4v0x05 _088_ (
    .a(rec_datH),
    .b(state[2]),
    .c(rec_data_cntrH_1),
    .d(_061_),
    .z(_006_)
  );
  nr3av0x05 _089_ (
    .a(rec_data_cntrH_2),
    .b(ena),
    .c(_005_),
    .z(_008_)
  );
  nd3abv0x05 _090_ (
    .a(ena),
    .b(_005_),
    .c(rec_data_cntrH_2),
    .z(_007_)
  );
  nr2av0x1 _091_ (
    .a(sys_rst_l),
    .b(state[3]),
    .z(_068_)
  );
  aoi21v0x05 _092_ (
    .a1(state[2]),
    .a2(_061_),
    .b(state[0]),
    .z(_069_)
  );
  oai21v0x05 _093_ (
    .a1(_056_),
    .a2(_069_),
    .b(_068_),
    .z(_002_)
  );
  nr2av0x1 _094_ (
    .a(par_dataH[0]),
    .b(ena),
    .z(rec_dataH[0])
  );
  nr2av0x1 _095_ (
    .a(par_dataH[1]),
    .b(ena),
    .z(rec_dataH[1])
  );
  nr2av0x1 _096_ (
    .a(par_dataH[2]),
    .b(ena),
    .z(rec_dataH[2])
  );
  nr2av0x1 _097_ (
    .a(par_dataH[3]),
    .b(ena),
    .z(rec_dataH[3])
  );
  nr2av0x1 _098_ (
    .a(par_dataH[4]),
    .b(ena),
    .z(rec_dataH[4])
  );
  nr2av0x1 _099_ (
    .a(par_dataH[5]),
    .b(ena),
    .z(rec_dataH[5])
  );
  nr2av0x1 _100_ (
    .a(par_dataH[6]),
    .b(ena),
    .z(rec_dataH[6])
  );
  nr2av0x1 _101_ (
    .a(par_dataH[7]),
    .b(ena),
    .z(rec_dataH[7])
  );
  nr2av0x1 _102_ (
    .a(rec_readyH_temp),
    .b(ena),
    .z(rec_readyH)
  );
  nd3abv0x05 _103_ (
    .a(recd_bitCntrH[1]),
    .b(recd_bitCntrH[0]),
    .c(recd_bitCntrH[3]),
    .z(_070_)
  );
  nr2v0x05 _104_ (
    .a(recd_bitCntrH[2]),
    .b(_070_),
    .z(_071_)
  );
  nr3abv0x05 _105_ (
    .a(state[4]),
    .b(sys_rst_l),
    .c(_064_),
    .z(_072_)
  );
  nr2av0x1 _106_ (
    .a(_072_),
    .b(_071_),
    .z(_001_)
  );
  an2v0x05 _107_ (
    .a(_071_),
    .b(_072_),
    .z(_000_)
  );
  nd2av0x05 _108_ (
    .a(uart_dataH),
    .b(sys_rst_l),
    .z(_009_)
  );
  nr4v1x05 _109_ (
    .a(state[4]),
    .b(state[0]),
    .c(state[3]),
    .d(state[2]),
    .z(_028_)
  );
  nr3v0x05 _110_ (
    .a(state[4]),
    .b(state[1]),
    .c(state[3]),
    .z(_029_)
  );
  nr3abv0x05 _111_ (
    .a(rec_datH),
    .b(_029_),
    .c(state[2]),
    .z(_030_)
  );
  aoi31v0x05 _112_ (
    .a1(rec_datH),
    .a2(_059_),
    .a3(_029_),
    .b(_028_),
    .z(_031_)
  );
  oai21v0x05 _113_ (
    .a1(recd_bitCntrH[0]),
    .a2(_028_),
    .b(sys_rst_l),
    .z(_032_)
  );
  aoi21a2v0x05 _114_ (
    .a1(recd_bitCntrH[0]),
    .a2(_031_),
    .b(_032_),
    .z(_010_)
  );
  xor2v0x05 _115_ (
    .a(recd_bitCntrH[1]),
    .b(recd_bitCntrH[0]),
    .z(_033_)
  );
  aoi22v0x05 _116_ (
    .a1(recd_bitCntrH[1]),
    .a2(_031_),
    .b1(_033_),
    .b2(_028_),
    .z(_034_)
  );
  nr2av0x1 _117_ (
    .a(sys_rst_l),
    .b(_034_),
    .z(_011_)
  );
  nd3v0x05 _118_ (
    .a(recd_bitCntrH[2]),
    .b(recd_bitCntrH[1]),
    .c(recd_bitCntrH[0]),
    .z(_035_)
  );
  an2v0x05 _119_ (
    .a(_028_),
    .b(_035_),
    .z(_036_)
  );
  aoi31v0x05 _120_ (
    .a1(recd_bitCntrH[1]),
    .a2(recd_bitCntrH[0]),
    .a3(_028_),
    .b(recd_bitCntrH[2]),
    .z(_037_)
  );
  oai21v0x05 _121_ (
    .a1(_031_),
    .a2(_036_),
    .b(sys_rst_l),
    .z(_038_)
  );
  nr2v0x05 _122_ (
    .a(_037_),
    .b(_038_),
    .z(_012_)
  );
  oai21v0x05 _123_ (
    .a1(_031_),
    .a2(_036_),
    .b(recd_bitCntrH[3]),
    .z(_039_)
  );
  nd3abv0x05 _124_ (
    .a(_035_),
    .b(recd_bitCntrH[3]),
    .c(_028_),
    .z(_040_)
  );
  aoi21bv0x05 _125_ (
    .a1(_039_),
    .a2(_040_),
    .b(sys_rst_l),
    .z(_013_)
  );
  mxn2v0x05 _126_ (
    .a0(par_dataH[0]),
    .a1(par_dataH[1]),
    .s(_028_),
    .z(_041_)
  );
  an2v0x05 _127_ (
    .a(sys_rst_l),
    .b(_041_),
    .z(_014_)
  );
  mxn2v0x05 _128_ (
    .a0(par_dataH[1]),
    .a1(par_dataH[2]),
    .s(_028_),
    .z(_042_)
  );
  an2v0x05 _129_ (
    .a(sys_rst_l),
    .b(_042_),
    .z(_015_)
  );
  mxn2v0x05 _130_ (
    .a0(par_dataH[2]),
    .a1(par_dataH[3]),
    .s(_028_),
    .z(_043_)
  );
  an2v0x05 _131_ (
    .a(sys_rst_l),
    .b(_043_),
    .z(_016_)
  );
  mxn2v0x05 _132_ (
    .a0(par_dataH[3]),
    .a1(par_dataH[4]),
    .s(_028_),
    .z(_044_)
  );
  an2v0x05 _133_ (
    .a(sys_rst_l),
    .b(_044_),
    .z(_017_)
  );
  mxn2v0x05 _134_ (
    .a0(par_dataH[4]),
    .a1(par_dataH[5]),
    .s(_028_),
    .z(_045_)
  );
  an2v0x05 _135_ (
    .a(sys_rst_l),
    .b(_045_),
    .z(_018_)
  );
  mxn2v0x05 _136_ (
    .a0(par_dataH[5]),
    .a1(par_dataH[6]),
    .s(_028_),
    .z(_046_)
  );
  an2v0x05 _137_ (
    .a(sys_rst_l),
    .b(_046_),
    .z(_019_)
  );
  mxn2v0x05 _138_ (
    .a0(par_dataH[6]),
    .a1(par_dataH[7]),
    .s(_028_),
    .z(_047_)
  );
  an2v0x05 _139_ (
    .a(sys_rst_l),
    .b(_047_),
    .z(_020_)
  );
  mxn2v0x05 _140_ (
    .a0(par_dataH[7]),
    .a1(rec_datH),
    .s(_028_),
    .z(_048_)
  );
  an2v0x05 _141_ (
    .a(sys_rst_l),
    .b(_048_),
    .z(_021_)
  );
  oan21v0x05 _142_ (
    .a1(state[3]),
    .a2(_030_),
    .b(sys_rst_l),
    .z(_022_)
  );
  aoi21v0x05 _143_ (
    .a1(bitCell_cntrH[2]),
    .a2(_060_),
    .b(state[4]),
    .z(_049_)
  );
  nr2v0x05 _144_ (
    .a(state[1]),
    .b(state[0]),
    .z(_050_)
  );
  oai211v0x05 _145_ (
    .a1(_065_),
    .a2(_049_),
    .b(_050_),
    .c(_068_),
    .z(_051_)
  );
  nr2v0x05 _146_ (
    .a(bitCell_cntrH[0]),
    .b(_051_),
    .z(_023_)
  );
  xnr2v0x05 _147_ (
    .a(bitCell_cntrH[1]),
    .b(bitCell_cntrH[0]),
    .z(_052_)
  );
  nr2v0x05 _148_ (
    .a(_051_),
    .b(_052_),
    .z(_024_)
  );
  aoi21v0x05 _149_ (
    .a1(bitCell_cntrH[1]),
    .a2(bitCell_cntrH[0]),
    .b(bitCell_cntrH[2]),
    .z(_053_)
  );
  nd3v0x05 _150_ (
    .a(bitCell_cntrH[1]),
    .b(bitCell_cntrH[0]),
    .c(bitCell_cntrH[2]),
    .z(_054_)
  );
  nr3av0x05 _151_ (
    .a(_054_),
    .b(_051_),
    .c(_053_),
    .z(_025_)
  );
  xor2v0x05 _152_ (
    .a(bitCell_cntrH[3]),
    .b(_054_),
    .z(_055_)
  );
  nr2v0x05 _153_ (
    .a(_051_),
    .b(_055_),
    .z(_026_)
  );
  nd2av0x05 _154_ (
    .a(rec_datSyncH),
    .b(sys_rst_l),
    .z(_027_)
  );
  (* src = "u_rec.v:54.1-61.6" *)
  dfnt1v0x2 _155_ (
    .cp(sys_clk),
    .d(_009_),
    .z(rec_datSyncH)
  );
  dfnt1v0x2 _156_ (
    .cp(sys_clk),
    .d(_002_),
    .z(state[0])
  );
  dfnt1v0x2 _157_ (
    .cp(sys_clk),
    .d(_001_),
    .z(state[1])
  );
  dfnt1v0x2 _158_ (
    .cp(sys_clk),
    .d(_003_),
    .z(state[2])
  );
  dfnt1v0x2 _159_ (
    .cp(sys_clk),
    .d(_000_),
    .z(state[3])
  );
  dfnt1v0x2 _160_ (
    .cp(sys_clk),
    .d(_004_),
    .z(state[4])
  );
  (* src = "u_rec.v:91.1-171.4" *)
  always @*
    if (!_005_) rec_data_cntrH_1 = 1'h1;
  (* src = "u_rec.v:91.1-171.4" *)
  always @*
    if (!_006_) rec_data_cntrH_2 = 1'h1;
  (* src = "u_rec.v:91.1-171.4" *)
  always @*
    if (!_007_) ena = 1'h1;
  (* src = "u_rec.v:78.1-81.42" *)
  dfnt1v0x2 _164_ (
    .cp(sys_clk),
    .d(_010_),
    .z(recd_bitCntrH[0])
  );
  (* src = "u_rec.v:78.1-81.42" *)
  dfnt1v0x2 _165_ (
    .cp(sys_clk),
    .d(_011_),
    .z(recd_bitCntrH[1])
  );
  (* src = "u_rec.v:78.1-81.42" *)
  dfnt1v0x2 _166_ (
    .cp(sys_clk),
    .d(_012_),
    .z(recd_bitCntrH[2])
  );
  (* src = "u_rec.v:78.1-81.42" *)
  dfnt1v0x2 _167_ (
    .cp(sys_clk),
    .d(_013_),
    .z(recd_bitCntrH[3])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _168_ (
    .cp(sys_clk),
    .d(_014_),
    .z(par_dataH[0])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _169_ (
    .cp(sys_clk),
    .d(_015_),
    .z(par_dataH[1])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _170_ (
    .cp(sys_clk),
    .d(_016_),
    .z(par_dataH[2])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _171_ (
    .cp(sys_clk),
    .d(_017_),
    .z(par_dataH[3])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _172_ (
    .cp(sys_clk),
    .d(_018_),
    .z(par_dataH[4])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _173_ (
    .cp(sys_clk),
    .d(_019_),
    .z(par_dataH[5])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _174_ (
    .cp(sys_clk),
    .d(_020_),
    .z(par_dataH[6])
  );
  (* src = "u_rec.v:70.1-75.6" *)
  dfnt1v0x2 _175_ (
    .cp(sys_clk),
    .d(_021_),
    .z(par_dataH[7])
  );
  (* src = "u_rec.v:174.1-176.40" *)
  dfnt1v0x2 _176_ (
    .cp(sys_clk),
    .d(_022_),
    .z(rec_readyH_temp)
  );
  (* src = "u_rec.v:64.1-67.43" *)
  dfnt1v0x2 _177_ (
    .cp(sys_clk),
    .d(_023_),
    .z(bitCell_cntrH[0])
  );
  (* src = "u_rec.v:64.1-67.43" *)
  dfnt1v0x2 _178_ (
    .cp(sys_clk),
    .d(_024_),
    .z(bitCell_cntrH[1])
  );
  (* src = "u_rec.v:64.1-67.43" *)
  dfnt1v0x2 _179_ (
    .cp(sys_clk),
    .d(_025_),
    .z(bitCell_cntrH[2])
  );
  (* src = "u_rec.v:64.1-67.43" *)
  dfnt1v0x2 _180_ (
    .cp(sys_clk),
    .d(_026_),
    .z(bitCell_cntrH[3])
  );
  (* src = "u_rec.v:54.1-61.6" *)
  dfnt1v0x2 _181_ (
    .cp(sys_clk),
    .d(_027_),
    .z(rec_datH)
  );
  always @*
    if (_008_)
      $write("Trojan Activated\n");
endmodule

(* src = "u_xmit.v:4.1-178.10" *)
module u_xmit(sys_clk, sys_rst_l, uart_xmitH, xmitH, xmit_dataH, xmit_doneH);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "u_xmit.v:27.12-27.25" *)
  wire [3:0] bitCell_cntrH;
  (* src = "u_xmit.v:30.12-30.21" *)
  wire [3:0] bitCountH;
  (* onehot = 32'd1 *)
  wire [3:0] state;
  (* src = "u_xmit.v:15.9-15.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "u_xmit.v:16.9-16.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "u_xmit.v:17.10-17.20" *)
  output uart_xmitH;
  wire uart_xmitH;
  (* src = "u_xmit.v:18.9-18.14" *)
  input xmitH;
  wire xmitH;
  (* src = "u_xmit.v:29.12-29.26" *)
  wire [7:0] xmit_ShiftRegH;
  (* src = "u_xmit.v:19.13-19.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "u_xmit.v:20.10-20.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  aoi21v0x05 _07_ (
    .a1(xmitH),
    .a2(state[0]),
    .b(state[1]),
    .z(_05_)
  );
  nr2av0x1 _08_ (
    .a(sys_rst_l),
    .b(_05_),
    .z(_03_)
  );
  oai21a2v0x05 _09_ (
    .a1(xmitH),
    .a2(state[0]),
    .b(sys_rst_l),
    .z(_02_)
  );
  or2v0x05 _10_ (
    .a(state[2]),
    .b(state[0]),
    .z(uart_xmitH)
  );
  an2v0x05 _11_ (
    .a(sys_rst_l),
    .b(state[2]),
    .z(_00_)
  );
  an2v0x05 _12_ (
    .a(sys_rst_l),
    .b(state[3]),
    .z(_01_)
  );
  nd3abv0x05 _13_ (
    .a(state[1]),
    .b(state[2]),
    .c(sys_rst_l),
    .z(_06_)
  );
  nr3v0x05 _14_ (
    .a(state[3]),
    .b(xmitH),
    .c(_06_),
    .z(_04_)
  );
  dfnt1v0x2 _15_ (
    .cp(sys_clk),
    .d(_02_),
    .z(state[0])
  );
  dfnt1v0x2 _16_ (
    .cp(sys_clk),
    .d(_03_),
    .z(state[1])
  );
  dfnt1v0x2 _17_ (
    .cp(sys_clk),
    .d(_00_),
    .z(state[2])
  );
  dfnt1v0x2 _18_ (
    .cp(sys_clk),
    .d(_01_),
    .z(state[3])
  );
  (* src = "u_xmit.v:173.1-175.35" *)
  dfnt1v0x2 _19_ (
    .cp(sys_clk),
    .d(_04_),
    .z(xmit_doneH)
  );
  assign bitCell_cntrH = 4'h0;
  assign bitCountH = 4'h0;
  assign xmit_ShiftRegH = 8'h00;
endmodule

(* src = "uart.v:3.1-78.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "uart.v:25.14-25.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "uart.v:30.17-30.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "uart.v:29.17-29.31" *)
  wire [7:0] rec_dataH_temp;
  (* src = "uart.v:26.10-26.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "uart.v:17.9-17.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "uart.v:18.9-18.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "uart.v:24.9-24.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "uart.v:19.10-19.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "uart.v:20.9-20.14" *)
  input xmitH;
  wire xmitH;
  (* src = "uart.v:21.13-21.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "uart.v:22.10-22.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  an2v0x05 _16_ (
    .a(rec_dataH_rec[0]),
    .b(sys_rst_l),
    .z(_00_)
  );
  an2v0x05 _17_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[1]),
    .z(_01_)
  );
  an2v0x05 _18_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[2]),
    .z(_02_)
  );
  an2v0x05 _19_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[3]),
    .z(_03_)
  );
  an2v0x05 _20_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[4]),
    .z(_04_)
  );
  an2v0x05 _21_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[5]),
    .z(_05_)
  );
  an2v0x05 _22_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[6]),
    .z(_06_)
  );
  an2v0x05 _23_ (
    .a(sys_rst_l),
    .b(rec_dataH_rec[7]),
    .z(_07_)
  );
  an2v0x05 _24_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[0]),
    .z(_08_)
  );
  an2v0x05 _25_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[1]),
    .z(_09_)
  );
  an2v0x05 _26_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[2]),
    .z(_10_)
  );
  an2v0x05 _27_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[3]),
    .z(_11_)
  );
  an2v0x05 _28_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[4]),
    .z(_12_)
  );
  an2v0x05 _29_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[5]),
    .z(_13_)
  );
  an2v0x05 _30_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[6]),
    .z(_14_)
  );
  an2v0x05 _31_ (
    .a(sys_rst_l),
    .b(rec_dataH_temp[7]),
    .z(_15_)
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _32_ (
    .cp(rec_readyH),
    .d(_00_),
    .z(rec_dataH_temp[0])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _33_ (
    .cp(rec_readyH),
    .d(_01_),
    .z(rec_dataH_temp[1])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _34_ (
    .cp(rec_readyH),
    .d(_02_),
    .z(rec_dataH_temp[2])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _35_ (
    .cp(rec_readyH),
    .d(_03_),
    .z(rec_dataH_temp[3])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _36_ (
    .cp(rec_readyH),
    .d(_04_),
    .z(rec_dataH_temp[4])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _37_ (
    .cp(rec_readyH),
    .d(_05_),
    .z(rec_dataH_temp[5])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _38_ (
    .cp(rec_readyH),
    .d(_06_),
    .z(rec_dataH_temp[6])
  );
  (* src = "uart.v:69.1-76.6" *)
  dfnt1v0x2 _39_ (
    .cp(rec_readyH),
    .d(_07_),
    .z(rec_dataH_temp[7])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _40_ (
    .cp(sys_clk),
    .d(_08_),
    .z(rec_dataH[0])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _41_ (
    .cp(sys_clk),
    .d(_09_),
    .z(rec_dataH[1])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _42_ (
    .cp(sys_clk),
    .d(_10_),
    .z(rec_dataH[2])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _43_ (
    .cp(sys_clk),
    .d(_11_),
    .z(rec_dataH[3])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _44_ (
    .cp(sys_clk),
    .d(_12_),
    .z(rec_dataH[4])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _45_ (
    .cp(sys_clk),
    .d(_13_),
    .z(rec_dataH[5])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _46_ (
    .cp(sys_clk),
    .d(_14_),
    .z(rec_dataH[6])
  );
  (* src = "uart.v:59.1-66.6" *)
  dfnt1v0x2 _47_ (
    .cp(sys_clk),
    .d(_15_),
    .z(rec_dataH[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "uart.v:47.7-57.6" *)
  u_rec iRECEIVER (
    .rec_dataH(rec_dataH_rec),
    .rec_readyH(rec_readyH),
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_dataH(uart_REC_dataH)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "uart.v:35.9-42.5" *)
  u_xmit iXMIT (
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_xmitH(uart_XMIT_dataH),
    .xmitH(xmitH),
    .xmit_dataH(xmit_dataH),
    .xmit_doneH(xmit_doneH)
  );
endmodule
