/* Generated by Yosys 0.31+1 (git sha1 83c9261d6, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* top =  1  *)
(* src = "spi_main.v:2.1-8.10" *)
module spi_main(t_start, sys_clk, d_in_m, d_in_s, d_out_m, d_out_s, rstn, miso, mosi);
  (* src = "spi_main.v:5.6-5.8" *)
  wire _0_;
  (* src = "spi_main.v:7.63-7.66" *)
  wire _1_;
  wire [31:0] _2_;
  wire [31:0] _3_;
  (* src = "spi_main.v:7.63-7.66" *)
  wire _4_;
  (* src = "spi_main.v:5.6-5.8" *)
  wire cs;
  (* src = "spi_main.v:2.58-2.64" *)
  input [7:0] d_in_m;
  wire [7:0] d_in_m;
  (* src = "spi_main.v:2.77-2.83" *)
  input [7:0] d_in_s;
  wire [7:0] d_in_s;
  (* src = "spi_main.v:2.97-2.104" *)
  output [7:0] d_out_m;
  wire [7:0] d_out_m;
  (* src = "spi_main.v:2.118-2.125" *)
  output [7:0] d_out_s;
  wire [7:0] d_out_s;
  (* src = "spi_main.v:2.146-2.150" *)
  output miso;
  wire miso;
  (* src = "spi_main.v:2.159-2.163" *)
  output mosi;
  wire mosi;
  (* src = "spi_main.v:2.133-2.137" *)
  input rstn;
  wire rstn;
  (* src = "spi_main.v:3.6-3.15" *)
  wire spi_clk_m;
  (* src = "spi_main.v:4.6-4.15" *)
  wire spi_clk_s;
  (* src = "spi_main.v:2.38-2.45" *)
  input sys_clk;
  wire sys_clk;
  (* src = "spi_main.v:2.23-2.30" *)
  input t_start;
  wire t_start;
  iv1v0x05 _5_ (
    .a(_0_),
    .z(_1_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "spi_main.v:6.12-6.172" *)
  spi_master master (
    .cs(cs),
    .d_in_m(d_in_m),
    .d_out_m(d_out_m),
    .miso(miso),
    .mosi(mosi),
    .rstn(rstn),
    .spi_clk(spi_clk_m),
    .sys_clk(sys_clk),
    .t_size(4'h8),
    .t_start(t_start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "spi_main.v:7.11-7.161" *)
  spi_slave slave (
    .d_in_s(d_in_s),
    .d_out_s(d_out_s),
    .miso(miso),
    .mosi(mosi),
    .rstn(_4_),
    .slave_clk(sys_clk),
    .spi_clk(spi_clk_s),
    .t_size(4'h8),
    .t_start(t_start)
  );
  assign _2_ = 32'd8;
  assign _3_ = 32'd8;
  assign _0_ = cs;
  assign _4_ = _1_;
endmodule

(* dynports =  1  *)
(* src = "spi_master.v:2.1-124.10" *)
module spi_master(rstn, sys_clk, t_start, d_in_m, t_size, d_out_m, miso, mosi, spi_clk, cs);
  (* src = "spi_master.v:31.5-74.4" *)
  wire [3:0] _000_;
  (* src = "spi_master.v:31.5-74.4" *)
  wire _001_;
  (* src = "spi_master.v:31.5-74.4" *)
  wire [7:0] _002_;
  (* src = "spi_master.v:31.5-74.4" *)
  wire [7:0] _003_;
  (* src = "spi_master.v:103.1-107.21" *)
  wire _004_;
  (* src = "spi_master.v:31.5-74.4" *)
  wire [7:0] _005_;
  (* src = "spi_master.v:31.5-74.4" *)
  wire [2:0] _006_;
  (* src = "spi_master.v:116.1-123.4" *)
  wire [3:0] _007_;
  (* src = "spi_master.v:110.1-114.4" *)
  wire [7:0] _008_;
  (* src = "spi_master.v:116.1-123.4" *)
  wire [7:0] _009_;
  (* src = "spi_master.v:31.5-74.4" *)
  wire [2:0] _010_;
  (* src = "spi_master.v:0.0-0.0" *)
  wire [3:0] _011_;
  (* src = "spi_master.v:0.0-0.0" *)
  wire [7:0] _012_;
  (* src = "spi_master.v:0.0-0.0" *)
  wire [7:0] _013_;
  (* src = "spi_master.v:75.1-102.4" *)
  wire [2:0] _014_;
  (* src = "spi_master.v:75.1-102.4" *)
  wire [2:0] _015_;
  (* src = "spi_master.v:75.1-102.4" *)
  wire [2:0] _016_;
  (* src = "spi_master.v:75.1-102.4" *)
  wire [2:0] _017_;
  (* src = "spi_master.v:75.1-102.4" *)
  wire [2:0] _018_;
  (* src = "spi_master.v:75.1-102.4" *)
  wire [2:0] _019_;
  (* src = "spi_master.v:75.1-102.4" *)
  wire [2:0] _020_;
  (* src = "spi_master.v:0.0-0.0" *)
  wire [2:0] _021_;
  wire _022_;
  (* src = "spi_master.v:8.11-8.15" *)
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  (* src = "spi_master.v:109.20-109.37" *)
  wire _102_;
  (* src = "spi_master.v:112.10-112.27" *)
  wire _103_;
  (* src = "spi_master.v:118.10-118.27" *)
  wire _104_;
  (* src = "spi_master.v:77.9-77.14" *)
  wire _105_;
  (* src = "spi_master.v:87.21-87.31" *)
  wire _106_;
  (* src = "spi_master.v:92.21-92.31" *)
  wire _107_;
  (* src = "spi_master.v:104.9-104.12" *)
  wire _108_;
  wire _109_;
  wire [2:0] _110_;
  wire _111_;
  wire [2:0] _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire [3:0] _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire [7:0] _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire [7:0] _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire [7:0] _138_;
  wire _139_;
  wire _140_;
  wire [3:0] _141_;
  wire _142_;
  wire [7:0] _143_;
  wire _144_;
  wire [7:0] _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire [2:0] _149_;
  wire _150_;
  wire [2:0] _151_;
  wire _152_;
  wire [2:0] _153_;
  wire _154_;
  wire [2:0] _155_;
  wire _156_;
  wire [2:0] _157_;
  wire _158_;
  wire [2:0] _159_;
  wire _160_;
  wire [2:0] _161_;
  wire _162_;
  wire [2:0] _163_;
  wire _164_;
  wire [2:0] _165_;
  wire _166_;
  wire [2:0] _167_;
  wire _168_;
  wire [2:0] _169_;
  wire _170_;
  wire [2:0] _171_;
  wire _172_;
  wire [2:0] _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire [2:0] _179_;
  (* src = "spi_master.v:121.18-121.25" *)
  wire [31:0] _180_;
  (* src = "spi_master.v:109.18-109.56" *)
  wire _181_;
  (* src = "spi_master.v:23.27-23.32" *)
  wire [3:0] count;
  (* src = "spi_master.v:19.16-19.18" *)
  output cs;
  wire cs;
  (* src = "spi_master.v:11.27-11.33" *)
  input [7:0] d_in_m;
  wire [7:0] d_in_m;
  (* src = "spi_master.v:13.32-13.39" *)
  output [7:0] d_out_m;
  wire [7:0] d_out_m;
  (* src = "spi_master.v:16.11-16.15" *)
  input miso;
  wire miso;
  (* src = "spi_master.v:22.25-22.31" *)
  wire [7:0] miso_d;
  (* src = "spi_master.v:17.16-17.20" *)
  output mosi;
  wire mosi;
  (* src = "spi_master.v:21.25-21.31" *)
  wire [7:0] mosi_d;
  (* src = "spi_master.v:8.11-8.15" *)
  input rstn;
  wire rstn;
  (* src = "spi_master.v:18.16-18.23" *)
  output spi_clk;
  wire spi_clk;
  (* src = "spi_master.v:24.15-24.20" *)
  wire [2:0] state;
  (* src = "spi_master.v:9.11-9.18" *)
  input sys_clk;
  wire sys_clk;
  (* src = "spi_master.v:12.29-12.35" *)
  input [3:0] t_size;
  wire [3:0] t_size;
  (* src = "spi_master.v:10.11-10.18" *)
  input t_start;
  wire t_start;
  bf1v0x05 _182_ (
    .a(_023_),
    .z(_022_)
  );
  (* src = "spi_master.v:75.1-102.4" *)
  dfnt1v0x2 _183_ (
    .cp(sys_clk),
    .d(_101_),
    .z(1'h0)
  );
  assign spi_clk = _181_;
  assign _021_ = 3'h0;
  assign _011_ = 4'h0;
  assign _013_ = 8'h00;
  assign _012_ = 8'h00;
  assign _014_ = _015_;
  assign _006_ = _010_;
  assign _142_ = _104_;
  assign _007_ = _141_;
  assign _144_ = _104_;
  assign _009_ = _143_;
  assign _146_ = _103_;
  assign _008_ = _145_;
  assign _148_ = _108_;
  assign _004_ = _147_;
  assign _150_ = t_start;
  assign _154_ = _105_;
  assign _020_ = _153_;
  assign _156_ = _107_;
  assign _160_ = _105_;
  assign _019_ = _159_;
  assign _162_ = _106_;
  assign _166_ = _105_;
  assign _018_ = _165_;
  assign _168_ = t_start;
  assign _172_ = _105_;
  assign _017_ = _171_;
  assign _109_ = _105_;
  assign _016_ = _179_;
  assign _111_ = _105_;
  assign _015_ = _110_;
  assign _010_ = _112_;
  assign _000_ = _118_;
  assign _003_ = _122_;
  assign _005_ = _127_;
  assign _001_ = _132_;
  assign _002_ = _138_;
  assign _112_ = 3'h0;
  assign _049_ = 1'h1;
  assign _078_ = _026_;
  assign _050_ = _026_;
  assign _051_ = _079_;
  assign _052_ = 1'h1;
  assign _080_ = _032_;
  assign _053_ = _032_;
  assign _054_ = _081_;
  assign _055_ = _082_;
  assign _056_ = _083_;
  assign _057_ = _084_;
  assign _058_ = 1'h1;
  assign _085_ = _037_;
  assign _059_ = _037_;
  assign _060_ = _086_;
  assign _061_ = _087_;
  assign _062_ = _088_;
  assign _063_ = 1'h1;
  assign _089_ = _042_;
  assign _064_ = _042_;
  assign _065_ = _090_;
  assign _066_ = _091_;
  assign _067_ = _092_;
  assign _068_ = 1'h1;
  assign _093_ = _046_;
  assign _069_ = _046_;
  assign _070_ = _094_;
  assign _071_ = _095_;
  assign _072_ = 1'h1;
  assign _096_ = _113_;
  assign _073_ = 1'h1;
  assign _097_ = _114_;
  assign _074_ = 1'h1;
  assign _098_ = _115_;
  assign _075_ = 1'h1;
  assign _099_ = _116_;
  assign _076_ = 1'h1;
  assign _100_ = _117_;
  assign _137_ = _140_;
  assign _133_ = _139_;
  assign _131_ = _140_;
  assign _130_ = _136_;
  assign _129_ = _135_;
  assign _128_ = _139_;
  assign _126_ = _140_;
  assign _125_ = _136_;
  assign _124_ = _135_;
  assign _123_ = _139_;
  assign _121_ = _140_;
  assign _120_ = _136_;
  assign _119_ = _135_;
  assign _117_ = _140_;
  assign _116_ = _136_;
  assign _115_ = _135_;
  assign _114_ = _134_;
  assign _113_ = _139_;
  assign _178_ = _140_;
  assign _177_ = _136_;
  assign _176_ = _135_;
  assign _175_ = _134_;
  assign _174_ = _139_;
  assign _170_ = _136_;
  assign _164_ = _135_;
  assign _158_ = _134_;
  assign _152_ = _139_;
  assign _104_ = _134_;
  assign _103_ = _134_;
  assign _102_ = _134_;
  assign _106_ = _107_;
  assign _026_ = _032_;
  assign _025_ = _028_;
  assign _042_ = _032_;
  assign _041_ = _030_;
  assign _040_ = _029_;
  assign _039_ = _028_;
  assign _044_ = _028_;
  assign _046_ = _030_;
  assign _037_ = _032_;
  assign _036_ = _030_;
  assign _035_ = _029_;
  assign _034_ = _028_;
  assign _045_ = _029_;
  assign _090_ = _086_;
  assign _091_ = _087_;
  assign _092_ = _088_;
  assign _043_ = _038_;
  assign _179_ = _173_;
  assign _171_ = _169_;
  assign _169_ = _167_;
  assign _165_ = _163_;
  assign _163_ = _161_;
  assign _159_ = _157_;
  assign _157_ = _155_;
  assign _153_ = _151_;
  assign _151_ = _149_;
  assign _122_ = 8'h00;
  assign state[0] = 1'h0;
  assign state[1] = 1'h0;
  assign state[2] = 1'h0;
  assign mosi_d[0] = 1'h0;
  assign _140_ = 1'h1;
  assign _028_ = 1'h0;
  assign _079_ = 1'h0;
  assign _027_ = 1'h1;
  assign _084_ = 1'h0;
  assign _033_ = 1'h1;
  assign _088_ = 1'h0;
  assign _038_ = 1'h1;
  assign _095_ = 1'h0;
  assign _047_ = 1'h1;
  assign _077_ = 1'h1;
  assign _048_ = 1'h0;
  assign _134_ = 1'h0;
  assign _145_ = miso_d;
  assign _143_ = mosi_d;
  assign _141_ = count;
  assign _181_ = 1'h0;
  assign _135_ = 1'h0;
  assign _136_ = 1'h0;
  assign _139_ = 1'h0;
  assign _118_ = 4'h0;
  assign _024_ = 1'h0;
  assign _127_ = 8'h00;
  assign _132_ = 1'h1;
  assign _138_ = 8'h00;
  assign _029_ = 1'h1;
  assign _030_ = 1'h1;
  assign _031_ = 1'h1;
  assign _032_ = 1'h1;
  assign _081_ = 1'h1;
  assign _082_ = 1'h1;
  assign _083_ = 1'h1;
  assign _086_ = 1'h1;
  assign _087_ = 1'h1;
  assign _094_ = 1'h1;
  assign _173_ = 3'h1;
  assign mosi = 1'hx;
  assign count = 4'h0;
  assign cs = 1'h1;
  assign count = 4'h0;
  assign miso_d = 8'h00;
  assign mosi_d = 8'h00;
  assign d_out_m = 8'h00;
  assign mosi_d[7:1] = 7'hxx;
  assign miso_d = 8'h00;
  assign _147_ = 1'hz;
  assign _107_ = 1'h0;
  assign _108_ = 1'h0;
  assign _180_ = 32'd4294967295;
  assign _023_ = rstn;
  assign _101_ = _022_;
endmodule

(* dynports =  1  *)
(* src = "spi_slave.v:2.1-121.10" *)
module spi_slave(rstn, slave_clk, t_start, d_in_s, t_size, d_out_s, spi_clk, mosi, miso);
  (* src = "spi_slave.v:27.5-65.4" *)
  wire [3:0] _000_;
  (* src = "spi_slave.v:27.5-65.4" *)
  wire [7:0] _001_;
  (* src = "spi_slave.v:94.1-98.21" *)
  wire _002_;
  (* src = "spi_slave.v:27.5-65.4" *)
  wire [7:0] _003_;
  (* src = "spi_slave.v:27.5-65.4" *)
  wire [7:0] _004_;
  (* src = "spi_slave.v:27.5-65.4" *)
  wire [2:0] _005_;
  (* src = "spi_slave.v:113.1-120.4" *)
  wire [3:0] _006_;
  (* src = "spi_slave.v:113.1-120.4" *)
  wire [7:0] _007_;
  (* src = "spi_slave.v:107.1-111.4" *)
  wire [7:0] _008_;
  (* src = "spi_slave.v:27.5-65.4" *)
  wire [2:0] _009_;
  (* src = "spi_slave.v:0.0-0.0" *)
  wire [3:0] _010_;
  (* src = "spi_slave.v:0.0-0.0" *)
  wire [7:0] _011_;
  (* src = "spi_slave.v:0.0-0.0" *)
  wire [7:0] _012_;
  (* src = "spi_slave.v:66.1-93.4" *)
  wire [2:0] _013_;
  (* src = "spi_slave.v:66.1-93.4" *)
  wire [2:0] _014_;
  (* src = "spi_slave.v:66.1-93.4" *)
  wire [2:0] _015_;
  (* src = "spi_slave.v:66.1-93.4" *)
  wire [2:0] _016_;
  (* src = "spi_slave.v:66.1-93.4" *)
  wire [2:0] _017_;
  (* src = "spi_slave.v:66.1-93.4" *)
  wire [2:0] _018_;
  (* src = "spi_slave.v:66.1-93.4" *)
  wire [2:0] _019_;
  (* src = "spi_slave.v:0.0-0.0" *)
  wire [2:0] _020_;
  wire _021_;
  (* src = "spi_slave.v:6.11-6.15" *)
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  (* src = "spi_slave.v:105.20-105.37" *)
  wire _080_;
  (* src = "spi_slave.v:109.10-109.27" *)
  wire _081_;
  (* src = "spi_slave.v:115.10-115.27" *)
  wire _082_;
  (* src = "spi_slave.v:105.18-105.55" *)
  wire [31:0] _083_;
  (* src = "spi_slave.v:68.9-68.14" *)
  wire _084_;
  (* src = "spi_slave.v:78.21-78.31" *)
  wire _085_;
  (* src = "spi_slave.v:83.21-83.31" *)
  wire _086_;
  wire [3:0] _087_;
  wire _088_;
  wire [7:0] _089_;
  wire _090_;
  wire [7:0] _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire [2:0] _095_;
  wire _096_;
  wire [2:0] _097_;
  wire _098_;
  wire [2:0] _099_;
  wire _100_;
  wire [2:0] _101_;
  wire _102_;
  wire [2:0] _103_;
  wire _104_;
  wire [2:0] _105_;
  wire _106_;
  wire [2:0] _107_;
  wire _108_;
  wire [2:0] _109_;
  wire _110_;
  wire [2:0] _111_;
  wire _112_;
  wire [2:0] _113_;
  wire _114_;
  wire [2:0] _115_;
  wire _116_;
  wire [2:0] _117_;
  wire _118_;
  wire [2:0] _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire [2:0] _125_;
  wire _126_;
  wire [2:0] _127_;
  wire _128_;
  wire [2:0] _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire [3:0] _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire [7:0] _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire [7:0] _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire [7:0] _148_;
  wire _149_;
  wire _150_;
  (* src = "spi_slave.v:118.18-118.25" *)
  wire [31:0] _151_;
  (* src = "spi_slave.v:105.18-105.55" *)
  wire [31:0] _152_;
  (* src = "spi_slave.v:19.27-19.32" *)
  wire [3:0] count;
  (* src = "spi_slave.v:9.27-9.33" *)
  input [7:0] d_in_s;
  wire [7:0] d_in_s;
  (* src = "spi_slave.v:11.32-11.39" *)
  output [7:0] d_out_s;
  wire [7:0] d_out_s;
  (* src = "spi_slave.v:16.16-16.20" *)
  output miso;
  wire miso;
  (* src = "spi_slave.v:18.25-18.31" *)
  wire [7:0] miso_d;
  (* src = "spi_slave.v:15.11-15.15" *)
  input mosi;
  wire mosi;
  (* src = "spi_slave.v:17.25-17.31" *)
  wire [7:0] mosi_d;
  (* src = "spi_slave.v:6.11-6.15" *)
  input rstn;
  wire rstn;
  (* src = "spi_slave.v:7.11-7.20" *)
  input slave_clk;
  wire slave_clk;
  (* src = "spi_slave.v:12.16-12.23" *)
  output spi_clk;
  wire spi_clk;
  (* src = "spi_slave.v:20.15-20.20" *)
  wire [2:0] state;
  (* src = "spi_slave.v:10.29-10.35" *)
  input [3:0] t_size;
  wire [3:0] t_size;
  (* src = "spi_slave.v:8.11-8.18" *)
  input t_start;
  wire t_start;
  bf1v0x05 _153_ (
    .a(_022_),
    .z(_021_)
  );
  (* src = "spi_slave.v:66.1-93.4" *)
  dfnt1v0x2 _154_ (
    .cp(slave_clk),
    .d(_079_),
    .z(1'h0)
  );
  assign spi_clk = _152_[0];
  assign _020_ = 3'h0;
  assign _010_ = 4'h0;
  assign _012_ = 8'h00;
  assign _011_ = 8'h00;
  assign _013_ = _014_;
  assign _005_ = _009_;
  assign _088_ = _082_;
  assign _006_ = _087_;
  assign _090_ = _082_;
  assign _007_ = _089_;
  assign _092_ = _081_;
  assign _008_ = _091_;
  assign _094_ = rstn;
  assign _002_ = _093_;
  assign _096_ = t_start;
  assign _100_ = _084_;
  assign _019_ = _099_;
  assign _102_ = _086_;
  assign _106_ = _084_;
  assign _018_ = _105_;
  assign _108_ = _085_;
  assign _112_ = _084_;
  assign _017_ = _111_;
  assign _114_ = t_start;
  assign _118_ = _084_;
  assign _016_ = _117_;
  assign _126_ = _084_;
  assign _015_ = _125_;
  assign _128_ = _084_;
  assign _014_ = _127_;
  assign _009_ = _129_;
  assign _000_ = _135_;
  assign _003_ = _139_;
  assign _004_ = _144_;
  assign _001_ = _148_;
  assign _129_ = 3'h0;
  assign _040_ = 1'h1;
  assign _062_ = _024_;
  assign _041_ = _024_;
  assign _042_ = _063_;
  assign _043_ = 1'h1;
  assign _064_ = _028_;
  assign _044_ = _028_;
  assign _045_ = _065_;
  assign _046_ = _066_;
  assign _047_ = 1'h1;
  assign _067_ = _033_;
  assign _048_ = _033_;
  assign _049_ = _068_;
  assign _050_ = _069_;
  assign _051_ = _070_;
  assign _052_ = 1'h1;
  assign _071_ = _037_;
  assign _053_ = _037_;
  assign _054_ = _072_;
  assign _055_ = _073_;
  assign _056_ = 1'h1;
  assign _074_ = _130_;
  assign _057_ = 1'h1;
  assign _075_ = _131_;
  assign _058_ = 1'h1;
  assign _076_ = _132_;
  assign _059_ = 1'h1;
  assign _077_ = _133_;
  assign _060_ = 1'h1;
  assign _078_ = _134_;
  assign _147_ = _150_;
  assign _143_ = _150_;
  assign _142_ = _146_;
  assign _141_ = _145_;
  assign _140_ = _149_;
  assign _138_ = _150_;
  assign _137_ = _146_;
  assign _136_ = _145_;
  assign _134_ = _150_;
  assign _133_ = _146_;
  assign _132_ = _145_;
  assign _130_ = _149_;
  assign _124_ = _150_;
  assign _123_ = _146_;
  assign _122_ = _145_;
  assign _121_ = _131_;
  assign _120_ = _149_;
  assign _116_ = _146_;
  assign _110_ = _145_;
  assign _104_ = _131_;
  assign _098_ = _149_;
  assign _082_ = _131_;
  assign _081_ = _131_;
  assign _080_ = _131_;
  assign _085_ = _086_;
  assign _023_ = _026_;
  assign _033_ = _024_;
  assign _032_ = _037_;
  assign _031_ = _036_;
  assign _030_ = _026_;
  assign _035_ = _026_;
  assign _028_ = _037_;
  assign _027_ = _036_;
  assign _065_ = _072_;
  assign _066_ = _073_;
  assign _029_ = _038_;
  assign _125_ = _119_;
  assign _117_ = _115_;
  assign _115_ = _113_;
  assign _111_ = _109_;
  assign _109_ = _107_;
  assign _105_ = _103_;
  assign _103_ = _101_;
  assign _099_ = _097_;
  assign _097_ = _095_;
  assign _144_ = 8'h00;
  assign miso_d[0] = 1'h0;
  assign state[0] = 1'h0;
  assign state[1] = 1'h0;
  assign state[2] = 1'h0;
  assign _150_ = 1'h1;
  assign _026_ = 1'h0;
  assign _063_ = 1'h0;
  assign _025_ = 1'h1;
  assign _070_ = 1'h0;
  assign _034_ = 1'h1;
  assign _073_ = 1'h0;
  assign _038_ = 1'h1;
  assign _061_ = 1'h1;
  assign _039_ = 1'h0;
  assign _131_ = 1'h0;
  assign _152_ = 32'd0;
  assign _087_ = count;
  assign _089_ = miso_d;
  assign _091_ = mosi_d;
  assign _145_ = 1'h0;
  assign _146_ = 1'h0;
  assign _149_ = 1'h0;
  assign _135_ = 4'h0;
  assign _139_ = 8'h00;
  assign _148_ = 8'h00;
  assign _024_ = 1'h1;
  assign _037_ = 1'h1;
  assign _068_ = 1'h1;
  assign _036_ = 1'h1;
  assign _069_ = 1'h1;
  assign _072_ = 1'h1;
  assign _119_ = 3'h1;
  assign miso = 1'hx;
  assign mosi_d = 8'h00;
  assign miso_d = 8'h00;
  assign miso_d[7:1] = 7'hxx;
  assign count = 4'h0;
  assign count = 4'hx;
  assign mosi_d = 8'h00;
  assign d_out_s = 8'h00;
  assign _086_ = 1'h0;
  assign _151_ = 32'd4294967295;
  assign _083_ = { 31'h00000000, slave_clk };
  assign _022_ = rstn;
  assign _079_ = _021_;
endmodule
