/* Generated by Yosys 0.32+74 (git sha1 b739213d9, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "async_reset.v:8.1-25.10" *)
module \$abstract\async_reset ();
endmodule

(* src = "display_clocks.v:10.1-96.10" *)
module \$abstract\display_clocks ();
endmodule

(* src = "display_timings.v:10.1-80.10" *)
module \$abstract\display_timings ();
endmodule

(* src = "dvi_generator.v:8.1-94.10" *)
module \$abstract\dvi_generator ();
endmodule

(* src = "serializer_10to1.v:8.1-117.10" *)
module \$abstract\serializer_10to1 ();
endmodule

(* src = "tmds_encoder_dvi.v:8.1-95.10" *)
module \$abstract\tmds_encoder_dvi ();
endmodule
