/* Generated by Yosys 0.32+74 (git sha1 b739213d9, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* dynports =  1  *)
(* hdlname = "\\up_cnt_mod" *)
(* src = "utils.v:25.1-48.10" *)
module \$paramod$a8e0632467158ddaf1a03dbaacb5062349325662\up_cnt_mod (CLK, CE, CLR, Q, CO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "utils.v:31.25-31.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:30.25-30.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:32.25-32.28" *)
  input CLR;
  wire CLR;
  (* src = "utils.v:34.25-34.27" *)
  output CO;
  wire CO;
  (* init = 12'h000 *)
  (* src = "utils.v:33.25-33.26" *)
  output [11:0] Q;
  wire [11:0] Q;
  iv1v0x05 _37_ (
    .a(Q[10]),
    .z(_12_)
  );
  iv1v0x05 _38_ (
    .a(Q[9]),
    .z(_13_)
  );
  an3v0x05 _39_ (
    .a(CE),
    .b(Q[1]),
    .c(Q[0]),
    .z(_14_)
  );
  an4v0x05 _40_ (
    .a(CE),
    .b(Q[2]),
    .c(Q[1]),
    .d(Q[0]),
    .z(_15_)
  );
  an2v0x05 _41_ (
    .a(Q[3]),
    .b(_15_),
    .z(_16_)
  );
  an4v0x05 _42_ (
    .a(Q[5]),
    .b(Q[4]),
    .c(Q[3]),
    .d(_15_),
    .z(_17_)
  );
  an2v0x05 _43_ (
    .a(Q[6]),
    .b(_17_),
    .z(_18_)
  );
  nr3v0x05 _44_ (
    .a(Q[9]),
    .b(Q[8]),
    .c(Q[7]),
    .z(_19_)
  );
  nd3v0x05 _45_ (
    .a(Q[11]),
    .b(Q[10]),
    .c(_19_),
    .z(_20_)
  );
  nr3abv0x05 _46_ (
    .a(Q[6]),
    .b(_17_),
    .c(_20_),
    .z(CO)
  );
  xnr2v0x05 _47_ (
    .a(CE),
    .b(Q[0]),
    .z(_21_)
  );
  nr2v0x05 _48_ (
    .a(CLR),
    .b(_21_),
    .z(_00_)
  );
  aoi21v0x05 _49_ (
    .a1(CE),
    .a2(Q[0]),
    .b(Q[1]),
    .z(_22_)
  );
  nr3v0x05 _50_ (
    .a(CLR),
    .b(_14_),
    .c(_22_),
    .z(_01_)
  );
  nr2v0x05 _51_ (
    .a(Q[2]),
    .b(_14_),
    .z(_23_)
  );
  nr3v0x05 _52_ (
    .a(CLR),
    .b(_15_),
    .c(_23_),
    .z(_02_)
  );
  nr2v0x05 _53_ (
    .a(Q[3]),
    .b(_15_),
    .z(_24_)
  );
  nr3v0x05 _54_ (
    .a(CLR),
    .b(_16_),
    .c(_24_),
    .z(_03_)
  );
  xnr2v0x05 _55_ (
    .a(Q[4]),
    .b(_16_),
    .z(_25_)
  );
  nr2v0x05 _56_ (
    .a(CLR),
    .b(_25_),
    .z(_04_)
  );
  aoi21v0x05 _57_ (
    .a1(Q[4]),
    .a2(_16_),
    .b(Q[5]),
    .z(_26_)
  );
  nr3v0x05 _58_ (
    .a(CLR),
    .b(_17_),
    .c(_26_),
    .z(_05_)
  );
  nr2v0x05 _59_ (
    .a(Q[6]),
    .b(_17_),
    .z(_27_)
  );
  nr3v0x05 _60_ (
    .a(CLR),
    .b(_18_),
    .c(_27_),
    .z(_06_)
  );
  nr2v0x05 _61_ (
    .a(CLR),
    .b(CO),
    .z(_28_)
  );
  xnr2v0x05 _62_ (
    .a(Q[7]),
    .b(_18_),
    .z(_29_)
  );
  nr3v0x05 _63_ (
    .a(CLR),
    .b(CO),
    .c(_29_),
    .z(_07_)
  );
  an4v0x05 _64_ (
    .a(Q[8]),
    .b(Q[7]),
    .c(Q[6]),
    .d(_17_),
    .z(_30_)
  );
  nd4v0x05 _65_ (
    .a(Q[8]),
    .b(Q[7]),
    .c(Q[6]),
    .d(_17_),
    .z(_31_)
  );
  aoi21v0x05 _66_ (
    .a1(Q[7]),
    .a2(_18_),
    .b(Q[8]),
    .z(_32_)
  );
  nr3v0x05 _67_ (
    .a(CLR),
    .b(_30_),
    .c(_32_),
    .z(_08_)
  );
  xnr2v0x05 _68_ (
    .a(Q[9]),
    .b(_30_),
    .z(_33_)
  );
  nr2v0x05 _69_ (
    .a(CLR),
    .b(_33_),
    .z(_09_)
  );
  xooi21v0x05 _70_ (
    .a1(_13_),
    .a2(_31_),
    .b(Q[10]),
    .z(_34_)
  );
  an2v0x05 _71_ (
    .a(_28_),
    .b(_34_),
    .z(_10_)
  );
  oai31v0x05 _72_ (
    .a1(_12_),
    .a2(_13_),
    .a3(_31_),
    .b(Q[11]),
    .z(_35_)
  );
  nr4v1x05 _73_ (
    .a(Q[11]),
    .b(_12_),
    .c(_13_),
    .d(_31_),
    .z(_36_)
  );
  aoi21a2bv0x05 _74_ (
    .a1(_35_),
    .a2(_36_),
    .b(_28_),
    .z(_11_)
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _75_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _76_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _77_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _78_ (
    .cp(CLK),
    .d(_03_),
    .z(Q[3])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _79_ (
    .cp(CLK),
    .d(_04_),
    .z(Q[4])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _80_ (
    .cp(CLK),
    .d(_05_),
    .z(Q[5])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _81_ (
    .cp(CLK),
    .d(_06_),
    .z(Q[6])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _82_ (
    .cp(CLK),
    .d(_07_),
    .z(Q[7])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _83_ (
    .cp(CLK),
    .d(_08_),
    .z(Q[8])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _84_ (
    .cp(CLK),
    .d(_09_),
    .z(Q[9])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _85_ (
    .cp(CLK),
    .d(_10_),
    .z(Q[10])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _86_ (
    .cp(CLK),
    .d(_11_),
    .z(Q[11])
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\up_cnt_mod" *)
(* src = "utils.v:25.1-48.10" *)
module \$paramod$bd56cd18463522cf742d73406a4024be0afccdd0\up_cnt_mod (CLK, CE, CLR, Q, CO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "utils.v:31.25-31.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:30.25-30.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:32.25-32.28" *)
  input CLR;
  wire CLR;
  (* src = "utils.v:34.25-34.27" *)
  output CO;
  wire CO;
  (* init = 3'h0 *)
  (* src = "utils.v:33.25-33.26" *)
  output [2:0] Q;
  wire [2:0] Q;
  an4v0x05 _06_ (
    .a(Q[2]),
    .b(CE),
    .c(Q[1]),
    .d(Q[0]),
    .z(CO)
  );
  xnr2v0x05 _07_ (
    .a(CE),
    .b(Q[0]),
    .z(_03_)
  );
  nr2v0x05 _08_ (
    .a(CLR),
    .b(_03_),
    .z(_00_)
  );
  xaoi21v0x05 _09_ (
    .a1(CE),
    .a2(Q[0]),
    .b(Q[1]),
    .z(_04_)
  );
  nr2v0x05 _10_ (
    .a(CLR),
    .b(_04_),
    .z(_01_)
  );
  aoi31v0x05 _11_ (
    .a1(CE),
    .a2(Q[1]),
    .a3(Q[0]),
    .b(Q[2]),
    .z(_05_)
  );
  nr3v0x05 _12_ (
    .a(CLR),
    .b(CO),
    .c(_05_),
    .z(_02_)
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _13_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _14_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _15_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\prescaler" *)
(* src = "utils.v:1.1-23.10" *)
module \$paramod$dac31f5b8da215793873bc3275fc490f79fae642\prescaler (CLK, CE, CEO);
  wire _0_;
  wire _1_;
  (* src = "utils.v:8.11-8.13" *)
  input CE;
  wire CE;
  (* src = "utils.v:9.12-9.15" *)
  output CEO;
  wire CEO;
  (* src = "utils.v:7.11-7.14" *)
  input CLK;
  wire CLK;
  (* init = 2'h0 *)
  (* src = "utils.v:12.13-12.14" *)
  wire [1:0] Q;
  an3v0x05 _2_ (
    .a(Q[0]),
    .b(Q[1]),
    .c(CE),
    .z(CEO)
  );
  xor2v0x05 _3_ (
    .a(Q[0]),
    .b(CE),
    .z(_0_)
  );
  xaon21v0x05 _4_ (
    .a1(Q[0]),
    .a2(CE),
    .b(Q[1]),
    .z(_1_)
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _5_ (
    .cp(CLK),
    .d(_0_),
    .z(Q[0])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _6_ (
    .cp(CLK),
    .d(_1_),
    .z(Q[1])
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\shift_reg" *)
(* src = "utils.v:50.1-72.10" *)
module \$paramod\shift_reg\W=s32'00000000000000000000000000001000 (CLK, CE, CLR, DIR, D, Q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "utils.v:55.25-55.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:54.25-54.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:56.25-56.28" *)
  input CLR;
  wire CLR;
  (* src = "utils.v:58.25-58.26" *)
  input D;
  wire D;
  (* src = "utils.v:57.25-57.28" *)
  input DIR;
  wire DIR;
  (* src = "utils.v:59.25-59.26" *)
  output [7:0] Q;
  wire [7:0] Q;
  mxi2v0x05 _24_ (
    .a0(D),
    .a1(Q[1]),
    .s(DIR),
    .z(_08_)
  );
  nr2v0x05 _25_ (
    .a(CE),
    .b(Q[0]),
    .z(_09_)
  );
  aoi112v0x05 _26_ (
    .a(CLR),
    .b(_09_),
    .c1(_08_),
    .c2(CE),
    .z(_00_)
  );
  mxi2v0x05 _27_ (
    .a0(Q[0]),
    .a1(Q[2]),
    .s(DIR),
    .z(_10_)
  );
  nr2v0x05 _28_ (
    .a(CE),
    .b(Q[1]),
    .z(_11_)
  );
  aoi112v0x05 _29_ (
    .a(CLR),
    .b(_11_),
    .c1(_10_),
    .c2(CE),
    .z(_01_)
  );
  mxi2v0x05 _30_ (
    .a0(Q[1]),
    .a1(Q[3]),
    .s(DIR),
    .z(_12_)
  );
  nr2v0x05 _31_ (
    .a(CE),
    .b(Q[2]),
    .z(_13_)
  );
  aoi112v0x05 _32_ (
    .a(CLR),
    .b(_13_),
    .c1(_12_),
    .c2(CE),
    .z(_02_)
  );
  mxi2v0x05 _33_ (
    .a0(Q[2]),
    .a1(Q[4]),
    .s(DIR),
    .z(_14_)
  );
  nr2v0x05 _34_ (
    .a(CE),
    .b(Q[3]),
    .z(_15_)
  );
  aoi112v0x05 _35_ (
    .a(CLR),
    .b(_15_),
    .c1(_14_),
    .c2(CE),
    .z(_03_)
  );
  mxi2v0x05 _36_ (
    .a0(Q[3]),
    .a1(Q[5]),
    .s(DIR),
    .z(_16_)
  );
  nr2v0x05 _37_ (
    .a(CE),
    .b(Q[4]),
    .z(_17_)
  );
  aoi112v0x05 _38_ (
    .a(CLR),
    .b(_17_),
    .c1(_16_),
    .c2(CE),
    .z(_04_)
  );
  mxi2v0x05 _39_ (
    .a0(Q[4]),
    .a1(Q[6]),
    .s(DIR),
    .z(_18_)
  );
  nr2v0x05 _40_ (
    .a(CE),
    .b(Q[5]),
    .z(_19_)
  );
  aoi112v0x05 _41_ (
    .a(CLR),
    .b(_19_),
    .c1(_18_),
    .c2(CE),
    .z(_05_)
  );
  mxi2v0x05 _42_ (
    .a0(Q[5]),
    .a1(Q[7]),
    .s(DIR),
    .z(_20_)
  );
  nr2v0x05 _43_ (
    .a(CE),
    .b(Q[6]),
    .z(_21_)
  );
  aoi112v0x05 _44_ (
    .a(CLR),
    .b(_21_),
    .c1(_20_),
    .c2(CE),
    .z(_06_)
  );
  mxi2v0x05 _45_ (
    .a0(Q[6]),
    .a1(D),
    .s(DIR),
    .z(_22_)
  );
  nr2v0x05 _46_ (
    .a(Q[7]),
    .b(CE),
    .z(_23_)
  );
  aoi112v0x05 _47_ (
    .a(CLR),
    .b(_23_),
    .c1(_22_),
    .c2(CE),
    .z(_07_)
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _48_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _49_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _50_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _51_ (
    .cp(CLK),
    .d(_03_),
    .z(Q[3])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _52_ (
    .cp(CLK),
    .d(_04_),
    .z(Q[4])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _53_ (
    .cp(CLK),
    .d(_05_),
    .z(Q[5])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _54_ (
    .cp(CLK),
    .d(_06_),
    .z(Q[6])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _55_ (
    .cp(CLK),
    .d(_07_),
    .z(Q[7])
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\up_cnt_mod" *)
(* src = "utils.v:25.1-48.10" *)
module \$paramod\up_cnt_mod\MODULO=10'1000001101\W=s32'00000000000000000000000000001010 (CLK, CE, CLR, Q, CO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  (* src = "utils.v:31.25-31.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:30.25-30.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:32.25-32.28" *)
  input CLR;
  wire CLR;
  (* src = "utils.v:34.25-34.27" *)
  output CO;
  wire CO;
  (* init = 10'h000 *)
  (* src = "utils.v:33.25-33.26" *)
  output [9:0] Q;
  wire [9:0] Q;
  nr3abv0x05 _30_ (
    .a(Q[3]),
    .b(Q[2]),
    .c(Q[4]),
    .z(_10_)
  );
  nr4v1x05 _31_ (
    .a(Q[8]),
    .b(Q[7]),
    .c(Q[6]),
    .d(Q[5]),
    .z(_11_)
  );
  nr2v0x05 _32_ (
    .a(Q[1]),
    .b(Q[0]),
    .z(_12_)
  );
  nd3v0x05 _33_ (
    .a(Q[9]),
    .b(CE),
    .c(_12_),
    .z(_13_)
  );
  nr3abv0x05 _34_ (
    .a(_10_),
    .b(_11_),
    .c(_13_),
    .z(CO)
  );
  or2v0x05 _35_ (
    .a(CLR),
    .b(CO),
    .z(_14_)
  );
  xnr2v0x05 _36_ (
    .a(CE),
    .b(Q[0]),
    .z(_15_)
  );
  nr2v0x05 _37_ (
    .a(_14_),
    .b(_15_),
    .z(_00_)
  );
  xaoi21v0x05 _38_ (
    .a1(CE),
    .a2(Q[0]),
    .b(Q[1]),
    .z(_16_)
  );
  nr2v0x05 _39_ (
    .a(CLR),
    .b(_16_),
    .z(_01_)
  );
  aoi31v0x05 _40_ (
    .a1(CE),
    .a2(Q[1]),
    .a3(Q[0]),
    .b(Q[2]),
    .z(_17_)
  );
  an4v0x05 _41_ (
    .a(CE),
    .b(Q[2]),
    .c(Q[1]),
    .d(Q[0]),
    .z(_18_)
  );
  nr3v0x05 _42_ (
    .a(_14_),
    .b(_17_),
    .c(_18_),
    .z(_02_)
  );
  nr2v0x05 _43_ (
    .a(Q[3]),
    .b(_18_),
    .z(_19_)
  );
  an2v0x05 _44_ (
    .a(Q[3]),
    .b(_18_),
    .z(_20_)
  );
  nr3v0x05 _45_ (
    .a(_14_),
    .b(_19_),
    .c(_20_),
    .z(_03_)
  );
  aoi21v0x05 _46_ (
    .a1(Q[4]),
    .a2(_20_),
    .b(CLR),
    .z(_21_)
  );
  oan21v0x05 _47_ (
    .a1(Q[4]),
    .a2(_20_),
    .b(_21_),
    .z(_04_)
  );
  an4v0x05 _48_ (
    .a(Q[5]),
    .b(Q[4]),
    .c(Q[3]),
    .d(_18_),
    .z(_22_)
  );
  aoi21v0x05 _49_ (
    .a1(Q[4]),
    .a2(_20_),
    .b(Q[5]),
    .z(_23_)
  );
  nr3v0x05 _50_ (
    .a(CLR),
    .b(_22_),
    .c(_23_),
    .z(_05_)
  );
  an2v0x05 _51_ (
    .a(Q[6]),
    .b(_22_),
    .z(_24_)
  );
  nr2v0x05 _52_ (
    .a(Q[6]),
    .b(_22_),
    .z(_25_)
  );
  nr3v0x05 _53_ (
    .a(CLR),
    .b(_24_),
    .c(_25_),
    .z(_06_)
  );
  an3v0x05 _54_ (
    .a(Q[7]),
    .b(Q[6]),
    .c(_22_),
    .z(_26_)
  );
  nr2v0x05 _55_ (
    .a(Q[7]),
    .b(_24_),
    .z(_27_)
  );
  nr3v0x05 _56_ (
    .a(CLR),
    .b(_26_),
    .c(_27_),
    .z(_07_)
  );
  aoi21v0x05 _57_ (
    .a1(Q[8]),
    .a2(_26_),
    .b(CLR),
    .z(_28_)
  );
  oan21v0x05 _58_ (
    .a1(Q[8]),
    .a2(_26_),
    .b(_28_),
    .z(_08_)
  );
  xaoi21v0x05 _59_ (
    .a1(Q[8]),
    .a2(_26_),
    .b(Q[9]),
    .z(_29_)
  );
  nr2v0x05 _60_ (
    .a(_14_),
    .b(_29_),
    .z(_09_)
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _61_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _62_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _63_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _64_ (
    .cp(CLK),
    .d(_03_),
    .z(Q[3])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _65_ (
    .cp(CLK),
    .d(_04_),
    .z(Q[4])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _66_ (
    .cp(CLK),
    .d(_05_),
    .z(Q[5])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _67_ (
    .cp(CLK),
    .d(_06_),
    .z(Q[6])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _68_ (
    .cp(CLK),
    .d(_07_),
    .z(Q[7])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _69_ (
    .cp(CLK),
    .d(_08_),
    .z(Q[8])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _70_ (
    .cp(CLK),
    .d(_09_),
    .z(Q[9])
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\up_cnt_mod" *)
(* src = "utils.v:25.1-48.10" *)
module \$paramod\up_cnt_mod\MODULO=10'1100100000\W=s32'00000000000000000000000000001010 (CLK, CE, CLR, Q, CO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  (* src = "utils.v:31.25-31.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:30.25-30.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:32.25-32.28" *)
  input CLR;
  wire CLR;
  (* src = "utils.v:34.25-34.27" *)
  output CO;
  wire CO;
  (* init = 10'h000 *)
  (* src = "utils.v:33.25-33.26" *)
  output [9:0] Q;
  wire [9:0] Q;
  iv1v0x05 _30_ (
    .a(CLR),
    .z(_10_)
  );
  an3v0x05 _31_ (
    .a(Q[2]),
    .b(Q[1]),
    .c(Q[0]),
    .z(_11_)
  );
  an3v0x05 _32_ (
    .a(CE),
    .b(Q[4]),
    .c(Q[3]),
    .z(_12_)
  );
  an2v0x05 _33_ (
    .a(Q[9]),
    .b(Q[8]),
    .z(_13_)
  );
  nr3v0x05 _34_ (
    .a(Q[7]),
    .b(Q[6]),
    .c(Q[5]),
    .z(_14_)
  );
  an4v0x05 _35_ (
    .a(_11_),
    .b(_12_),
    .c(_13_),
    .d(_14_),
    .z(CO)
  );
  oai21v0x05 _36_ (
    .a1(CE),
    .a2(Q[0]),
    .b(_10_),
    .z(_15_)
  );
  aoi21v0x05 _37_ (
    .a1(CE),
    .a2(Q[0]),
    .b(_15_),
    .z(_00_)
  );
  nd3v0x05 _38_ (
    .a(CE),
    .b(Q[1]),
    .c(Q[0]),
    .z(_16_)
  );
  aoi21v0x05 _39_ (
    .a1(CE),
    .a2(Q[0]),
    .b(Q[1]),
    .z(_17_)
  );
  nr3abv0x05 _40_ (
    .a(_10_),
    .b(_16_),
    .c(_17_),
    .z(_01_)
  );
  xor2v0x05 _41_ (
    .a(Q[2]),
    .b(_16_),
    .z(_18_)
  );
  nr2v0x05 _42_ (
    .a(CLR),
    .b(_18_),
    .z(_02_)
  );
  nd3v0x05 _43_ (
    .a(CE),
    .b(Q[3]),
    .c(_11_),
    .z(_19_)
  );
  aoi21v0x05 _44_ (
    .a1(CE),
    .a2(_11_),
    .b(Q[3]),
    .z(_20_)
  );
  nr3abv0x05 _45_ (
    .a(_10_),
    .b(_19_),
    .c(_20_),
    .z(_03_)
  );
  xor2v0x05 _46_ (
    .a(Q[4]),
    .b(_19_),
    .z(_21_)
  );
  nr2v0x05 _47_ (
    .a(CLR),
    .b(_21_),
    .z(_04_)
  );
  or2v0x05 _48_ (
    .a(CLR),
    .b(CO),
    .z(_22_)
  );
  xaoi21v0x05 _49_ (
    .a1(_11_),
    .a2(_12_),
    .b(Q[5]),
    .z(_23_)
  );
  nr2v0x05 _50_ (
    .a(_22_),
    .b(_23_),
    .z(_05_)
  );
  an4v0x05 _51_ (
    .a(Q[6]),
    .b(Q[5]),
    .c(_11_),
    .d(_12_),
    .z(_24_)
  );
  aoi31v0x05 _52_ (
    .a1(Q[5]),
    .a2(_11_),
    .a3(_12_),
    .b(Q[6]),
    .z(_25_)
  );
  nr3v0x05 _53_ (
    .a(CLR),
    .b(_24_),
    .c(_25_),
    .z(_06_)
  );
  oai21v0x05 _54_ (
    .a1(Q[7]),
    .a2(_24_),
    .b(_10_),
    .z(_26_)
  );
  aoi21v0x05 _55_ (
    .a1(Q[7]),
    .a2(_24_),
    .b(_26_),
    .z(_07_)
  );
  xaoi21v0x05 _56_ (
    .a1(Q[7]),
    .a2(_24_),
    .b(Q[8]),
    .z(_27_)
  );
  nr2v0x05 _57_ (
    .a(_22_),
    .b(_27_),
    .z(_08_)
  );
  an4v0x05 _58_ (
    .a(Q[9]),
    .b(Q[8]),
    .c(Q[7]),
    .d(_24_),
    .z(_28_)
  );
  aoi31v0x05 _59_ (
    .a1(Q[8]),
    .a2(Q[7]),
    .a3(_24_),
    .b(Q[9]),
    .z(_29_)
  );
  nr3v0x05 _60_ (
    .a(_22_),
    .b(_28_),
    .c(_29_),
    .z(_09_)
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _61_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _62_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _63_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _64_ (
    .cp(CLK),
    .d(_03_),
    .z(Q[3])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _65_ (
    .cp(CLK),
    .d(_04_),
    .z(Q[4])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _66_ (
    .cp(CLK),
    .d(_05_),
    .z(Q[5])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _67_ (
    .cp(CLK),
    .d(_06_),
    .z(Q[6])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _68_ (
    .cp(CLK),
    .d(_07_),
    .z(Q[7])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _69_ (
    .cp(CLK),
    .d(_08_),
    .z(Q[8])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _70_ (
    .cp(CLK),
    .d(_09_),
    .z(Q[9])
  );
endmodule

(* src = "img_src.v:1.1-46.10" *)
module img_src(CLK, CE, PIX, LINE, R, G, B);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "img_src.v:8.19-8.20" *)
  output [1:0] B;
  wire [1:0] B;
  (* src = "img_src.v:3.8-3.10" *)
  input CE;
  wire CE;
  (* src = "img_src.v:2.8-2.11" *)
  input CLK;
  wire CLK;
  (* src = "img_src.v:7.19-7.20" *)
  output [2:0] G;
  wire [2:0] G;
  (* src = "img_src.v:5.14-5.18" *)
  input [9:0] LINE;
  wire [9:0] LINE;
  (* src = "img_src.v:4.14-4.17" *)
  input [9:0] PIX;
  wire [9:0] PIX;
  (* src = "img_src.v:6.19-6.20" *)
  output [2:0] R;
  wire [2:0] R;
  iv1v0x05 _13_ (
    .a(CE),
    .z(_03_)
  );
  aoi21v0x05 _14_ (
    .a1(PIX[7]),
    .a2(PIX[8]),
    .b(PIX[9]),
    .z(_04_)
  );
  oan21v0x05 _15_ (
    .a1(PIX[7]),
    .a2(PIX[8]),
    .b(PIX[9]),
    .z(_05_)
  );
  nd2av0x05 _16_ (
    .a(CE),
    .b(B[0]),
    .z(_06_)
  );
  oai31v0x05 _17_ (
    .a1(_03_),
    .a2(_04_),
    .a3(_05_),
    .b(_06_),
    .z(_00_)
  );
  cgi2v0x05 _18_ (
    .a(PIX[7]),
    .b(PIX[9]),
    .c(PIX[8]),
    .z(_07_)
  );
  oai21v0x05 _19_ (
    .a1(PIX[9]),
    .a2(PIX[8]),
    .b(CE),
    .z(_08_)
  );
  nd2av0x05 _20_ (
    .a(CE),
    .b(G[1]),
    .z(_09_)
  );
  oai21a2v0x05 _21_ (
    .a1(_08_),
    .a2(_07_),
    .b(_09_),
    .z(_01_)
  );
  aon21v0x05 _22_ (
    .a1(PIX[7]),
    .a2(PIX[9]),
    .b(PIX[8]),
    .z(_10_)
  );
  oai21v0x05 _23_ (
    .a1(PIX[7]),
    .a2(PIX[9]),
    .b(CE),
    .z(_11_)
  );
  nd2av0x05 _24_ (
    .a(CE),
    .b(R[1]),
    .z(_12_)
  );
  oai21v0x05 _25_ (
    .a1(_10_),
    .a2(_11_),
    .b(_12_),
    .z(_02_)
  );
  (* src = "img_src.v:12.1-43.6" *)
  dfnt1v0x2 _26_ (
    .cp(CLK),
    .d(_00_),
    .z(B[0])
  );
  (* src = "img_src.v:12.1-43.6" *)
  dfnt1v0x2 _27_ (
    .cp(CLK),
    .d(_01_),
    .z(G[1])
  );
  (* src = "img_src.v:12.1-43.6" *)
  dfnt1v0x2 _28_ (
    .cp(CLK),
    .d(_02_),
    .z(R[1])
  );
  assign B[1] = B[0];
  assign { G[2], G[0] } = { G[1], G[1] };
  assign { R[2], R[0] } = { R[1], R[1] };
endmodule

(* dynports =  1  *)
(* src = "utils.v:1.1-23.10" *)
module prescaler(CLK, CE, CEO);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "utils.v:8.11-8.13" *)
  input CE;
  wire CE;
  (* src = "utils.v:9.12-9.15" *)
  output CEO;
  wire CEO;
  (* src = "utils.v:7.11-7.14" *)
  input CLK;
  wire CLK;
  (* init = 27'h0000000 *)
  (* src = "utils.v:12.13-12.14" *)
  wire [26:0] Q;
  iv1v0x05 _072_ (
    .a(Q[25]),
    .z(_044_)
  );
  iv1v0x05 _073_ (
    .a(Q[24]),
    .z(_045_)
  );
  an4v0x05 _074_ (
    .a(Q[0]),
    .b(Q[1]),
    .c(Q[3]),
    .d(Q[2]),
    .z(_046_)
  );
  nd3v0x05 _075_ (
    .a(Q[5]),
    .b(Q[4]),
    .c(Q[6]),
    .z(_047_)
  );
  nr3abv0x05 _076_ (
    .a(Q[7]),
    .b(_046_),
    .c(_047_),
    .z(_048_)
  );
  nr4v1x05 _077_ (
    .a(Q[9]),
    .b(Q[8]),
    .c(Q[11]),
    .d(Q[10]),
    .z(_049_)
  );
  an2v0x05 _078_ (
    .a(Q[15]),
    .b(Q[14]),
    .z(_050_)
  );
  nr3abv0x05 _079_ (
    .a(Q[16]),
    .b(_050_),
    .c(Q[17]),
    .z(_051_)
  );
  nd2v0x05 _080_ (
    .a(Q[20]),
    .b(Q[21]),
    .z(_052_)
  );
  nd4v0x05 _081_ (
    .a(Q[20]),
    .b(Q[21]),
    .c(Q[23]),
    .d(Q[22]),
    .z(_053_)
  );
  nd4v0x05 _082_ (
    .a(_044_),
    .b(Q[24]),
    .c(Q[26]),
    .d(CE),
    .z(_054_)
  );
  nd2av0x05 _083_ (
    .a(Q[19]),
    .b(Q[18]),
    .z(_055_)
  );
  nd3abv0x05 _084_ (
    .a(Q[12]),
    .b(_055_),
    .c(Q[13]),
    .z(_056_)
  );
  nr3v0x05 _085_ (
    .a(_053_),
    .b(_054_),
    .c(_056_),
    .z(_057_)
  );
  nd4v0x05 _086_ (
    .a(_048_),
    .b(_049_),
    .c(_051_),
    .d(_057_),
    .z(_058_)
  );
  iv1v0x05 _087_ (
    .a(_058_),
    .z(CEO)
  );
  xor2v0x05 _088_ (
    .a(Q[0]),
    .b(CE),
    .z(_000_)
  );
  xaon21v0x05 _089_ (
    .a1(Q[0]),
    .a2(CE),
    .b(Q[1]),
    .z(_001_)
  );
  aoi31v0x05 _090_ (
    .a1(Q[0]),
    .a2(Q[1]),
    .a3(CE),
    .b(Q[2]),
    .z(_059_)
  );
  an4v0x05 _091_ (
    .a(Q[0]),
    .b(Q[1]),
    .c(Q[2]),
    .d(CE),
    .z(_060_)
  );
  nr2v0x05 _092_ (
    .a(_059_),
    .b(_060_),
    .z(_002_)
  );
  nd2v0x05 _093_ (
    .a(Q[3]),
    .b(_060_),
    .z(_061_)
  );
  xor2v0x05 _094_ (
    .a(Q[3]),
    .b(_060_),
    .z(_003_)
  );
  xnr2v0x05 _095_ (
    .a(Q[4]),
    .b(_061_),
    .z(_004_)
  );
  aoi31v0x05 _096_ (
    .a1(Q[3]),
    .a2(Q[4]),
    .a3(_060_),
    .b(Q[5]),
    .z(_062_)
  );
  nr3abv0x05 _097_ (
    .a(Q[5]),
    .b(Q[4]),
    .c(_061_),
    .z(_063_)
  );
  nr2v0x05 _098_ (
    .a(_062_),
    .b(_063_),
    .z(_005_)
  );
  xor2v0x05 _099_ (
    .a(Q[6]),
    .b(_063_),
    .z(_006_)
  );
  xaon21v0x05 _100_ (
    .a1(Q[6]),
    .a2(_063_),
    .b(Q[7]),
    .z(_007_)
  );
  an3v0x05 _101_ (
    .a(Q[8]),
    .b(CE),
    .c(_048_),
    .z(_064_)
  );
  aoi21v0x05 _102_ (
    .a1(CE),
    .a2(_048_),
    .b(Q[8]),
    .z(_065_)
  );
  nr3v0x05 _103_ (
    .a(CEO),
    .b(_064_),
    .c(_065_),
    .z(_008_)
  );
  an4v0x05 _104_ (
    .a(Q[9]),
    .b(Q[8]),
    .c(CE),
    .d(_048_),
    .z(_066_)
  );
  oan21bv0x05 _105_ (
    .a1(Q[9]),
    .a2(_064_),
    .b(_066_),
    .z(_009_)
  );
  xor2v0x05 _106_ (
    .a(Q[10]),
    .b(_066_),
    .z(_010_)
  );
  nd3v0x05 _107_ (
    .a(Q[11]),
    .b(Q[10]),
    .c(CE),
    .z(_067_)
  );
  nr3abv0x05 _108_ (
    .a(Q[9]),
    .b(Q[8]),
    .c(_067_),
    .z(_068_)
  );
  xaon21v0x05 _109_ (
    .a1(Q[10]),
    .a2(_066_),
    .b(Q[11]),
    .z(_011_)
  );
  xaon21v0x05 _110_ (
    .a1(_048_),
    .a2(_068_),
    .b(Q[12]),
    .z(_012_)
  );
  nd4v0x05 _111_ (
    .a(Q[13]),
    .b(Q[12]),
    .c(_048_),
    .d(_068_),
    .z(_069_)
  );
  aoi31v0x05 _112_ (
    .a1(Q[12]),
    .a2(_048_),
    .a3(_068_),
    .b(Q[13]),
    .z(_070_)
  );
  nr3abv0x05 _113_ (
    .a(_058_),
    .b(_069_),
    .c(_070_),
    .z(_013_)
  );
  xnai21v2x05 _114_ (
    .a1(Q[14]),
    .a2(_069_),
    .b(_058_),
    .z(_071_)
  );
  iv1v0x05 _115_ (
    .a(_071_),
    .z(_014_)
  );
  nr3abv0x05 _116_ (
    .a(Q[15]),
    .b(Q[14]),
    .c(_069_),
    .z(_027_)
  );
  aoi21a2v0x05 _117_ (
    .a1(Q[14]),
    .a2(_069_),
    .b(Q[15]),
    .z(_028_)
  );
  nr3v0x05 _118_ (
    .a(CEO),
    .b(_027_),
    .c(_028_),
    .z(_015_)
  );
  oai21v0x05 _119_ (
    .a1(Q[16]),
    .a2(_027_),
    .b(_058_),
    .z(_029_)
  );
  aoi21v0x05 _120_ (
    .a1(Q[16]),
    .a2(_027_),
    .b(_029_),
    .z(_016_)
  );
  xaon21v0x05 _121_ (
    .a1(Q[16]),
    .a2(_027_),
    .b(Q[17]),
    .z(_017_)
  );
  an2v0x05 _122_ (
    .a(Q[16]),
    .b(Q[17]),
    .z(_030_)
  );
  nd3v0x05 _123_ (
    .a(Q[18]),
    .b(_027_),
    .c(_030_),
    .z(_031_)
  );
  aoi21v0x05 _124_ (
    .a1(_027_),
    .a2(_030_),
    .b(Q[18]),
    .z(_032_)
  );
  nr3abv0x05 _125_ (
    .a(_058_),
    .b(_031_),
    .c(_032_),
    .z(_018_)
  );
  nd4v0x05 _126_ (
    .a(Q[19]),
    .b(Q[18]),
    .c(_050_),
    .d(_030_),
    .z(_033_)
  );
  nr2v0x05 _127_ (
    .a(_069_),
    .b(_033_),
    .z(_034_)
  );
  xnr2v0x05 _128_ (
    .a(Q[19]),
    .b(_031_),
    .z(_019_)
  );
  oai21v0x05 _129_ (
    .a1(Q[20]),
    .a2(_034_),
    .b(_058_),
    .z(_035_)
  );
  aoi21v0x05 _130_ (
    .a1(Q[20]),
    .a2(_034_),
    .b(_035_),
    .z(_020_)
  );
  aoi21v0x05 _131_ (
    .a1(Q[20]),
    .a2(_034_),
    .b(Q[21]),
    .z(_036_)
  );
  nr3v0x05 _132_ (
    .a(_052_),
    .b(_069_),
    .c(_033_),
    .z(_037_)
  );
  nr3v0x05 _133_ (
    .a(CEO),
    .b(_036_),
    .c(_037_),
    .z(_021_)
  );
  oai21v0x05 _134_ (
    .a1(Q[22]),
    .a2(_037_),
    .b(_058_),
    .z(_038_)
  );
  aoi21v0x05 _135_ (
    .a1(Q[22]),
    .a2(_037_),
    .b(_038_),
    .z(_022_)
  );
  aoi21v0x05 _136_ (
    .a1(Q[22]),
    .a2(_037_),
    .b(Q[23]),
    .z(_039_)
  );
  nr3v0x05 _137_ (
    .a(_053_),
    .b(_069_),
    .c(_033_),
    .z(_040_)
  );
  nr3v0x05 _138_ (
    .a(CEO),
    .b(_039_),
    .c(_040_),
    .z(_023_)
  );
  or4v0x05 _139_ (
    .a(_045_),
    .b(_053_),
    .c(_069_),
    .d(_033_),
    .z(_041_)
  );
  nr2v0x05 _140_ (
    .a(Q[24]),
    .b(_040_),
    .z(_042_)
  );
  nr3abv0x05 _141_ (
    .a(_058_),
    .b(_041_),
    .c(_042_),
    .z(_024_)
  );
  xnr2v0x05 _142_ (
    .a(Q[25]),
    .b(_041_),
    .z(_025_)
  );
  xoon21v0x05 _143_ (
    .a1(_044_),
    .a2(_041_),
    .b(Q[26]),
    .z(_043_)
  );
  nr2v0x05 _144_ (
    .a(CEO),
    .b(_043_),
    .z(_026_)
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _145_ (
    .cp(CLK),
    .d(_000_),
    .z(Q[0])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _146_ (
    .cp(CLK),
    .d(_001_),
    .z(Q[1])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _147_ (
    .cp(CLK),
    .d(_002_),
    .z(Q[2])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _148_ (
    .cp(CLK),
    .d(_003_),
    .z(Q[3])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _149_ (
    .cp(CLK),
    .d(_004_),
    .z(Q[4])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _150_ (
    .cp(CLK),
    .d(_005_),
    .z(Q[5])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _151_ (
    .cp(CLK),
    .d(_006_),
    .z(Q[6])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _152_ (
    .cp(CLK),
    .d(_007_),
    .z(Q[7])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _153_ (
    .cp(CLK),
    .d(_008_),
    .z(Q[8])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _154_ (
    .cp(CLK),
    .d(_009_),
    .z(Q[9])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _155_ (
    .cp(CLK),
    .d(_010_),
    .z(Q[10])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _156_ (
    .cp(CLK),
    .d(_011_),
    .z(Q[11])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _157_ (
    .cp(CLK),
    .d(_012_),
    .z(Q[12])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _158_ (
    .cp(CLK),
    .d(_013_),
    .z(Q[13])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _159_ (
    .cp(CLK),
    .d(_014_),
    .z(Q[14])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _160_ (
    .cp(CLK),
    .d(_015_),
    .z(Q[15])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _161_ (
    .cp(CLK),
    .d(_016_),
    .z(Q[16])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _162_ (
    .cp(CLK),
    .d(_017_),
    .z(Q[17])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _163_ (
    .cp(CLK),
    .d(_018_),
    .z(Q[18])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _164_ (
    .cp(CLK),
    .d(_019_),
    .z(Q[19])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _165_ (
    .cp(CLK),
    .d(_020_),
    .z(Q[20])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _166_ (
    .cp(CLK),
    .d(_021_),
    .z(Q[21])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _167_ (
    .cp(CLK),
    .d(_022_),
    .z(Q[22])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _168_ (
    .cp(CLK),
    .d(_023_),
    .z(Q[23])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _169_ (
    .cp(CLK),
    .d(_024_),
    .z(Q[24])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _170_ (
    .cp(CLK),
    .d(_025_),
    .z(Q[25])
  );
  (* src = "utils.v:14.1-19.22" *)
  dfnt1v0x2 _171_ (
    .cp(CLK),
    .d(_026_),
    .z(Q[26])
  );
endmodule

(* dynports =  1  *)
(* src = "utils.v:74.1-88.10" *)
module register(CLK, CE, D, Q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "utils.v:79.25-79.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:78.25-78.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:80.25-80.26" *)
  input [7:0] D;
  wire [7:0] D;
  (* init = 8'h00 *)
  (* src = "utils.v:81.25-81.26" *)
  output [7:0] Q;
  wire [7:0] Q;
  mxn2v0x05 _08_ (
    .a0(Q[0]),
    .a1(D[0]),
    .s(CE),
    .z(_00_)
  );
  mxn2v0x05 _09_ (
    .a0(Q[1]),
    .a1(D[1]),
    .s(CE),
    .z(_01_)
  );
  mxn2v0x05 _10_ (
    .a0(Q[2]),
    .a1(D[2]),
    .s(CE),
    .z(_02_)
  );
  mxn2v0x05 _11_ (
    .a0(Q[3]),
    .a1(D[3]),
    .s(CE),
    .z(_03_)
  );
  mxn2v0x05 _12_ (
    .a0(Q[4]),
    .a1(D[4]),
    .s(CE),
    .z(_04_)
  );
  mxn2v0x05 _13_ (
    .a0(Q[5]),
    .a1(D[5]),
    .s(CE),
    .z(_05_)
  );
  mxn2v0x05 _14_ (
    .a0(Q[6]),
    .a1(D[6]),
    .s(CE),
    .z(_06_)
  );
  mxn2v0x05 _15_ (
    .a0(Q[7]),
    .a1(D[7]),
    .s(CE),
    .z(_07_)
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _16_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _17_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _18_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _19_ (
    .cp(CLK),
    .d(_03_),
    .z(Q[3])
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _20_ (
    .cp(CLK),
    .d(_04_),
    .z(Q[4])
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _21_ (
    .cp(CLK),
    .d(_05_),
    .z(Q[5])
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _22_ (
    .cp(CLK),
    .d(_06_),
    .z(Q[6])
  );
  (* src = "utils.v:84.1-86.16" *)
  dfnt1v0x2 _23_ (
    .cp(CLK),
    .d(_07_),
    .z(Q[7])
  );
endmodule

(* dynports =  1  *)
(* src = "utils.v:50.1-72.10" *)
module shift_reg(CLK, CE, CLR, DIR, D, Q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "utils.v:55.25-55.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:54.25-54.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:56.25-56.28" *)
  input CLR;
  wire CLR;
  (* src = "utils.v:58.25-58.26" *)
  input D;
  wire D;
  (* src = "utils.v:57.25-57.28" *)
  input DIR;
  wire DIR;
  (* src = "utils.v:59.25-59.26" *)
  output [7:0] Q;
  wire [7:0] Q;
  mxi2v0x05 _24_ (
    .a0(D),
    .a1(Q[1]),
    .s(DIR),
    .z(_08_)
  );
  nr2v0x05 _25_ (
    .a(CE),
    .b(Q[0]),
    .z(_09_)
  );
  aoi112v0x05 _26_ (
    .a(CLR),
    .b(_09_),
    .c1(_08_),
    .c2(CE),
    .z(_00_)
  );
  mxi2v0x05 _27_ (
    .a0(Q[0]),
    .a1(Q[2]),
    .s(DIR),
    .z(_10_)
  );
  nr2v0x05 _28_ (
    .a(CE),
    .b(Q[1]),
    .z(_11_)
  );
  aoi112v0x05 _29_ (
    .a(CLR),
    .b(_11_),
    .c1(_10_),
    .c2(CE),
    .z(_01_)
  );
  mxi2v0x05 _30_ (
    .a0(Q[1]),
    .a1(Q[3]),
    .s(DIR),
    .z(_12_)
  );
  nr2v0x05 _31_ (
    .a(CE),
    .b(Q[2]),
    .z(_13_)
  );
  aoi112v0x05 _32_ (
    .a(CLR),
    .b(_13_),
    .c1(_12_),
    .c2(CE),
    .z(_02_)
  );
  mxi2v0x05 _33_ (
    .a0(Q[2]),
    .a1(Q[4]),
    .s(DIR),
    .z(_14_)
  );
  nr2v0x05 _34_ (
    .a(CE),
    .b(Q[3]),
    .z(_15_)
  );
  aoi112v0x05 _35_ (
    .a(CLR),
    .b(_15_),
    .c1(_14_),
    .c2(CE),
    .z(_03_)
  );
  mxi2v0x05 _36_ (
    .a0(Q[3]),
    .a1(Q[5]),
    .s(DIR),
    .z(_16_)
  );
  nr2v0x05 _37_ (
    .a(CE),
    .b(Q[4]),
    .z(_17_)
  );
  aoi112v0x05 _38_ (
    .a(CLR),
    .b(_17_),
    .c1(_16_),
    .c2(CE),
    .z(_04_)
  );
  mxi2v0x05 _39_ (
    .a0(Q[4]),
    .a1(Q[6]),
    .s(DIR),
    .z(_18_)
  );
  nr2v0x05 _40_ (
    .a(CE),
    .b(Q[5]),
    .z(_19_)
  );
  aoi112v0x05 _41_ (
    .a(CLR),
    .b(_19_),
    .c1(_18_),
    .c2(CE),
    .z(_05_)
  );
  mxi2v0x05 _42_ (
    .a0(Q[5]),
    .a1(Q[7]),
    .s(DIR),
    .z(_20_)
  );
  nr2v0x05 _43_ (
    .a(CE),
    .b(Q[6]),
    .z(_21_)
  );
  aoi112v0x05 _44_ (
    .a(CLR),
    .b(_21_),
    .c1(_20_),
    .c2(CE),
    .z(_06_)
  );
  mxi2v0x05 _45_ (
    .a0(Q[6]),
    .a1(D),
    .s(DIR),
    .z(_22_)
  );
  nr2v0x05 _46_ (
    .a(Q[7]),
    .b(CE),
    .z(_23_)
  );
  aoi112v0x05 _47_ (
    .a(CLR),
    .b(_23_),
    .c1(_22_),
    .c2(CE),
    .z(_07_)
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _48_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _49_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _50_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _51_ (
    .cp(CLK),
    .d(_03_),
    .z(Q[3])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _52_ (
    .cp(CLK),
    .d(_04_),
    .z(Q[4])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _53_ (
    .cp(CLK),
    .d(_05_),
    .z(Q[5])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _54_ (
    .cp(CLK),
    .d(_06_),
    .z(Q[6])
  );
  (* src = "utils.v:62.1-69.29" *)
  dfnt1v0x2 _55_ (
    .cp(CLK),
    .d(_07_),
    .z(Q[7])
  );
endmodule

(* src = "uart_fsm.v:2.1-65.10" *)
module uart_fsm(CLK, CLR, CE, DI, HB, BD, LB, STATUS);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "uart_fsm.v:8.18-8.20" *)
  input BD;
  wire BD;
  (* src = "uart_fsm.v:5.11-5.13" *)
  input CE;
  wire CE;
  (* src = "uart_fsm.v:3.14-3.17" *)
  input CLK;
  wire CLK;
  (* src = "uart_fsm.v:4.11-4.14" *)
  input CLR;
  wire CLR;
  (* src = "uart_fsm.v:6.11-6.13" *)
  input DI;
  wire DI;
  (* src = "uart_fsm.v:7.18-7.20" *)
  input HB;
  wire HB;
  (* src = "uart_fsm.v:9.18-9.20" *)
  input LB;
  wire LB;
  (* src = "uart_fsm.v:10.17-10.23" *)
  output [2:0] STATUS;
  wire [2:0] STATUS;
  (* init = 3'h0 *)
  (* src = "uart_fsm.v:20.15-20.20" *)
  wire [2:0] state;
  iv1v0x05 _20_ (
    .a(LB),
    .z(_03_)
  );
  nr2v0x05 _21_ (
    .a(state[1]),
    .b(state[0]),
    .z(_04_)
  );
  nd3abv0x05 _22_ (
    .a(state[1]),
    .b(state[0]),
    .c(state[2]),
    .z(_05_)
  );
  oan21bv0x05 _23_ (
    .a1(state[2]),
    .a2(_04_),
    .b(DI),
    .z(_06_)
  );
  nd2av0x05 _24_ (
    .a(state[2]),
    .b(state[1]),
    .z(_07_)
  );
  nd3av0x05 _25_ (
    .a(state[2]),
    .b(state[1]),
    .c(state[0]),
    .z(_08_)
  );
  or2v0x05 _26_ (
    .a(state[0]),
    .b(DI),
    .z(_09_)
  );
  oai22v0x05 _27_ (
    .a1(LB),
    .a2(_08_),
    .b1(_09_),
    .b2(_07_),
    .z(_10_)
  );
  aoi21a2bv0x05 _28_ (
    .a1(state[2]),
    .a2(_04_),
    .b(CE),
    .z(_11_)
  );
  nd3abv0x05 _29_ (
    .a(state[2]),
    .b(state[1]),
    .c(state[0]),
    .z(_12_)
  );
  nr2v0x05 _30_ (
    .a(HB),
    .b(_12_),
    .z(_13_)
  );
  aoi112v0x05 _31_ (
    .a(_10_),
    .b(_13_),
    .c1(_05_),
    .c2(_06_),
    .z(_14_)
  );
  nr2v0x05 _32_ (
    .a(state[0]),
    .b(_11_),
    .z(_15_)
  );
  aoi112v0x05 _33_ (
    .a(CLR),
    .b(_15_),
    .c1(_14_),
    .c2(_11_),
    .z(_00_)
  );
  aoi21a2v0x05 _34_ (
    .a1(HB),
    .a2(_12_),
    .b(_10_),
    .z(_16_)
  );
  nr2v0x05 _35_ (
    .a(state[1]),
    .b(_11_),
    .z(_17_)
  );
  aoi112v0x05 _36_ (
    .a(CLR),
    .b(_17_),
    .c1(_16_),
    .c2(_11_),
    .z(_01_)
  );
  oai22v0x05 _37_ (
    .a1(BD),
    .a2(_05_),
    .b1(_08_),
    .b2(_03_),
    .z(_18_)
  );
  mxi2v0x05 _38_ (
    .a0(state[2]),
    .a1(_18_),
    .s(_11_),
    .z(_19_)
  );
  nr2v0x05 _39_ (
    .a(CLR),
    .b(_19_),
    .z(_02_)
  );
  (* src = "uart_fsm.v:23.5-63.8" *)
  dfnt1v0x2 _40_ (
    .cp(CLK),
    .d(_00_),
    .z(state[0])
  );
  (* src = "uart_fsm.v:23.5-63.8" *)
  dfnt1v0x2 _41_ (
    .cp(CLK),
    .d(_01_),
    .z(state[1])
  );
  (* src = "uart_fsm.v:23.5-63.8" *)
  dfnt1v0x2 _42_ (
    .cp(CLK),
    .d(_02_),
    .z(state[2])
  );
  assign STATUS = state;
endmodule

(* dynports =  1  *)
(* src = "uart_rx.v:2.1-89.10" *)
module uart_rx(CLK, CE, RST, DI, DV, PO);
  (* src = "uart_rx.v:43.10-43.31" *)
  wire _00_;
  (* src = "uart_rx.v:31.49-31.63" *)
  wire _01_;
  (* src = "uart_rx.v:58.9-58.20" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "uart_rx.v:25.10-25.12" *)
  wire BD;
  (* src = "uart_rx.v:8.21-8.23" *)
  input CE;
  wire CE;
  (* src = "uart_rx.v:7.21-7.24" *)
  input CLK;
  wire CLK;
  (* src = "uart_rx.v:10.21-10.23" *)
  input DI;
  wire DI;
  (* src = "uart_rx.v:11.21-11.23" *)
  output DV;
  wire DV;
  (* src = "uart_rx.v:25.6-25.8" *)
  wire HB;
  (* src = "uart_rx.v:25.14-25.16" *)
  wire LB;
  (* src = "uart_rx.v:12.21-12.23" *)
  output [7:0] PO;
  wire [7:0] PO;
  (* src = "uart_rx.v:9.21-9.24" *)
  input RST;
  wire RST;
  (* src = "uart_rx.v:23.27-23.35" *)
  wire [11:0] baud_cnt;
  (* src = "uart_rx.v:26.6-26.16" *)
  wire baud_reset;
  (* unused_bits = "0 1 2" *)
  wire [2:0] bit_cnt;
  (* src = "uart_rx.v:27.5-27.9" *)
  wire data;
  (* src = "uart_rx.v:22.12-22.18" *)
  wire [2:0] status;
  iv1v0x05 _16_ (
    .a(status[0]),
    .z(_03_)
  );
  iv1v0x05 _17_ (
    .a(status[2]),
    .z(_04_)
  );
  nr2av0x1 _18_ (
    .a(baud_cnt[10]),
    .b(baud_cnt[11]),
    .z(_05_)
  );
  nd2av0x05 _19_ (
    .a(baud_cnt[8]),
    .b(baud_cnt[9]),
    .z(_06_)
  );
  nd4v0x05 _20_ (
    .a(baud_cnt[3]),
    .b(baud_cnt[2]),
    .c(baud_cnt[5]),
    .d(baud_cnt[4]),
    .z(_07_)
  );
  nr4v1x05 _21_ (
    .a(baud_cnt[7]),
    .b(baud_cnt[6]),
    .c(_06_),
    .d(_07_),
    .z(_08_)
  );
  an4v0x05 _22_ (
    .a(baud_cnt[1]),
    .b(baud_cnt[0]),
    .c(_05_),
    .d(_08_),
    .z(HB)
  );
  nr3v0x05 _23_ (
    .a(status[1]),
    .b(status[0]),
    .c(status[2]),
    .z(_01_)
  );
  nd3av0x05 _24_ (
    .a(baud_cnt[11]),
    .b(baud_cnt[10]),
    .c(baud_cnt[1]),
    .z(_09_)
  );
  nd3abv0x05 _25_ (
    .a(baud_cnt[7]),
    .b(baud_cnt[6]),
    .c(baud_cnt[0]),
    .z(_10_)
  );
  nd3av0x05 _26_ (
    .a(baud_cnt[8]),
    .b(baud_cnt[9]),
    .c(baud_cnt[3]),
    .z(_11_)
  );
  nd3v0x05 _27_ (
    .a(baud_cnt[2]),
    .b(baud_cnt[5]),
    .c(baud_cnt[4]),
    .z(_12_)
  );
  nr4v1x05 _28_ (
    .a(_09_),
    .b(_10_),
    .c(_11_),
    .d(_12_),
    .z(_13_)
  );
  nr2v0x05 _29_ (
    .a(status[1]),
    .b(status[2]),
    .z(_14_)
  );
  oan21v0x05 _30_ (
    .a1(_03_),
    .a2(_13_),
    .b(_14_),
    .z(baud_reset)
  );
  oai21v0x05 _31_ (
    .a1(_03_),
    .a2(_13_),
    .b(_14_),
    .z(_02_)
  );
  nd3v0x05 _32_ (
    .a(status[2]),
    .b(BD),
    .c(data),
    .z(_15_)
  );
  nr3v0x05 _33_ (
    .a(status[1]),
    .b(status[0]),
    .c(_15_),
    .z(DV)
  );
  an4v0x05 _34_ (
    .a(status[1]),
    .b(status[0]),
    .c(_04_),
    .d(BD),
    .z(_00_)
  );
  (* src = "uart_rx.v:34.1-35.16" *)
  dfnt1v0x2 _35_ (
    .cp(CLK),
    .d(DI),
    .z(data)
  );
  (* src = "uart_rx.v:55.1-62.2" *)
  \$paramod$a8e0632467158ddaf1a03dbaacb5062349325662\up_cnt_mod  baud_counter (
    .CE(_02_),
    .CLK(CLK),
    .CLR(baud_reset),
    .CO(BD),
    .Q(baud_cnt)
  );
  (* src = "uart_rx.v:68.1-75.2" *)
  \$paramod$bd56cd18463522cf742d73406a4024be0afccdd0\up_cnt_mod  bit_counter (
    .CE(_00_),
    .CLK(CLK),
    .CLR(_01_),
    .CO(LB),
    .Q(bit_cnt)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "uart_rx.v:78.10-87.2" *)
  uart_fsm fsm (
    .BD(BD),
    .CE(CE),
    .CLK(CLK),
    .CLR(RST),
    .DI(data),
    .HB(HB),
    .LB(LB),
    .STATUS(status)
  );
  (* src = "uart_rx.v:40.1-48.2" *)
  \$paramod\shift_reg\W=s32'00000000000000000000000000001000  out_reg (
    .CE(_00_),
    .CLK(CLK),
    .CLR(RST),
    .D(data),
    .DIR(1'h1),
    .Q(PO)
  );
endmodule

(* dynports =  1  *)
(* src = "utils.v:25.1-48.10" *)
module up_cnt_mod(CLK, CE, CLR, Q, CO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "utils.v:31.25-31.27" *)
  input CE;
  wire CE;
  (* src = "utils.v:30.25-30.28" *)
  input CLK;
  wire CLK;
  (* src = "utils.v:32.25-32.28" *)
  input CLR;
  wire CLR;
  (* src = "utils.v:34.25-34.27" *)
  output CO;
  wire CO;
  (* init = 4'h0 *)
  (* src = "utils.v:33.25-33.26" *)
  output [3:0] Q;
  wire [3:0] Q;
  nd2av0x05 _13_ (
    .a(Q[2]),
    .b(Q[3]),
    .z(_04_)
  );
  nd2v0x05 _14_ (
    .a(CE),
    .b(Q[0]),
    .z(_05_)
  );
  nr3v0x05 _15_ (
    .a(Q[1]),
    .b(_04_),
    .c(_05_),
    .z(CO)
  );
  xnr2v0x05 _16_ (
    .a(CE),
    .b(Q[0]),
    .z(_06_)
  );
  nr2v0x05 _17_ (
    .a(CLR),
    .b(_06_),
    .z(_00_)
  );
  nd2v0x05 _18_ (
    .a(Q[1]),
    .b(_05_),
    .z(_07_)
  );
  nd3abv0x05 _19_ (
    .a(Q[1]),
    .b(_05_),
    .c(_04_),
    .z(_08_)
  );
  aoi21v0x05 _20_ (
    .a1(_07_),
    .a2(_08_),
    .b(CLR),
    .z(_01_)
  );
  an4v0x05 _21_ (
    .a(CE),
    .b(Q[2]),
    .c(Q[1]),
    .d(Q[0]),
    .z(_09_)
  );
  aoi31v0x05 _22_ (
    .a1(CE),
    .a2(Q[1]),
    .a3(Q[0]),
    .b(Q[2]),
    .z(_10_)
  );
  nr3v0x05 _23_ (
    .a(CLR),
    .b(_09_),
    .c(_10_),
    .z(_02_)
  );
  or2v0x05 _24_ (
    .a(Q[3]),
    .b(_09_),
    .z(_11_)
  );
  aoi21v0x05 _25_ (
    .a1(Q[3]),
    .a2(_09_),
    .b(CLR),
    .z(_12_)
  );
  nr3abv0x05 _26_ (
    .a(_12_),
    .b(_11_),
    .c(CO),
    .z(_03_)
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _27_ (
    .cp(CLK),
    .d(_00_),
    .z(Q[0])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _28_ (
    .cp(CLK),
    .d(_01_),
    .z(Q[1])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _29_ (
    .cp(CLK),
    .d(_02_),
    .z(Q[2])
  );
  (* src = "utils.v:37.1-44.22" *)
  dfnt1v0x2 _30_ (
    .cp(CLK),
    .d(_03_),
    .z(Q[3])
  );
endmodule

(* src = "vga.v:1.1-77.10" *)
module vga(CLK, CLK_25MHZ, HS, VS, DRAW, PIX, LINE);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "vga.v:2.11-2.14" *)
  input CLK;
  wire CLK;
  (* src = "vga.v:3.12-3.21" *)
  output CLK_25MHZ;
  wire CLK_25MHZ;
  (* src = "vga.v:6.12-6.16" *)
  output DRAW;
  wire DRAW;
  (* src = "vga.v:4.12-4.14" *)
  output HS;
  wire HS;
  (* src = "vga.v:8.18-8.22" *)
  output [9:0] LINE;
  wire [9:0] LINE;
  (* src = "vga.v:7.18-7.21" *)
  output [9:0] PIX;
  wire [9:0] PIX;
  (* src = "vga.v:5.12-5.14" *)
  output VS;
  wire VS;
  (* src = "vga.v:29.20-29.29" *)
  wire clk_25MHz;
  (* src = "vga.v:23.12-23.17" *)
  wire [9:0] h_cnt;
  (* src = "vga.v:26.6-26.15" *)
  wire next_line;
  (* src = "vga.v:24.12-24.17" *)
  wire [9:0] v_cnt;
  or2v0x05 _32_ (
    .a(v_cnt[8]),
    .b(v_cnt[9]),
    .z(_00_)
  );
  oai21v0x05 _33_ (
    .a1(v_cnt[1]),
    .a2(v_cnt[0]),
    .b(v_cnt[2]),
    .z(_01_)
  );
  nr2v0x05 _34_ (
    .a(v_cnt[3]),
    .b(v_cnt[4]),
    .z(_02_)
  );
  or2v0x05 _35_ (
    .a(v_cnt[3]),
    .b(v_cnt[4]),
    .z(_03_)
  );
  aoi21bv0x05 _36_ (
    .a1(_01_),
    .a2(_02_),
    .b(v_cnt[5]),
    .z(_04_)
  );
  nr4v1x05 _37_ (
    .a(v_cnt[7]),
    .b(v_cnt[6]),
    .c(_00_),
    .d(_04_),
    .z(_05_)
  );
  oai31v0x05 _38_ (
    .a1(h_cnt[6]),
    .a2(h_cnt[4]),
    .a3(h_cnt[5]),
    .b(h_cnt[7]),
    .z(_06_)
  );
  or2v0x05 _39_ (
    .a(h_cnt[8]),
    .b(h_cnt[9]),
    .z(_07_)
  );
  nd2av0x05 _40_ (
    .a(_07_),
    .b(_06_),
    .z(_08_)
  );
  or4v0x05 _41_ (
    .a(v_cnt[7]),
    .b(v_cnt[6]),
    .c(v_cnt[5]),
    .d(v_cnt[2]),
    .z(_09_)
  );
  oai31v0x05 _42_ (
    .a1(v_cnt[8]),
    .a2(_03_),
    .a3(_09_),
    .b(v_cnt[9]),
    .z(_10_)
  );
  or4v0x05 _43_ (
    .a(h_cnt[3]),
    .b(h_cnt[2]),
    .c(h_cnt[1]),
    .d(h_cnt[0]),
    .z(_11_)
  );
  nd2av0x05 _44_ (
    .a(h_cnt[5]),
    .b(h_cnt[4]),
    .z(_12_)
  );
  nr4v1x05 _45_ (
    .a(h_cnt[6]),
    .b(h_cnt[7]),
    .c(_11_),
    .d(_12_),
    .z(_13_)
  );
  or4v0x05 _46_ (
    .a(h_cnt[6]),
    .b(h_cnt[7]),
    .c(h_cnt[4]),
    .d(h_cnt[5]),
    .z(_14_)
  );
  nd3v0x05 _47_ (
    .a(h_cnt[8]),
    .b(h_cnt[9]),
    .c(_14_),
    .z(_15_)
  );
  oai211v0x05 _48_ (
    .a1(_13_),
    .a2(_15_),
    .b(_08_),
    .c(_10_),
    .z(_16_)
  );
  nr2v0x05 _49_ (
    .a(_05_),
    .b(_16_),
    .z(DRAW)
  );
  nr3av0x05 _50_ (
    .a(h_cnt[0]),
    .b(_05_),
    .c(_16_),
    .z(PIX[0])
  );
  nr3av0x05 _51_ (
    .a(h_cnt[1]),
    .b(_05_),
    .c(_16_),
    .z(PIX[1])
  );
  nr3av0x05 _52_ (
    .a(h_cnt[2]),
    .b(_05_),
    .c(_16_),
    .z(PIX[2])
  );
  nr3av0x05 _53_ (
    .a(h_cnt[3]),
    .b(_05_),
    .c(_16_),
    .z(PIX[3])
  );
  nr3v0x05 _54_ (
    .a(h_cnt[4]),
    .b(_05_),
    .c(_16_),
    .z(PIX[4])
  );
  xor2v0x05 _55_ (
    .a(h_cnt[4]),
    .b(h_cnt[5]),
    .z(_17_)
  );
  nr3v0x05 _56_ (
    .a(_05_),
    .b(_16_),
    .c(_17_),
    .z(PIX[5])
  );
  xoon21v0x05 _57_ (
    .a1(h_cnt[4]),
    .a2(h_cnt[5]),
    .b(h_cnt[6]),
    .z(_18_)
  );
  nr3v0x05 _58_ (
    .a(_05_),
    .b(_16_),
    .c(_18_),
    .z(PIX[6])
  );
  nd2v0x05 _59_ (
    .a(_06_),
    .b(_14_),
    .z(_19_)
  );
  nr3v0x05 _60_ (
    .a(_05_),
    .b(_16_),
    .c(_19_),
    .z(PIX[7])
  );
  xnr2v0x05 _61_ (
    .a(h_cnt[8]),
    .b(_06_),
    .z(_20_)
  );
  nr3v0x05 _62_ (
    .a(_05_),
    .b(_16_),
    .c(_20_),
    .z(PIX[8])
  );
  oai21a2v0x05 _63_ (
    .a1(h_cnt[8]),
    .a2(_06_),
    .b(h_cnt[9]),
    .z(_21_)
  );
  aoi112v0x05 _64_ (
    .a(_05_),
    .b(_16_),
    .c1(_21_),
    .c2(_08_),
    .z(PIX[9])
  );
  nr3v0x05 _65_ (
    .a(v_cnt[0]),
    .b(_05_),
    .c(_16_),
    .z(LINE[0])
  );
  xor2v0x05 _66_ (
    .a(v_cnt[1]),
    .b(v_cnt[0]),
    .z(_22_)
  );
  nr3v0x05 _67_ (
    .a(_05_),
    .b(_16_),
    .c(_22_),
    .z(LINE[1])
  );
  xooi21v0x05 _68_ (
    .a1(v_cnt[1]),
    .a2(v_cnt[0]),
    .b(v_cnt[2]),
    .z(_23_)
  );
  nr3v0x05 _69_ (
    .a(_05_),
    .b(_16_),
    .c(_23_),
    .z(LINE[2])
  );
  xnr2v0x05 _70_ (
    .a(v_cnt[3]),
    .b(_01_),
    .z(_24_)
  );
  nr3v0x05 _71_ (
    .a(_05_),
    .b(_16_),
    .c(_24_),
    .z(LINE[3])
  );
  nd2av0x05 _72_ (
    .a(v_cnt[3]),
    .b(_01_),
    .z(_25_)
  );
  aoi22v0x05 _73_ (
    .a1(_01_),
    .a2(_02_),
    .b1(_25_),
    .b2(v_cnt[4]),
    .z(_26_)
  );
  nr3v0x05 _74_ (
    .a(_05_),
    .b(_16_),
    .c(_26_),
    .z(LINE[4])
  );
  nr3abv0x05 _75_ (
    .a(_02_),
    .b(_01_),
    .c(v_cnt[5]),
    .z(_27_)
  );
  nr4v1x05 _76_ (
    .a(_04_),
    .b(_05_),
    .c(_16_),
    .d(_27_),
    .z(LINE[5])
  );
  xor2v0x05 _77_ (
    .a(v_cnt[6]),
    .b(_04_),
    .z(_28_)
  );
  nr3v0x05 _78_ (
    .a(_05_),
    .b(_16_),
    .c(_28_),
    .z(LINE[6])
  );
  xoon21v0x05 _79_ (
    .a1(v_cnt[6]),
    .a2(_04_),
    .b(v_cnt[7]),
    .z(_29_)
  );
  nr3v0x05 _80_ (
    .a(_05_),
    .b(_16_),
    .c(_29_),
    .z(LINE[7])
  );
  oai31v0x05 _81_ (
    .a1(v_cnt[7]),
    .a2(v_cnt[6]),
    .a3(_04_),
    .b(v_cnt[8]),
    .z(_30_)
  );
  or4v0x05 _82_ (
    .a(v_cnt[7]),
    .b(v_cnt[8]),
    .c(v_cnt[6]),
    .d(_04_),
    .z(_31_)
  );
  aoi112v0x05 _83_ (
    .a(_05_),
    .b(_16_),
    .c1(_30_),
    .c2(_31_),
    .z(LINE[8])
  );
  nr4v1x05 _84_ (
    .a(v_cnt[1]),
    .b(_00_),
    .c(_03_),
    .d(_09_),
    .z(VS)
  );
  aoi112v0x05 _85_ (
    .a(h_cnt[7]),
    .b(_07_),
    .c1(h_cnt[5]),
    .c2(h_cnt[6]),
    .z(HS)
  );
  (* src = "vga.v:42.1-47.2" *)
  \$paramod$dac31f5b8da215793873bc3275fc490f79fae642\prescaler  MHz25 (
    .CE(1'h1),
    .CEO(clk_25MHz),
    .CLK(CLK)
  );
  (* src = "vga.v:54.1-61.2" *)
  \$paramod\up_cnt_mod\MODULO=10'1100100000\W=s32'00000000000000000000000000001010  hor_cnt (
    .CE(clk_25MHz),
    .CLK(CLK),
    .CLR(1'h0),
    .CO(next_line),
    .Q(h_cnt)
  );
  (* src = "vga.v:69.1-75.2" *)
  \$paramod\up_cnt_mod\MODULO=10'1000001101\W=s32'00000000000000000000000000001010  ver_cnt (
    .CE(next_line),
    .CLK(CLK),
    .CLR(1'h0),
    .Q(v_cnt)
  );
  assign CLK_25MHZ = clk_25MHz;
  assign LINE[9] = 1'h0;
endmodule
