/* Generated by Yosys 0.32+74 (git sha1 b739213d9, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "vga_controller.v:3.1-161.11" *)
module vga_controller(clk, rst, VSYNC, HSYNC, R, G, B);
  (* src = "vga_controller.v:72.2-158.4" *)
  wire [9:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  (* src = "vga_controller.v:9.19-9.20" *)
  output [3:0] B;
  wire [3:0] B;
  (* src = "vga_controller.v:8.19-8.20" *)
  output [3:0] G;
  wire [3:0] G;
  (* init = 1'h1 *)
  (* src = "vga_controller.v:6.19-6.24" *)
  output HSYNC;
  wire HSYNC;
  (* init = 10'h001 *)
  (* src = "vga_controller.v:20.12-20.21" *)
  wire [9:0] H_Counter;
  (* src = "vga_controller.v:7.19-7.20" *)
  output [3:0] R;
  wire [3:0] R;
  (* init = 4'h0 *)
  (* src = "vga_controller.v:30.12-30.23" *)
  wire [3:0] RGB_Counter;
  (* init = 1'h1 *)
  (* src = "vga_controller.v:6.13-6.18" *)
  output VSYNC;
  wire VSYNC;
  (* init = 1'h0 *)
  (* src = "vga_controller.v:32.6-32.13" *)
  wire V_CHECK;
  (* init = 10'h001 *)
  (* src = "vga_controller.v:27.12-27.21" *)
  wire [9:0] V_Counter;
  (* src = "vga_controller.v:5.8-5.11" *)
  input clk;
  wire clk;
  (* init = 32'd0 *)
  (* src = "vga_controller.v:11.10-11.23" *)
  wire [31:0] clock_counter;
  (* init = 1'h0 *)
  (* src = "vga_controller.v:12.6-12.17" *)
  wire divided_clk;
  (* src = "vga_controller.v:5.12-5.15" *)
  input rst;
  wire rst;
  (* init = 1'h1 *)
  (* src = "vga_controller.v:31.6-31.20" *)
  wire visible_enable;
  iv1v0x05 _168_ (
    .a(clock_counter[0]),
    .z(_020_)
  );
  iv1v0x05 _169_ (
    .a(clock_counter[11]),
    .z(_056_)
  );
  iv1v0x05 _170_ (
    .a(clock_counter[10]),
    .z(_057_)
  );
  iv1v0x05 _171_ (
    .a(clock_counter[12]),
    .z(_058_)
  );
  iv1v0x05 _172_ (
    .a(clock_counter[17]),
    .z(_059_)
  );
  iv1v0x05 _173_ (
    .a(clock_counter[19]),
    .z(_060_)
  );
  iv1v0x05 _174_ (
    .a(clock_counter[21]),
    .z(_061_)
  );
  iv1v0x05 _175_ (
    .a(clock_counter[20]),
    .z(_062_)
  );
  iv1v0x05 _176_ (
    .a(clock_counter[23]),
    .z(_063_)
  );
  iv1v0x05 _177_ (
    .a(clock_counter[25]),
    .z(_064_)
  );
  iv1v0x05 _178_ (
    .a(clock_counter[28]),
    .z(_065_)
  );
  iv1v0x05 _179_ (
    .a(clock_counter[30]),
    .z(_066_)
  );
  iv1v0x05 _180_ (
    .a(H_Counter[0]),
    .z(_067_)
  );
  iv1v0x05 _181_ (
    .a(H_Counter[5]),
    .z(_068_)
  );
  iv1v0x05 _182_ (
    .a(V_CHECK),
    .z(_069_)
  );
  nd3abv0x05 _183_ (
    .a(V_Counter[4]),
    .b(V_Counter[1]),
    .c(V_Counter[0]),
    .z(_070_)
  );
  nd2v0x05 _184_ (
    .a(V_Counter[3]),
    .b(V_Counter[2]),
    .z(_071_)
  );
  nd3abv0x05 _185_ (
    .a(V_Counter[8]),
    .b(_071_),
    .c(V_CHECK),
    .z(_072_)
  );
  nd2av0x05 _186_ (
    .a(V_Counter[7]),
    .b(V_Counter[9]),
    .z(_073_)
  );
  nr3v0x05 _187_ (
    .a(V_Counter[6]),
    .b(V_Counter[5]),
    .c(_073_),
    .z(_074_)
  );
  nd3abv0x05 _188_ (
    .a(_070_),
    .b(_072_),
    .c(_074_),
    .z(_075_)
  );
  or4v0x05 _189_ (
    .a(H_Counter[1]),
    .b(H_Counter[0]),
    .c(H_Counter[3]),
    .d(H_Counter[2]),
    .z(_076_)
  );
  nd2v0x05 _190_ (
    .a(H_Counter[9]),
    .b(H_Counter[8]),
    .z(_077_)
  );
  nd3abv0x05 _191_ (
    .a(H_Counter[4]),
    .b(_077_),
    .c(H_Counter[5]),
    .z(_078_)
  );
  nr4v1x05 _192_ (
    .a(H_Counter[7]),
    .b(H_Counter[6]),
    .c(_076_),
    .d(_078_),
    .z(_079_)
  );
  or4v0x05 _193_ (
    .a(H_Counter[4]),
    .b(H_Counter[7]),
    .c(H_Counter[6]),
    .d(_077_),
    .z(_080_)
  );
  nr4v1x05 _194_ (
    .a(_068_),
    .b(V_CHECK),
    .c(_076_),
    .d(_080_),
    .z(_081_)
  );
  aoi21v0x05 _195_ (
    .a1(V_Counter[0]),
    .a2(_075_),
    .b(_081_),
    .z(_082_)
  );
  aoi21v0x05 _196_ (
    .a1(V_Counter[0]),
    .a2(_081_),
    .b(_082_),
    .z(_000_[0])
  );
  an2v0x05 _197_ (
    .a(V_Counter[0]),
    .b(V_Counter[1]),
    .z(_083_)
  );
  xaon21v0x05 _198_ (
    .a1(V_Counter[0]),
    .a2(_081_),
    .b(V_Counter[1]),
    .z(_000_[1])
  );
  aoi22v0x05 _199_ (
    .a1(V_Counter[2]),
    .a2(_075_),
    .b1(_081_),
    .b2(_083_),
    .z(_084_)
  );
  an3v0x05 _200_ (
    .a(V_Counter[2]),
    .b(_081_),
    .c(_083_),
    .z(_085_)
  );
  nr2v0x05 _201_ (
    .a(_084_),
    .b(_085_),
    .z(_000_[2])
  );
  aoi21v0x05 _202_ (
    .a1(V_Counter[3]),
    .a2(_075_),
    .b(_085_),
    .z(_086_)
  );
  nd3v0x05 _203_ (
    .a(V_Counter[3]),
    .b(V_Counter[2]),
    .c(_083_),
    .z(_087_)
  );
  nr3abv0x05 _204_ (
    .a(_069_),
    .b(_079_),
    .c(_087_),
    .z(_088_)
  );
  nr2v0x05 _205_ (
    .a(_086_),
    .b(_088_),
    .z(_000_[3])
  );
  xor2v0x05 _206_ (
    .a(V_Counter[4]),
    .b(_088_),
    .z(_000_[4])
  );
  aoi21v0x05 _207_ (
    .a1(V_Counter[4]),
    .a2(_088_),
    .b(V_Counter[5]),
    .z(_089_)
  );
  an3v0x05 _208_ (
    .a(V_Counter[5]),
    .b(V_Counter[4]),
    .c(_088_),
    .z(_090_)
  );
  nr2v0x05 _209_ (
    .a(_089_),
    .b(_090_),
    .z(_000_[5])
  );
  xor2v0x05 _210_ (
    .a(V_Counter[6]),
    .b(_090_),
    .z(_000_[6])
  );
  xaon21v0x05 _211_ (
    .a1(V_Counter[6]),
    .a2(_090_),
    .b(V_Counter[7]),
    .z(_000_[7])
  );
  nd3v0x05 _212_ (
    .a(V_Counter[7]),
    .b(V_Counter[6]),
    .c(_090_),
    .z(_091_)
  );
  nd4v0x05 _213_ (
    .a(V_Counter[8]),
    .b(V_Counter[7]),
    .c(V_Counter[6]),
    .d(_090_),
    .z(_092_)
  );
  xnr2v0x05 _214_ (
    .a(V_Counter[8]),
    .b(_091_),
    .z(_000_[8])
  );
  nd3v0x05 _215_ (
    .a(V_Counter[9]),
    .b(_075_),
    .c(_092_),
    .z(_093_)
  );
  oai21v0x05 _216_ (
    .a1(V_Counter[9]),
    .a2(_092_),
    .b(_093_),
    .z(_000_[9])
  );
  nr4v1x05 _217_ (
    .a(clock_counter[5]),
    .b(clock_counter[4]),
    .c(clock_counter[7]),
    .d(clock_counter[6]),
    .z(_094_)
  );
  nd2av0x05 _218_ (
    .a(clock_counter[1]),
    .b(clock_counter[0]),
    .z(_095_)
  );
  nr3v0x05 _219_ (
    .a(clock_counter[3]),
    .b(clock_counter[2]),
    .c(_095_),
    .z(_096_)
  );
  nr4v1x05 _220_ (
    .a(clock_counter[13]),
    .b(clock_counter[12]),
    .c(clock_counter[15]),
    .d(clock_counter[14]),
    .z(_097_)
  );
  or4v0x05 _221_ (
    .a(clock_counter[9]),
    .b(clock_counter[8]),
    .c(clock_counter[11]),
    .d(clock_counter[10]),
    .z(_098_)
  );
  or4v0x05 _222_ (
    .a(clock_counter[25]),
    .b(clock_counter[24]),
    .c(clock_counter[31]),
    .d(clock_counter[30]),
    .z(_099_)
  );
  nr4v1x05 _223_ (
    .a(clock_counter[29]),
    .b(clock_counter[28]),
    .c(_098_),
    .d(_099_),
    .z(_100_)
  );
  nd4v0x05 _224_ (
    .a(_094_),
    .b(_096_),
    .c(_097_),
    .d(_100_),
    .z(_101_)
  );
  nr3v0x05 _225_ (
    .a(clock_counter[23]),
    .b(clock_counter[27]),
    .c(clock_counter[26]),
    .z(_102_)
  );
  nd3v0x05 _226_ (
    .a(_061_),
    .b(_062_),
    .c(_102_),
    .z(_103_)
  );
  nr3v0x05 _227_ (
    .a(clock_counter[16]),
    .b(clock_counter[19]),
    .c(clock_counter[18]),
    .z(_104_)
  );
  nd3abv0x05 _228_ (
    .a(clock_counter[17]),
    .b(clock_counter[22]),
    .c(_104_),
    .z(_105_)
  );
  nr3v0x05 _229_ (
    .a(_101_),
    .b(_103_),
    .c(_105_),
    .z(_106_)
  );
  xor2v0x05 _230_ (
    .a(divided_clk),
    .b(_106_),
    .z(_001_)
  );
  nd3v0x05 _231_ (
    .a(V_Counter[7]),
    .b(V_Counter[6]),
    .c(V_Counter[5]),
    .z(_107_)
  );
  nr2v0x05 _232_ (
    .a(V_Counter[4]),
    .b(_107_),
    .z(_108_)
  );
  oai21v0x05 _233_ (
    .a1(V_Counter[2]),
    .a2(_083_),
    .b(V_Counter[3]),
    .z(_109_)
  );
  aoi21v0x05 _234_ (
    .a1(_108_),
    .a2(_109_),
    .b(_107_),
    .z(_110_)
  );
  nd3abv0x05 _235_ (
    .a(V_Counter[9]),
    .b(_110_),
    .c(V_Counter[8]),
    .z(_111_)
  );
  oai211v0x05 _236_ (
    .a1(V_Counter[8]),
    .a2(V_Counter[9]),
    .b(_111_),
    .c(V_CHECK),
    .z(_112_)
  );
  oai211v0x05 _237_ (
    .a1(V_Counter[0]),
    .a2(V_Counter[1]),
    .b(V_Counter[3]),
    .c(V_Counter[2]),
    .z(_113_)
  );
  aoi21v0x05 _238_ (
    .a1(_108_),
    .a2(_113_),
    .b(_107_),
    .z(_114_)
  );
  nd3abv0x05 _239_ (
    .a(V_Counter[9]),
    .b(_114_),
    .c(V_Counter[8]),
    .z(_115_)
  );
  mxn2v0x05 _240_ (
    .a0(_115_),
    .a1(VSYNC),
    .s(_112_),
    .z(_002_)
  );
  oai31v0x05 _241_ (
    .a1(H_Counter[5]),
    .a2(H_Counter[4]),
    .a3(H_Counter[6]),
    .b(H_Counter[7]),
    .z(_116_)
  );
  oai21a2v0x05 _242_ (
    .a1(H_Counter[8]),
    .a2(_116_),
    .b(H_Counter[9]),
    .z(_117_)
  );
  nr2v0x05 _243_ (
    .a(H_Counter[5]),
    .b(_076_),
    .z(_118_)
  );
  nr3abv0x05 _244_ (
    .a(H_Counter[4]),
    .b(H_Counter[7]),
    .c(H_Counter[6]),
    .z(_119_)
  );
  nr3abv0x05 _245_ (
    .a(H_Counter[9]),
    .b(_119_),
    .c(H_Counter[8]),
    .z(_120_)
  );
  aoi21v0x05 _246_ (
    .a1(_118_),
    .a2(_120_),
    .b(_117_),
    .z(_121_)
  );
  nr3v0x05 _247_ (
    .a(H_Counter[5]),
    .b(H_Counter[7]),
    .c(H_Counter[6]),
    .z(_122_)
  );
  nr3v0x05 _248_ (
    .a(_077_),
    .b(_079_),
    .c(_122_),
    .z(_123_)
  );
  nr3abv0x05 _249_ (
    .a(_069_),
    .b(_121_),
    .c(_123_),
    .z(_124_)
  );
  an4v0x05 _250_ (
    .a(H_Counter[5]),
    .b(H_Counter[4]),
    .c(H_Counter[7]),
    .d(H_Counter[6]),
    .z(_125_)
  );
  aoi21v0x05 _251_ (
    .a1(_076_),
    .a2(_125_),
    .b(H_Counter[8]),
    .z(_126_)
  );
  nr3av0x05 _252_ (
    .a(H_Counter[9]),
    .b(_123_),
    .c(_126_),
    .z(_127_)
  );
  mxn2v0x05 _253_ (
    .a0(HSYNC),
    .a1(_127_),
    .s(_124_),
    .z(_003_)
  );
  oai23av0x05 _254_ (
    .a3(_079_),
    .b1(_069_),
    .b2(_067_),
    .z(_004_)
  );
  nd2v0x05 _255_ (
    .a(H_Counter[1]),
    .b(H_Counter[0]),
    .z(_128_)
  );
  xooi21v0x05 _256_ (
    .a1(_067_),
    .a2(V_CHECK),
    .b(H_Counter[1]),
    .z(_005_)
  );
  nd3abv0x05 _257_ (
    .a(V_CHECK),
    .b(_128_),
    .c(H_Counter[2]),
    .z(_129_)
  );
  xooi21v0x05 _258_ (
    .a1(V_CHECK),
    .a2(_128_),
    .b(H_Counter[2]),
    .z(_006_)
  );
  nr2av0x1 _259_ (
    .a(H_Counter[3]),
    .b(_129_),
    .z(_130_)
  );
  xnr2v0x05 _260_ (
    .a(H_Counter[3]),
    .b(_129_),
    .z(_007_)
  );
  xor2v0x05 _261_ (
    .a(H_Counter[4]),
    .b(_130_),
    .z(_008_)
  );
  nd3v0x05 _262_ (
    .a(H_Counter[5]),
    .b(H_Counter[4]),
    .c(_130_),
    .z(_131_)
  );
  xaoi21v0x05 _263_ (
    .a1(H_Counter[4]),
    .a2(_130_),
    .b(H_Counter[5]),
    .z(_132_)
  );
  nr2v0x05 _264_ (
    .a(_081_),
    .b(_132_),
    .z(_009_)
  );
  xnr2v0x05 _265_ (
    .a(H_Counter[6]),
    .b(_131_),
    .z(_010_)
  );
  aoi21a2v0x05 _266_ (
    .a1(H_Counter[6]),
    .a2(_131_),
    .b(H_Counter[7]),
    .z(_133_)
  );
  an2v0x05 _267_ (
    .a(_125_),
    .b(_130_),
    .z(_134_)
  );
  nr2v0x05 _268_ (
    .a(_133_),
    .b(_134_),
    .z(_011_)
  );
  xnr2v0x05 _269_ (
    .a(H_Counter[8]),
    .b(_134_),
    .z(_135_)
  );
  nr2v0x05 _270_ (
    .a(_081_),
    .b(_135_),
    .z(_012_)
  );
  xaoi21v0x05 _271_ (
    .a1(H_Counter[8]),
    .a2(_134_),
    .b(H_Counter[9]),
    .z(_136_)
  );
  nr2v0x05 _272_ (
    .a(_081_),
    .b(_136_),
    .z(_013_)
  );
  nr4v1x05 _273_ (
    .a(V_Counter[3]),
    .b(V_Counter[2]),
    .c(V_Counter[0]),
    .d(V_Counter[1]),
    .z(_137_)
  );
  aoi21v0x05 _274_ (
    .a1(_108_),
    .a2(_137_),
    .b(_107_),
    .z(_138_)
  );
  nd3abv0x05 _275_ (
    .a(V_Counter[9]),
    .b(_138_),
    .c(V_Counter[8]),
    .z(_139_)
  );
  oai211v0x05 _276_ (
    .a1(V_Counter[8]),
    .a2(V_Counter[9]),
    .b(_139_),
    .c(V_CHECK),
    .z(_140_)
  );
  oan21v0x05 _277_ (
    .a1(visible_enable),
    .a2(V_CHECK),
    .b(_140_),
    .z(_014_)
  );
  xnr2v0x05 _278_ (
    .a(RGB_Counter[0]),
    .b(V_CHECK),
    .z(_015_)
  );
  nr3abv0x05 _279_ (
    .a(RGB_Counter[1]),
    .b(RGB_Counter[0]),
    .c(V_CHECK),
    .z(_141_)
  );
  xaon21v0x05 _280_ (
    .a1(RGB_Counter[0]),
    .a2(_069_),
    .b(RGB_Counter[1]),
    .z(_016_)
  );
  xor2v0x05 _281_ (
    .a(RGB_Counter[2]),
    .b(_141_),
    .z(_017_)
  );
  xaon21v0x05 _282_ (
    .a1(RGB_Counter[2]),
    .a2(_141_),
    .b(RGB_Counter[3]),
    .z(_018_)
  );
  an3v0x05 _283_ (
    .a(_079_),
    .b(_124_),
    .c(_127_),
    .z(_019_)
  );
  nd2v0x05 _284_ (
    .a(_020_),
    .b(clock_counter[1]),
    .z(_142_)
  );
  aoi21v0x05 _285_ (
    .a1(_095_),
    .a2(_142_),
    .b(_106_),
    .z(_021_)
  );
  xaon21v0x05 _286_ (
    .a1(clock_counter[0]),
    .a2(clock_counter[1]),
    .b(clock_counter[2]),
    .z(_022_)
  );
  an4v0x05 _287_ (
    .a(clock_counter[0]),
    .b(clock_counter[1]),
    .c(clock_counter[3]),
    .d(clock_counter[2]),
    .z(_143_)
  );
  aoi31v0x05 _288_ (
    .a1(clock_counter[0]),
    .a2(clock_counter[1]),
    .a3(clock_counter[2]),
    .b(clock_counter[3]),
    .z(_144_)
  );
  nr2v0x05 _289_ (
    .a(_143_),
    .b(_144_),
    .z(_023_)
  );
  xor2v0x05 _290_ (
    .a(clock_counter[4]),
    .b(_143_),
    .z(_024_)
  );
  xaon21v0x05 _291_ (
    .a1(clock_counter[4]),
    .a2(_143_),
    .b(clock_counter[5]),
    .z(_025_)
  );
  an4v0x05 _292_ (
    .a(clock_counter[5]),
    .b(clock_counter[4]),
    .c(clock_counter[6]),
    .d(_143_),
    .z(_145_)
  );
  aoi31v0x05 _293_ (
    .a1(clock_counter[5]),
    .a2(clock_counter[4]),
    .a3(_143_),
    .b(clock_counter[6]),
    .z(_146_)
  );
  nr2v0x05 _294_ (
    .a(_145_),
    .b(_146_),
    .z(_026_)
  );
  an2v0x05 _295_ (
    .a(clock_counter[7]),
    .b(_145_),
    .z(_147_)
  );
  xor2v0x05 _296_ (
    .a(clock_counter[7]),
    .b(_145_),
    .z(_027_)
  );
  xor2v0x05 _297_ (
    .a(clock_counter[8]),
    .b(_147_),
    .z(_028_)
  );
  nd4v0x05 _298_ (
    .a(clock_counter[7]),
    .b(clock_counter[9]),
    .c(clock_counter[8]),
    .d(_145_),
    .z(_148_)
  );
  xaon21v0x05 _299_ (
    .a1(clock_counter[8]),
    .a2(_147_),
    .b(clock_counter[9]),
    .z(_029_)
  );
  nr2v0x05 _300_ (
    .a(_057_),
    .b(_148_),
    .z(_149_)
  );
  xnr2v0x05 _301_ (
    .a(clock_counter[10]),
    .b(_148_),
    .z(_030_)
  );
  xnr2v0x05 _302_ (
    .a(_056_),
    .b(_149_),
    .z(_031_)
  );
  nr4v1x05 _303_ (
    .a(_056_),
    .b(_057_),
    .c(_058_),
    .d(_148_),
    .z(_150_)
  );
  xaoi21v0x05 _304_ (
    .a1(clock_counter[11]),
    .a2(_149_),
    .b(_058_),
    .z(_032_)
  );
  an2v0x05 _305_ (
    .a(clock_counter[13]),
    .b(_150_),
    .z(_151_)
  );
  xor2v0x05 _306_ (
    .a(clock_counter[13]),
    .b(_150_),
    .z(_033_)
  );
  xor2v0x05 _307_ (
    .a(clock_counter[14]),
    .b(_151_),
    .z(_034_)
  );
  an4v0x05 _308_ (
    .a(clock_counter[13]),
    .b(clock_counter[15]),
    .c(clock_counter[14]),
    .d(_150_),
    .z(_152_)
  );
  aoi21v0x05 _309_ (
    .a1(clock_counter[14]),
    .a2(_151_),
    .b(clock_counter[15]),
    .z(_153_)
  );
  nr2v0x05 _310_ (
    .a(_152_),
    .b(_153_),
    .z(_035_)
  );
  nd2v0x05 _311_ (
    .a(clock_counter[16]),
    .b(_152_),
    .z(_154_)
  );
  xor2v0x05 _312_ (
    .a(clock_counter[16]),
    .b(_152_),
    .z(_036_)
  );
  xnr2v0x05 _313_ (
    .a(clock_counter[17]),
    .b(_154_),
    .z(_037_)
  );
  nd4v0x05 _314_ (
    .a(clock_counter[17]),
    .b(clock_counter[16]),
    .c(clock_counter[18]),
    .d(_152_),
    .z(_155_)
  );
  xooi21v0x05 _315_ (
    .a1(_059_),
    .a2(_154_),
    .b(clock_counter[18]),
    .z(_038_)
  );
  nr2v0x05 _316_ (
    .a(_060_),
    .b(_155_),
    .z(_156_)
  );
  xnr2v0x05 _317_ (
    .a(clock_counter[19]),
    .b(_155_),
    .z(_039_)
  );
  xnr2v0x05 _318_ (
    .a(_062_),
    .b(_156_),
    .z(_040_)
  );
  nr4v1x05 _319_ (
    .a(_060_),
    .b(_061_),
    .c(_062_),
    .d(_155_),
    .z(_157_)
  );
  xaoi21v0x05 _320_ (
    .a1(clock_counter[20]),
    .a2(_156_),
    .b(_061_),
    .z(_041_)
  );
  nd2v0x05 _321_ (
    .a(clock_counter[22]),
    .b(_157_),
    .z(_158_)
  );
  xor2v0x05 _322_ (
    .a(clock_counter[22]),
    .b(_157_),
    .z(_042_)
  );
  xnr2v0x05 _323_ (
    .a(clock_counter[23]),
    .b(_158_),
    .z(_043_)
  );
  nd4v0x05 _324_ (
    .a(clock_counter[23]),
    .b(clock_counter[22]),
    .c(clock_counter[24]),
    .d(_157_),
    .z(_159_)
  );
  xooi21v0x05 _325_ (
    .a1(_063_),
    .a2(_158_),
    .b(clock_counter[24]),
    .z(_044_)
  );
  xnr2v0x05 _326_ (
    .a(clock_counter[25]),
    .b(_159_),
    .z(_045_)
  );
  nr3abv0x05 _327_ (
    .a(clock_counter[25]),
    .b(clock_counter[26]),
    .c(_159_),
    .z(_160_)
  );
  xooi21v0x05 _328_ (
    .a1(_064_),
    .a2(_159_),
    .b(clock_counter[26]),
    .z(_046_)
  );
  nd2v0x05 _329_ (
    .a(clock_counter[27]),
    .b(_160_),
    .z(_161_)
  );
  xor2v0x05 _330_ (
    .a(clock_counter[27]),
    .b(_160_),
    .z(_047_)
  );
  xnr2v0x05 _331_ (
    .a(clock_counter[28]),
    .b(_161_),
    .z(_048_)
  );
  nd4v0x05 _332_ (
    .a(clock_counter[27]),
    .b(clock_counter[29]),
    .c(clock_counter[28]),
    .d(_160_),
    .z(_162_)
  );
  xooi21v0x05 _333_ (
    .a1(_065_),
    .a2(_161_),
    .b(clock_counter[29]),
    .z(_049_)
  );
  xnr2v0x05 _334_ (
    .a(clock_counter[30]),
    .b(_162_),
    .z(_050_)
  );
  xooi21v0x05 _335_ (
    .a1(_066_),
    .a2(_162_),
    .b(clock_counter[31]),
    .z(_051_)
  );
  aoi21a2v0x05 _336_ (
    .a1(_121_),
    .a2(_127_),
    .b(V_CHECK),
    .z(_163_)
  );
  an2v0x05 _337_ (
    .a(visible_enable),
    .b(RGB_Counter[0]),
    .z(_164_)
  );
  mxn2v0x05 _338_ (
    .a0(G[0]),
    .a1(_164_),
    .s(_163_),
    .z(_052_)
  );
  an2v0x05 _339_ (
    .a(visible_enable),
    .b(RGB_Counter[1]),
    .z(_165_)
  );
  mxn2v0x05 _340_ (
    .a0(G[1]),
    .a1(_165_),
    .s(_163_),
    .z(_053_)
  );
  an2v0x05 _341_ (
    .a(visible_enable),
    .b(RGB_Counter[2]),
    .z(_166_)
  );
  mxn2v0x05 _342_ (
    .a0(G[2]),
    .a1(_166_),
    .s(_163_),
    .z(_054_)
  );
  an2v0x05 _343_ (
    .a(RGB_Counter[3]),
    .b(visible_enable),
    .z(_167_)
  );
  mxn2v0x05 _344_ (
    .a0(G[3]),
    .a1(_167_),
    .s(_163_),
    .z(_055_)
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _345_ (
    .cp(clk),
    .d(_001_),
    .z(divided_clk)
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _346_ (
    .cp(divided_clk),
    .d(_002_),
    .z(VSYNC)
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _347_ (
    .cp(divided_clk),
    .d(_003_),
    .z(HSYNC)
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _348_ (
    .cp(divided_clk),
    .d(_000_[0]),
    .z(V_Counter[0])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _349_ (
    .cp(divided_clk),
    .d(_000_[1]),
    .z(V_Counter[1])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _350_ (
    .cp(divided_clk),
    .d(_000_[2]),
    .z(V_Counter[2])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _351_ (
    .cp(divided_clk),
    .d(_000_[3]),
    .z(V_Counter[3])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _352_ (
    .cp(divided_clk),
    .d(_000_[4]),
    .z(V_Counter[4])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _353_ (
    .cp(divided_clk),
    .d(_000_[5]),
    .z(V_Counter[5])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _354_ (
    .cp(divided_clk),
    .d(_000_[6]),
    .z(V_Counter[6])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _355_ (
    .cp(divided_clk),
    .d(_000_[7]),
    .z(V_Counter[7])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _356_ (
    .cp(divided_clk),
    .d(_000_[8]),
    .z(V_Counter[8])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _357_ (
    .cp(divided_clk),
    .d(_000_[9]),
    .z(V_Counter[9])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _358_ (
    .cp(divided_clk),
    .d(_004_),
    .z(H_Counter[0])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _359_ (
    .cp(divided_clk),
    .d(_005_),
    .z(H_Counter[1])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _360_ (
    .cp(divided_clk),
    .d(_006_),
    .z(H_Counter[2])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _361_ (
    .cp(divided_clk),
    .d(_007_),
    .z(H_Counter[3])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _362_ (
    .cp(divided_clk),
    .d(_008_),
    .z(H_Counter[4])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _363_ (
    .cp(divided_clk),
    .d(_009_),
    .z(H_Counter[5])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _364_ (
    .cp(divided_clk),
    .d(_010_),
    .z(H_Counter[6])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _365_ (
    .cp(divided_clk),
    .d(_011_),
    .z(H_Counter[7])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _366_ (
    .cp(divided_clk),
    .d(_012_),
    .z(H_Counter[8])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _367_ (
    .cp(divided_clk),
    .d(_013_),
    .z(H_Counter[9])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _368_ (
    .cp(divided_clk),
    .d(_014_),
    .z(visible_enable)
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _369_ (
    .cp(divided_clk),
    .d(_015_),
    .z(RGB_Counter[0])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _370_ (
    .cp(divided_clk),
    .d(_016_),
    .z(RGB_Counter[1])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _371_ (
    .cp(divided_clk),
    .d(_017_),
    .z(RGB_Counter[2])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _372_ (
    .cp(divided_clk),
    .d(_018_),
    .z(RGB_Counter[3])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _373_ (
    .cp(divided_clk),
    .d(_019_),
    .z(V_CHECK)
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _374_ (
    .cp(clk),
    .d(_020_),
    .z(clock_counter[0])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _375_ (
    .cp(clk),
    .d(_021_),
    .z(clock_counter[1])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _376_ (
    .cp(clk),
    .d(_022_),
    .z(clock_counter[2])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _377_ (
    .cp(clk),
    .d(_023_),
    .z(clock_counter[3])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _378_ (
    .cp(clk),
    .d(_024_),
    .z(clock_counter[4])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _379_ (
    .cp(clk),
    .d(_025_),
    .z(clock_counter[5])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _380_ (
    .cp(clk),
    .d(_026_),
    .z(clock_counter[6])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _381_ (
    .cp(clk),
    .d(_027_),
    .z(clock_counter[7])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _382_ (
    .cp(clk),
    .d(_028_),
    .z(clock_counter[8])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _383_ (
    .cp(clk),
    .d(_029_),
    .z(clock_counter[9])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _384_ (
    .cp(clk),
    .d(_030_),
    .z(clock_counter[10])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _385_ (
    .cp(clk),
    .d(_031_),
    .z(clock_counter[11])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _386_ (
    .cp(clk),
    .d(_032_),
    .z(clock_counter[12])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _387_ (
    .cp(clk),
    .d(_033_),
    .z(clock_counter[13])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _388_ (
    .cp(clk),
    .d(_034_),
    .z(clock_counter[14])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _389_ (
    .cp(clk),
    .d(_035_),
    .z(clock_counter[15])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _390_ (
    .cp(clk),
    .d(_036_),
    .z(clock_counter[16])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _391_ (
    .cp(clk),
    .d(_037_),
    .z(clock_counter[17])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _392_ (
    .cp(clk),
    .d(_038_),
    .z(clock_counter[18])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _393_ (
    .cp(clk),
    .d(_039_),
    .z(clock_counter[19])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _394_ (
    .cp(clk),
    .d(_040_),
    .z(clock_counter[20])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _395_ (
    .cp(clk),
    .d(_041_),
    .z(clock_counter[21])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _396_ (
    .cp(clk),
    .d(_042_),
    .z(clock_counter[22])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _397_ (
    .cp(clk),
    .d(_043_),
    .z(clock_counter[23])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _398_ (
    .cp(clk),
    .d(_044_),
    .z(clock_counter[24])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _399_ (
    .cp(clk),
    .d(_045_),
    .z(clock_counter[25])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _400_ (
    .cp(clk),
    .d(_046_),
    .z(clock_counter[26])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _401_ (
    .cp(clk),
    .d(_047_),
    .z(clock_counter[27])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _402_ (
    .cp(clk),
    .d(_048_),
    .z(clock_counter[28])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _403_ (
    .cp(clk),
    .d(_049_),
    .z(clock_counter[29])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _404_ (
    .cp(clk),
    .d(_050_),
    .z(clock_counter[30])
  );
  (* src = "vga_controller.v:51.2-69.5" *)
  dfnt1v0x2 _405_ (
    .cp(clk),
    .d(_051_),
    .z(clock_counter[31])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _406_ (
    .cp(divided_clk),
    .d(_052_),
    .z(G[0])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _407_ (
    .cp(divided_clk),
    .d(_053_),
    .z(G[1])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _408_ (
    .cp(divided_clk),
    .d(_054_),
    .z(G[2])
  );
  (* src = "vga_controller.v:72.2-158.4" *)
  dfnt1v0x2 _409_ (
    .cp(divided_clk),
    .d(_055_),
    .z(G[3])
  );
  assign B = G;
  assign R = G;
endmodule
